### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by apfohl** [kemalcr/kemal#13]
How can I run tests when using `kemal` which starts a server while running tests and does not exit?

**Comment by sdogruyol** [comment]
https://github.com/kemalcr/kemal/blob/master/src/kemal.cr#L11-L15

**Comment by apfohl** [comment]
What do you mean exactly?

**Comment by sdogruyol** [comment]
You can spawn a server like that. Could you please detail your issue?

**Comment by apfohl** [comment]
I don't want, that a server is started, when running `crystal spec`. Would you suggest to use `require "kemal/*"` instead of `require "kemal"` and implement the start-server part myself?

**Comment by apfohl** [comment]
Ok, I just found out what the problem was. Instead of `require "kemal/*"` I had to use `require "kemal/kemal/*"` to get everything but the main `kemal.cr` file which contains the server starting part. Now, without getting `at_exit`set for the specs all is working well.

**Comment by sdogruyol** [comment]
:+1:
