### ISSUE TITLE
Missing --env option

### ISSUE THREAD

**Issue by Sija** [kemalcr/kemal#258]
Somehow `--env` option is missing (which according to issue #116 should work) resulting in:
```
Invalid option: --env (OptionParser::InvalidOption)
0x104d2baa5: *CallStack::new:CallStack at ??
0x104e0be2b: ~procProc(String, Nil)@/usr/local/Cellar/crystal-lang/0.20.0/src/option_parser.cr:70 at ??
0x104e0986f: *Kemal::run<Nil>:Nil at ??
0x104d425ef: main at ??
```

I know there's `KEMAL_ENV` variable but still having the option would be preferable.

**Comment by Sija** [comment]
I can send a PR if you'd like.

**Comment by sdogruyol** [comment]
Is there any specific use case over `KEMAL_ENV`?

**Comment by Sija** [comment]
Sometimes one is not in control of ENV variables, also every other Ruby server provides `--env` argument.

**Comment by sdogruyol** [comment]
Actually you can customize option parser to support extra parameters 😄 It's not documented but here you go

https://github.com/sdogruyol/kemal/blob/ad9790b9d844c66dca4053272dba91b9b7b2dfb3/spec/config_spec.cr#L40-L53
