### ISSUE TITLE
Upgrade Radix dependency to v0.3.5

### ISSUE THREAD

**Issue by luislavena** [kemalcr/kemal#261]
Hello,

Just released v0.3.5 to address bug reported in luislavena/radix#14.

Was going to sent a pull request and also recommend the usage of pessimistic operator (`~>`), but wasn't sure if specific version locking was intentional.

Let me know if you're OK with it and I can send the request.

Thank you :heart: :heart: :heart:

**Comment by sdogruyol** [comment]
Hey @luislavena thanks for the request. We can arrange this for the next version of Kemal. 
Can you please send the PR ❤️

**Comment by airinfection** [comment]
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by airinfection** [comment]
marry me serdarski ❤️❤️❤️❤️❤️❤️

**Comment by airinfection** [comment]
i mean gay marriage

**Comment by luislavena** [comment]
@sdogruyol done in #262 

Cheers!
