### ISSUE TITLE
/__kemal__/:image route broken

### ISSUE THREAD

**Issue by Sija** [kemalcr/kemal#263]
### Issue 1:
Calling `/__kemal__/404.png` should return image but it doesn't work due to wrong path set in code - `lib/kemal/images` in https://github.com/kemalcr/kemal/blob/master/src/kemal.cr#L41.

  - Solution: Move `image` folder out of `src` to match path in code and make folder hierarchy cleaner since it doesn't rly belong to `src`.

### Issue 2:
Calling `/__kemal__/unknown-image.png` returns `200 OK` instead of `404 Not Found`

  - Solution: Send `404` in else branch.

**Comment by sdogruyol** [comment]
Thanks for reporting 👍
