### ISSUE TITLE
Kemal Guide is not covering many aspect

### ISSUE THREAD

**Issue by airinfection** [kemalcr/kemal#268]
It needs improvement.

**Comment by sdogruyol** [comment]
Hello there, what's missing for you? 

Any improvements and PRs are welcome 👍 Thanks

**Comment by airinfection** [comment]
database mysql still redirecting to waterlink instead of crystal's one.

**Comment by airinfection** [comment]
there is no file uploads operations example. + crystal installation guide would be useful for those who are coming by seeing kemal first.

**Comment by airinfection** [comment]
https://github.com/crystal-lang/crystal-mysql
https://github.com/crystal-lang/crystal-sqlite3

**Comment by airinfection** [comment]
yes you gave the installation for crystal but it needs also libbsd-dev \
  libedit-dev \
  libevent-core-2.0-5 \
  libevent-dev \
  libevent-extra-2.0-5 \
  libevent-openssl-2.0-5 \
  libevent-pthreads-2.0-5 \
  libgmp-dev \
  libgmpxx4ldbl \
  libssl-dev \
  libxml2-dev \
  libyaml-dev \
  libreadline-dev

to run properly.

**Comment by sdogruyol** [comment]
Getting Started already contains a link to official installation guide http://kemalcr.com/docs/getting_started/

**Comment by airinfection** [comment]
official installation guide is not working without external libraries. you can only do basic operations.
