### ISSUE TITLE
Kemal.stop

### ISSUE THREAD

**Issue by kostya** [kemalcr/kemal#269]
would be nice if there stop command, which stop accepting new connections. after that i can manually wait for all current jobs (slow requests), send response to clients, and quit this process. this is useful for graceful restarts.

```crystal
require "kemal"

post "/job" do
  # some background slow Job....
end

trap("QUIT") do
  Kemal.stop
end

Kemal.run

# wait for all executed jobs
# ...


```

**Comment by sdogruyol** [comment]
Thanks for the request. It's not implemented in master 👍

**Comment by kostya** [comment]
thanks, works nice, as expected

**Comment by sdogruyol** [comment]
👍

**Comment by rdp** [comment]
I assume you meant "now implemented" there :) Is there an easy way to "join" on all outstanding requests or do they all run to completion before it exits or anything like that? or does stop already do that? Thanks!
