### ISSUE TITLE
Error writing file: Broken pipe

### ISSUE THREAD

**Issue by flagello** [kemalcr/kemal#272]
<img width="645" alt="screen shot 2016-12-08 at 23 23 37" src="https://cloud.githubusercontent.com/assets/649779/21030171/74b0cf90-bd9d-11e6-9d99-8ece2cc33c0a.png">
<img width="645" alt="screen shot 2016-12-08 at 23 34 07" src="https://cloud.githubusercontent.com/assets/649779/21030505/2ef3aee4-bd9f-11e6-9a0e-d822aa67f0b1.png">
<img width="640" alt="screen shot 2016-12-08 at 23 34 44" src="https://cloud.githubusercontent.com/assets/649779/21030520/3a0e90c8-bd9f-11e6-8644-2d23947c3ace.png">
<img width="645" alt="screen shot 2016-12-08 at 23 36 03" src="https://cloud.githubusercontent.com/assets/649779/21030536/46f0eae8-bd9f-11e6-9433-b528cfba0a03.png">
<img width="645" alt="screen shot 2016-12-08 at 23 22 58" src="https://cloud.githubusercontent.com/assets/649779/21030170/73e50d60-bd9d-11e6-8eb5-d4bfbd6f7e2d.png">
<br><br>
With a configuration as simple as<br><br>
<img width="247" alt="screen shot 2016-12-08 at 23 27 34" src="https://cloud.githubusercontent.com/assets/649779/21030276/f6a25726-bd9d-11e6-9db8-e148d638ea4c.png"><br><br>

Although it might be a bug in Crystal?

**Comment by sdogruyol** [comment]
@flagello thanks for your report. I couldn't reproduce the error with the same code.

What's your Crystal and Kemal version?

**Comment by flagello** [comment]
<img width="210" alt="screen shot 2016-12-09 at 16 03 45" src="https://cloud.githubusercontent.com/assets/649779/21053306/250ef610-be29-11e6-997e-0a1c71fe9922.png"><br>

(Thanks for Kemal, @sdogruyol!)

**Comment by sdogruyol** [comment]
@flagello thank you.

Could you please update to Crystal `0.20.1`?

**Comment by flagello** [comment]
Done. No luck.

**Comment by sdogruyol** [comment]
I can't reproduce this on OS X 10.11. Would be happy to dig into it

**Comment by flagello** [comment]
I'm on 10.12.1, might be that. Thanks @sdogruyol!

**Comment by denysvitali** [comment]
Same here, I opened #300, and I think it's a related issue
