### ISSUE TITLE
Unable to use content_for and yield_content with Symbol

### ISSUE THREAD

**Issue by jwoertink** [kemalcr/kemal#275]
In the docs, there's a mix between using these with strings and symbols:
<img width="718" alt="screen shot 2016-12-11 at 2 10 58 pm" src="https://cloud.githubusercontent.com/assets/2391/21083731/b407c8d2-bfab-11e6-97a4-b1238e38ed70.png">

It works fine when you use them with a string key, but using a symbol key throws the error:

```
expanding macro
in src/views/site/index.ecr:3: expanding macro

<% content_for(:some_key) do %>
   ^~~~~~~~~~~

in src/views/site/index.ecr:8: no overload matches 'Hash(String, Tuple(String, Proc(String)))#[]=' with types Symbol, Tuple(String, Proc(String))
Overloads are:
 - Hash(K, V)#[]=(key : K, value : V)
```

Using this code

```crystal
# layout.ecr
<%= yield_content(:some_key) %>

# index.ecr
<% content_for(:some_key) do %>
  <chunk of="html">...</chunk>
<% end %>
```

**Comment by sdogruyol** [comment]
The docs are wrong. It only works with String 👍

**Comment by sdogruyol** [comment]
Fixed the docs via https://github.com/kemalcr/kemalcr.com/commit/ce1a7f999011ee603d7e24383235eae350d22585.
 Thanks for the report 👍

**Comment by jwoertink** [comment]
ah! Boom!

**Comment by sdogruyol** [comment]
@jwoertink Here comes the boom 🤖
