### ISSUE TITLE
Serve a static file with 206 Partial Content status

### ISSUE THREAD

**Issue by flagello** [kemalcr/kemal#276]
As far as I understand there's no built-in way to do so. Should I fork and modify `static_file_handler.cr` for this specific use-case in conformity with the status spec?

**Comment by sdogruyol** [comment]
Currently there's no built-in way to do this

**Comment by rdp** [comment]
I just ran into this myself, if you serve for instance an .mp4 from the "public" file then clients end up having to download the entire file before playing it, apparently since it doesn't advertise partial content headers...

**Comment by denysvitali** [comment]
I experience the same thing. Bummer

**Comment by denysvitali** [comment]
For anyone wondering, this is the error I receive while trying to stream something:
```
Unhandled exception in spawn:
Error writing file: Broken pipe (Errno)
0x41405e: ??? at /root/.cache/crystal/macro67609776.cr 10:28
0x4ad5ed: ??? at /opt/crystal/src/io/file_descriptor.cr 274:11
0x4ad0e7: ??? at /opt/crystal/src/io/buffered.cr 268:5
0x52561b: ??? at /opt/crystal/src/http/server/request_processor.cr 65:7
0x4167c8: ??? at /opt/crystal/src/fiber.cr 114:3
0x0: ??? at ??
```

**Comment by sdogruyol** [comment]
This is now implemented in master via #299

**Comment by rdp** [comment]
Working great, thanks everybody!

**Comment by denysvitali** [comment]
Wonderful, even though I'm pretty sure it is not fully-spec compliant (I didn't added the part of multiple ranges), it would be good if somebody can fully review it 👍
