### ISSUE TITLE
routing params

### ISSUE THREAD

**Issue by jots** [kemalcr/kemal#277]
would be nice if:
`get "/related/:word1/:word2" do |env| `

would work for both:
`http://localhost:3000/related/neat/thing`
and
`http://localhost:3000/related/?word1=neat&word2=thing`

also if variables word1 and word2 were automagically populated
so no need for:
```
 word1 = env.params.url["word1"]                                                         
 word2 = env.params.url["word2"]   
```

**Comment by jwoertink** [comment]
The first one is `env.params.url["word1"]`, the second one is `env.params.query["word1"]`. You just have to know how it's being passed. You can see more on that here http://kemalcr.com/docs/context/

**Comment by jots** [comment]
Thanks @jwoertink I was hoping that we could have 1 block that worked for both /base/:var1/:var2  and /base?var1=x&var2=y  and since the route would have :var1 and :var2 in the route itself, those variables would be populated without having to do the env.params.url["var1"].  (DRY).

**Comment by sdogruyol** [comment]
@jots the parameters are lazily parsed so that there's no performance penalty
