### ISSUE TITLE
Donations System

### ISSUE THREAD

**Issue by airinfection** [kemalcr/kemal#278]
I would like to donate some little amount of money 5 $ or smtg , but there is no way to do it.
There must be a way to do it without paypal (paypal is currently off for turkey due to banking regulations)  :S

**Comment by airinfection** [comment]
rewardsları görünce ekrana kahve püskürttüm. tebrik ederim.

**Comment by rdp** [comment]
I would donate $5/month for "at least a year" if the bonus were a "link on the sponsor page" kind of like how crystal itself does it.  Get some google juice for $5 like crystal lets you, thanks for Kemal!! :)
