### ISSUE TITLE
question

### ISSUE THREAD

**Issue by airinfection** [kemalcr/kemal#279]
**# I have a mysql query and how can i loop attributes in ecr**

db.query "select title,text,author from posts" do |rs|
rs.each do
title = rs.read(String)
text = rs.read(String)
author = rs.read(String)
end
end
render "totosh.ecr"

# **i need best way to do it**

it was like that in other languages: 

php: 
while ($rows=mysqli_fetch_array($sql)) { 
echo $rows['title'];
echo $rows['text']....
....
}

ecma:
db.query(......(rows,fields,err) { posts: rows }    

# totosh.hbs
{{#each posts}}
{{title}}
{{text}}
....
{{/posts}}

**Comment by crisward** [comment]
You need to create method that you can call from your template.
I'd also recommend creating structs for your result sets with db mapping.

eg.
```crystal
class Posts

  def getposts
    db.query "select title,text,author from posts" do |rs|
      yield Post.from_rs(rs)
    end
  end
  
  def render
     render "totosh.ecr"
  end
end

struct Post
      DB.mapping({
      title:      {type: String, nilable: true},
      text:      {type: String, nilable: true},
      author:  {type: String, nilable: true}
    })
end
```

Your ecr template.

```ecr
  <% getposts.each do |post| %>
    <h1><% post.title %></h1>
  <% end %>
```

Sorry not tested any of the above. Hope it helps.
