### ISSUE TITLE
Dynamic views with variable names

### ISSUE THREAD

**Issue by jasonl99** [kemalcr/kemal#280]
I'm working off this documentation, trying to figure out how to do views with dynamic names:

----
Using Common Paths
Since Crystal does not allow using variables in macro literals, you need to generate another helper macro to make the code easier to read and write.
```crystal
macro my_renderer(filename)
  render "my/app/view/base/path/#{{{filename}}}.ecr", "my/app/view/base/path/layouts/layout.ecr"
end
```

And now you can use your new renderer.

```crystal
get "/:name" do
  my_renderer "subview"
end
```
----
What I'd like to be able to do is this
```crystal
get "/:name" do
  some_view = "subview"
  my_renderer some_view
end
```

But I get errors involving the macro.  I'm very new to crystal, so still trying to learn.  Is there any way to do this?

**Comment by crisward** [comment]
macro's need to know at compile time what some_view is. As you're passing a variable it's not possible. The way I do this is to wrap my_render method in a series of if statements. Then use a macro to build an if statement to include all views in my view folder. That way I can store my path to view relationships in a database and it all works. The same should work for you. The example below passes a layout too, you may not want to do this. The stuff inside of back-ticks is just bash.

The below works with slang templates, but it should be easy to modify for ecr.
```crystal
def my_renderer(some_view)
  {% for view in `cd src/views/ 2>/dev/null && find . -name "*.slang" -maxdepth 1 -type f || true`.lines.map(&.strip.gsub(/^\.\//, "").gsub(/\.slang/, "")) %}
    html = render "src/views/{{ view.id }}.slang", "src/views/layout.slang" if  some_view == "{{ view.id }}"
  {% end %}
  html = render "src/views/default.slang", "src/views/layout.slang" if html.nil?
  html
end
```

**Comment by jasonl99** [comment]
Thanks Cris.  I'm playing around with something similar!

Here's what I've come up with.   I use a macro to create a Hash(String,Proc), and strips the path name to just what's under views for the key.  So the hash produced might look like this:
```crystal
{
 "default" => -{ render "/home/jason/crystal/my_app/src/views/default.slang" },
 "user" => {render "/home/jason/crystal/my_app/src/views/user.slang" }
}
```
The macro that creates the Hash dynamically looks like this:

```crystal
macro renderers
  {{ run("../utils/create_renderers.cr") }}
end
```

The create_renderers.cr that produces the actual code is here:
```crystal
output = "{"
output += Dir.glob(["src/views/**/*.slang"]).map do |f|
  "\"#{f[10..-1]}\" => -> {render \"#{File.expand_path(f)}\" } "
end.join(",") + "}"
puts output
```

When I'm ready to render, it's simply
```crystal
output = renderers.fetch("user", -> {render_plain}).call            # or some other default
```

I just couldn't figure out how to get macros working with render, but I'll definitely take a close look at your example, it seems so much simpler than mine.  I am only two weeks into learning Crystal, so I'm soaking it all in :)
