### ISSUE TITLE
Getting Started "HTTP::Handler is not a module, it's a class"

### ISSUE THREAD

**Issue by Chyzwar** [kemalcr/kemal#281]
![image](https://cloud.githubusercontent.com/assets/5990767/21549566/e92f0316-cdea-11e6-8fba-c5cae997035f.png)

I got above error when running getting started.

```cr
require "kemal"

get "/" do
  "Hello World!"
end

Kemal.run
```

**Comment by sdogruyol** [comment]
If you are using `Kemal` `master` please be sure to use Crystal `0.20.3`.

**Comment by Chyzwar** [comment]
It works now with 0.20.3. There is now way to enforce crystal version? I tried first to change crystal version in shards.yaml but no effect.

Thanks.

**Comment by sdogruyol** [comment]
You can use [crenv](https://github.com/pine/crenv) to do that but it's not standard
