### ISSUE TITLE
how to deploy behind Nginx? Or What is the standard deployment environment onto any Ubuntu server?

### ISSUE THREAD

**Issue by dashbitla** [kemalcr/kemal#282]
how to deploy behind Nginx? Or What is the standard deployment environment onto any Ubuntu server?

**Comment by sdogruyol** [comment]
You can use Nginx as a proxy for your Kemal application. You can use [capistrano-kemal](https://github.com/sdogruyol/capistrano-kemal) to deploy your application.

**Comment by dashbitla** [comment]
Any example configuration for NGinx for the complete deployment setup? Also Kemal any configurations to be done? Is this production ready? 
Also is Crystal-Kemal single threaded or multi-threaded?

Planning to use it for High concurrent GPS location tracking and processing.

**Comment by sdogruyol** [comment]
@dashbitla it's production ready. (see who uses Kemal section at http://kemalcr.com/) 
If you want you can use multiple Kemal processes behind Nginx.

A standart Nginx reverse configuration proxy like this https://gist.github.com/micho/1712812 would be enough.

**Comment by dashbitla** [comment]
When do we need to use multiple Kemal processes? 
Can it use multiple cores on the server? Say 8 Core server, can the single process make use of all the cores or should we start 8 processes or is there any logic?
How do we configure the multiple Kemal processes and how to manage them? Monit / God etc!?? OR any standard Kemal configuration like Kemal way of doing it? 

Thank you!

**Comment by sdogruyol** [comment]
@dashbitla great questions. I should definitely write a guide for these.

> Can it use multiple cores on the server? Say 8 Core server, can the single process make use of all the cores or should we start 8 processes or is there any logic?

A single processes can utilize one core, so you need to start 8 processes for 8 cores.

> How do we configure the multiple Kemal processes and how to manage them? Monit / God etc!?? OR any standard Kemal configuration like Kemal way of doing it?

You can use Monit for that, there's no Kemal way (yet).

Thanks

**Comment by dashbitla** [comment]
Thank you!

**Comment by tbrand** [comment]
For the deployment, I also have questions.
For the high performance, we usually need muiti processes execution and unix socket.
My question is

1. How to execute `Kemal.run` in multi processes?
I did it by following way, am I right?
```
[nginx.conf]
  ...
  upstream kemal-servers {
    server localhost:8080;
    server localhost:8081;
  }
  ...
  location / {
    proxy_set_header Host $host;
    proxy_pass http://kemal-servers;
  }
  ...

[bash]
bin/server -b 127.0.0.1 -p 8080
bin/server -b 127.0.0.1 -p 8081
```

2. Can we use Unix Socket?
Like: 
```
Kemal.config.host_binding = "/tmp/kemal.sock"
```

Always thankful for the help. :)

**Comment by sdogruyol** [comment]
@tbrand for now we can't use 2 but i wish we had that at Crystal std //cc @asterite 

`1` is the correct way of using multiple processes 👍
