### ISSUE TITLE
File upload: Unexpected byte 0xff in UTF-8 byte sequence from parse_multipart

### ISSUE THREAD

**Issue by srpelissier** [kemalcr/kemal#283]
Using the example found at http://kemalcr.com/docs/file_upload/ causes an error in Kemal.

If I upload an image file `curl --form "file1=@image1.jpg" http://localhost:3000/upload`, there is an unexpected character `Unexpected byte 0xff in UTF-8 byte sequence from parse_multipart`. The return code: **500**.

In comparison, if I upload a text file `curl --form "file1=@test.txt" http://localhost:3000/upload`, the first character is lost: `puts "HEADERS: #{f.headers}"` shows `"his a test"` while I was expecting `"this a test"`. The return code: **200**.

Code:
```
require 'kemal'
module Kemal1
  post "/upload" do |env|
    parse_multipart(env) do |f|
      puts "HEADERS: #{f.headers}"
    end
  end
  Kemal.run
end
```

**Comment by samueleaton** [comment]
It [looks like](https://github.com/kemalcr/kemal/blob/b4c10a3f59392080f54a206ad40f779628cdad96/src/kemal/helpers/helpers.cr#L100) that its just using [multipart.cr](https://github.com/RX14/multipart.cr). So you may want to create an issue there. However, there should be some specs here.

**Comment by crisward** [comment]
I've got a fork of kemal with this updated. It's only temp while testing this fix. I'm sure kemal will have a new release soon.

perhaps use `crisward/kemal` while you're waiting...?

**Comment by srpelissier** [comment]
thank you, it's working now
