### ISSUE TITLE
Parsing array query

### ISSUE THREAD

**Issue by tbrand** [kemalcr/kemal#284]
I don't know how to parse array query from env.
`pp` says
```
# For debug
pp env.params.body

# => env.params.body # => HTTP::Params(
                      @raw_params=
                       {"uid[]" => ["3", "2"], # <= HERE!!
                        "submit" => ["submit"]})
```
I thought I could get the array like
```
env.params.body["uid[]"][1] # => should be 2?
```
But this throws `Index out of Bounds Exception`.

Thanks.

**Comment by tbrand** [comment]
Oh sorry, this is not a Kemal issue but Crystal itself.
I've solved this by myself.

I should use [this](https://github.com/crystal-lang/crystal/blob/7a0676b77548d3a99c0942007cc10cdd2a9f8530/src/http/params.cr#L157) instead of [this](https://github.com/crystal-lang/crystal/blob/7a0676b77548d3a99c0942007cc10cdd2a9f8530/src/http/params.cr#L121)

```
env.params.body["uid[]"] # NG
env.params.body.fetch_all("uid[]") # OK
```

**Comment by sdogruyol** [comment]
👍
