### ISSUE TITLE
allow custom ip address binding

### ISSUE THREAD

**Issue by zolamk** [kemalcr/kemal#286]
right now we are only allowed to configure the `port` kemal runs on,

    require "kemal"

    get "/" do
        "Hello World"
    end

    Kemal.run 8080

it should allow custom IP address binding like this

    require "kemal"

    get "/" do
        "Hello World"
    end

    Kemal.run "127.0.0.3", 8080

**Comment by sdogruyol** [comment]
Hey @zolamk thanks for the PR. 

You can already change your `host_binding` like below

```
Kemal.config.host_binding = "127.0.0.3"
```

and i don't think we need that in `run`.
