### ISSUE TITLE
files under /public when writing a shard

### ISSUE THREAD

**Issue by jasonl99** [kemalcr/kemal#288]
I'm working on a project that creates a shard using kemal.  There are a few static javascript files that I'd like to serve from the public directory, but I want to app that uses the shard to be able to override those files.  

For example, suppose my shard project is called `my_shard`.   In that project, I have a `/public` directory which contains `js/example.js`.  In a normal kemal project, this gets served just fine from the public directory.

But suppose I create a new app named `my_app` and have `my_shard` in shard.yml.  My new app has no `/public` directory, but there is a 'lib/my_shard/public/js/example.js` that was installed via `shards install~ which obviously won't be seen as a public directory by `my_app`. 

I think this is getting into the area where it becomes necessary to create builder of sorts, copying default files and creating the `public/` directory if necessary.    The ideal way to handle this in my mind would be to have kemal search the public directory of the app firs, then public directories in `lib/*/public` until it finds `js/example.js`.  

By the way, I can't say enough good things about how phenomenal crystal language and kemal both are!

**Comment by sdogruyol** [comment]
Hey @jasonl99 thanks a lot 👍 

How about using a virtual file system for your case? For example [sidekiq.cr](https://github.com/mperham/sidekiq.cr) uses a virtual filesystem to avoid all these problems.

You can check https://github.com/schovi/baked_file_system for more info

**Comment by jasonl99** [comment]
Thank you, this is a great way to handle it.  Here's what I ended up doing:

I've added a class for storage as per baked-file-system that contains the entire public directory of my shard;
```crystal
class PublicStorage
  BakedFileSystem.load("../public", __DIR__)
end
```

There's two new routes:
```crystal
  get "/css/:file" do |context|
    context.response.content_type = "text/css"
    PublicStorage.get("/css/#{context.params.url["file"]}").read
  end

  get "/js/:file" do |context|
    context.response.content_type = "text/javascript"
    PublicStorage.get("/js/#{context.params.url["file"]}").read
  end
```
If there's a file in the public/js or public/css directories of the app, those are served.  Otherwise, the shard's public/js and public/css files are used.

**Comment by sdogruyol** [comment]
@jasonl99 that's great to hear 👍
