### ISSUE TITLE
Integration with bootstrap?

### ISSUE THREAD

**Issue by igpg** [kemalcr/kemal#289]
Would be really great to integrate it with [http://getbootstrap.com/](url) or some other front-end framework.
What do you think?

**Comment by samueleaton** [comment]
IMO *if* kemal provided some kind of client code bundler (e.g. webpack) where you could specify a css preprocessor, css framework, js libraries, etc it would be in a separate repo within the [kemalcr](https://github.com/kemalcr) org and not in the kemal project itself.  

But then again, most people use NPM anyway for that kind of stuff. Even in Elixir/Phoenix they use Node.js for all of the client stuff building, which seems too heavy for Kemal. Kemal's simplicity is a key reason for its popularity.
