### ISSUE TITLE
How to tie a WebSocket to a session?

### ISSUE THREAD

**Issue by jasonl99** [kemalcr/kemal#295]
I monkey-patched HTTP::Reques to see how this all comes together (no, don't worry, I wouldn't do this for a production system!)

```crystal
class HTTP::Request
  def initialize(@method : String, @resource : String, headers : Headers? = nil, body : String | Bytes | IO | Nil = nil, @version = "HTTP/1.1")
    @headers = headers.try(&.dup) || Headers.new
    self.body = body
    puts self.inspect 
    puts "-"*40
  end 
end
```

Now let's say I have the following:

```crystal
require "kemal"
require "kemal-session"

module MyApp
  get "/something" do |context|
    context.session.string("foo","bar") # set a session string "foo" to "bar"
    #... some rendered page that has javascript code to to do a new WebSocket("/create_socket") on the browser
  end
  ws "/create_socket" do |socket|
    # ?? How do I tie this socket to the previous connection?
  end
end 
```

When I load `localhost:3000/something` my monkey-patch shows two HTTP::Requests, one for the page, and one for the socket connection:

```crystal
#<HTTP::Request:0x560298e84c80
  @method="GET",
  # other stuff 
  @resource="/something">
----------------------------------------
#<HTTP::Request:0x560298e84b00 @method="GET", @headers=HTTP::Headers{"Host" => "localhost:3000", 
  "Connection" => "Upgrade", 
  "Pragma" => "no-cache", 
  "Cache-Control" => "no-cache", 
  "Upgrade" => "websocket", 
  "Origin" => "http://localhost:3000", "Sec-WebSocket-Version" => "13", 
  "User-Agent" => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36", 
  "Accept-Encoding" => "gzip, deflate, sdch, br", 
  "Accept-Language" => "en-US,en;q=0.8,is;q=0.6", "Cookie" => 
  "kemal_sessid=39cac87ea647ded52fe144a4041aee92--876d9de79d3f8d678212984ceca0ec76d81d41fc", 
  "Sec-WebSocket-Key" => "VXkujB1hzDaUTxMMJhkAog==", 
  "Sec-WebSocket-Extensions" => "permessage-deflate; client_max_window_bits"}, 
  @body=nil, 
  @version="HTTP/1.1", 
  @cookies=nil, 
  @query_params=nil, 
  @uri=nil, 
  @url_params=nil, 
  @param_parser=nil, 
  @override_method=nil, 
  @resource="/create_socket">
```
So the kemal_sessid is actually available upon socket creation (/create_socket), but it's nowhere to be found in `#ws "/create_socket"`.

Is there a way to accomplish this?  It would be __awesome__ to be able to tie a socket to a session.

**Comment by f** [comment]
Technically they are different contexts. You should connect them explicitly just like ActionCable does: https://rubytutorial.io/actioncable-devise-authentication/

**Comment by crisward** [comment]
This works

```
ws "/" do |socket, ctx|
  session = Session.new(ctx)
end
```

They get the same cookies, so the same session can be referenced.

**Comment by jasonl99** [comment]
@crisward, thank you, I will try that.  @f, that's pretty much what I was doing for now, sending the session_id from the server back over the connection when it was opened.  But this eliminates the need to get the session cookie via javascript.

**Comment by crisward** [comment]
I stumbled across this when reading the source, so it's not documented as far as  I know. The mechanism isn't perfect because your session expires, but the socket only gets it once per connection. So ideally you should reload your session on each message received to make sure it's still valid.

**Comment by jasonl99** [comment]
To expand on this a little, take this code

```crystal
ws "/" do |socket, ctx|
  session_id = Session.new(ctx).id
  socket.on_message do |message|
     Foo.handle_message(message,session)
  end
end

class Foo
  def handle_message(message, session_id)
    puts "Socket message received for #{session_id}"
    if (session = Session.get session_id)
        # do something with the session
    end
  end
end
```
The only thing missing, as you said, is a way to prevent the session from timing out.  How about adding a `#touch` method to [Session](https://github.com/kemalcr/kemal-session)?   Then you could do this:

```crystal
ws "/" do |socket, ctx|
  session_id = Session.new(ctx)
  socket.on_message do |message|
     Session.touch(session_id)
     Foo.handle_message(message,session_id)
  end
end
```

**Comment by crisward** [comment]
I think the memory sessions already update their timer when data is accessed.
ie - https://github.com/kemalcr/kemal-session/blob/master/src/kemal-session/engines/memory.cr#L20
 
The file session doesn't, I raised an issue for that (https://github.com/kemalcr/kemal-session/issues/27). 

Reading the session on each message should be enough therefore to keep it alive. The session timeout is an hour by default so these keep-a-lives should be enough.

**Comment by jasonl99** [comment]
Yes, but my suggested code only only passes the session_id, not the entire session inside `socket.on_message`.    So once the socket is established, it's just passing around `String`s `Foo#handle_message` This avoids instantiating a Session until you need it (since `Session.touch` is a class proc).

That said, you probably almost always want the real session anyway.  So you could instead pass an instantiated session to `foo.handle_message`:

```crystal
ws "/" do |socket, ctx|
  session = Session.new(ctx)
  socket.on_message do |message|
     Foo.handle_message(message,session)
  end
  socket.on_close do
    # perhaps run session.destroy? 
  end
end

class Foo
  def handle_message(message : String, session: Session)
    puts "Socket message received for #{session.id}"
    puts "Socket user's name is #{session.string?("name") || "unknown"}"
    # do something with the session
  end
end
```

The difference between the two, I think, is that the Session instance stays instantiated (consuming server memory) while the socket is open since it's withinin the closure (again, probably what you want).  What I am not sure about is if/when the closure goes away.

**Comment by crisward** [comment]
The GC is supposed to remove it when it's dereferenced. But I think it may only do this under memory pressure. Classes have a `finalize` method, the opposite to`initialize`, which gets called before the GC kills your class instance. I've played with this and struggled to get it to fire.

@sdogruyol has done some benchmarking with sockets. Perhaps ask on gitter to see what he used. You can then at least see what memory impact your options have.
