### ISSUE TITLE
Easy way to customize static handling?

### ISSUE THREAD

**Issue by 0xFireball** [kemalcr/kemal#297]
I would like to map all routes in `/a` to a folder `client/dist/` (these are static files).

How can I do this with Kemal?
If this isn't possible, what should I modify to make this possible?

Thanks.

**Comment by denysvitali** [comment]
The only way I know is
`public_folder "client/dist"`, but this will map `/` instead of `/a`

**Comment by 0xFireball** [comment]
thanks!

**Comment by denysvitali** [comment]
It would be nice if someone from the kemal team ( @sdogruyol maybe? ) can confirm that there isn't a way / or show us how to do it (haven't found anything in the docs, unfortunately)
