### ISSUE TITLE
Testing websockets?

### ISSUE THREAD

**Issue by adamtrilling** [kemalcr/kemal#301]
How does one write integration tests for websockets? 

I'm working on an app where I'd like to accept websocket connections from non-browser clients, and it seems like the simplest way to build that is to write a mock client in a test and make assertions against the responses it gets from the server.

The problems are twofold:

1) The server doesn't bind to a port in the TEST environment
2) If you force it to do so, it blocks the entire process, so the test doesn't continue.

Any ideas how to get around this? I suppose I could run the test and the server in two separate shells, but that won't work in CI.

**Comment by sdogruyol** [comment]
Moving this issue to [spec-kemal](https://github.com/kemalcr/spec-kemal).
