### ISSUE TITLE
Splitting router across multiple files

### ISSUE THREAD

**Issue by lpil** [kemalcr/kemal#303]
Hello!

As apps get larger it's nice not to keep all routes in one file. For example, I'd may want to keep my authentication routes in one file, and my resource X CRUD routes in another.

With Sinatra I can achieve this by writing apps in the [modular style](http://www.sinatrarb.com/intro.html#Sinatra::Base%20-%20Middleware,%20Libraries,%20and%20Modular%20Apps) and then composing them with Rack::URLMap.

Is there a similar mechanism for Kemal?

Thank you.

**Comment by jasonl99** [comment]
I believe that you can add routes at any time (and anywhere in your code) before Kemal.run is called.   

In a project that has kemal installed as a shard, you can actually run `crystal play` and run this code

```crystal
require "kemal"

get "/test" do |context|
  "Hello TEST"
end

Kemal.run

get "/test2" do |context|
  "TEST2"
end
```

You can then open a different tab, go to `localhost:3000/test` (works as expected) and `localhost:3000/test2` where you get a "kemal doesn't know this way"

But the point is, until `Kemal.run` is called, you can put routes wherever you want in your code.

**Comment by lpil** [comment]
Interesting. Thank you.

**Comment by sdogruyol** [comment]
@jasonl99 that's correct 👍 

@lpil you can define routes in anywhere until you call `Kemal.run`.
