### ISSUE TITLE
Store objects other than primitive values in Context Storage

### ISSUE THREAD

**Issue by joaodiogocosta** [kemalcr/kemal#307]
Given [this](https://github.com/kemalcr/kemal/blob/cc44710654e90542ca379404ce1c4173c01c34e4/src/kemal/context.cr#L7), how do you recommend to share state such as a custom object between middlewares and filters?

```crystal
alias StoreTypes = Nil | String | Int32 | Int64 | Float64 | Bool
```

**Comment by sdogruyol** [comment]
I'd recommend using https://github.com/kemalcr/kemal-session and `StorableObject`

```crystal
class UserStorableObject
  JSON.mapping({
    id: Int32,
    name: String
  })
  include Session::StorableObject

  def initialize(@id : Int32, @name : String); end
end
```

In your routes

```crystal
require "kemal"
require "kemal-session"

get "/set" do |env|
  user = UserStorableObject.new(123, "charlie")
  env.session.object("user", user)
end

get "/get" do |env|
  user = env.session.object("user").as(UserStorableObject)
  "The user stored in session is #{user.name}"
end
```

**Comment by joaodiogocosta** [comment]
I see, thanks, serialize to JSON was actually my first thought and it's cool that kemal has a way to handle it already.

 Do you think there's a better way to do it? I mean, instead of serialize to JSON (which is cool 'cause it's simple), serialize to some other format to make it more performant?

Or even a struct-like object that you can serialize to/from and support that type in `storeTypes`. We can have a macro to do the default serialization and make it stupid simple to use:

```crystal
macro storable_object
    {{ CustomStorableObject.new(_serialize_all_instance_vars_here_) }}
end
```

In your object:
```
class User
  storable_object
   ...
```

Or if you want custom serialization:
```
class User
  @name : String

  def to_custom_storable_object
    CustomStorableObject.new({ name: @name })
  end
end
```

What do you think? Does this make sense?

**Comment by sdogruyol** [comment]
I have think about this. 

Meanwhile we can ask @neovintage since he's more knowledgable than me in serialization 👍

**Comment by joaodiogocosta** [comment]
I discussed this with some folks and other ideas came up such as using generics (would be this implementation of a [radix tree](https://github.com/luislavena/radix) with generic payloads) or store objects the most abstract structure possible and then define methods (using macros) to access objects. Something like:

```
def add_to_store(obj_name, obj : Object)
  store[obj_name] = obj
end

# and then a macro to generate accessor methods
macro add_to_store(obj_name, obj)
  store[obj_name] = obj

  def {{ obj_name.id }}
    store[obj_name].as(obj.class)
  end
end
```

store = {} of String => Object
user = User.new
add_to_store(:user, user)
store.user # => <User ...>

**Comment by sdogruyol** [comment]
@joaodiogocosta actually i'm waiting on Crystal to have the ability to use `Object` as generics such as

```crystal
generic_hash = {} of Object
```

thus we can use this to store anything 👍

**Comment by joaodiogocosta** [comment]
Hm, didn't you can't do it in Crystal :/

**Comment by sdogruyol** [comment]
You can't do this as of now in Crystal but it'll be possible before 1.0 👍

**Comment by joaodiogocosta** [comment]
Cool. I think you can close this issue then 👍

**Comment by sdogruyol** [comment]
Thanks

**Comment by joaodiogocosta** [comment]
That macro thingy, if it works, would be useful though and can be implemented right away. You wouldn't have to call `session.object("user").as(UserStorableObject)`, just `session.user` 'cause the macro can do it for you. I would be happy to contribute if you think it makes sense.

**Comment by sdogruyol** [comment]
@joaodiogocosta that should be a seperate issue in https://github.com/kemalcr/kemal-session
