### ISSUE TITLE
files are "saved" locally even when absent

### ISSUE THREAD

**Issue by rdp** [kemalcr/kemal#309]
If I have a form with a file input field, even if I don't actually use it to upload a file, the following multipart is sent with the request:

```
  -----------------------------1679966275781931692080083066
  Content-Disposition: form-data; name="srt_upload"; filename=""
  Content-Type: application/octet-stream
  
```

kemal loads it as a zero length FileUpload:

```
puts env.params.files

files={"srt_upload" => FileUpload(@tmpfile=#<IO::FileDescriptor: fd=11>, @tmpfile_path="/var/folders/_s/c0kwjqxn2txglx5kdpcvmj0jb5h2bk/T/.KWGnP4", @filename="", @meta=HTTP::FormData::FileMetadata(@filename="", @creation_time=nil, @modification_time=nil, @read_time=nil, @size=nil), @headers=HTTP::Headers{"Content-Disposition" => "form-data; name=\"srt_upload\"; filename=\"\"", "Content-Type" => "application/octet-stream"})}
```

(that is an empty file)

My hunch is that kemal probably shouldn't create a temp file for it.

My work around is to check  is the FileUpload's name's size is > 0.

Cheers!

**Comment by sdogruyol** [comment]
@rdp thanks for the issue. This is definitely an improvement over current implementation 👍

**Comment by rdp** [comment]
Yeah they probably shouldn't even show up in  env.params.files :|
Also files["filename"].filename can be nil [hmm a bit odd].
Thanks!

**Comment by rdp** [comment]
Awesome [I presume it still lets "empty" files be uploaded, just not "non" files as it were ?)

**Comment by crisward** [comment]
This update can break file uploads at least in crystal 0.21.0. Confirmed in discussion on gitter.
Should be able to recreate with below example.

```
require "./upload/*"
require "kemal"

module Upload
  get "/" do |ctx|
    %{<html><body>
          <form method="post" action="/upload" enctype="multipart/form-data">
            <input type="file" name="file" >
           <button type="submit">Upload</button>
         </form></body></html>
  }
  end
  post "/upload" do |ctx|
    p ctx.params.files
    ctx.params.files.each do |key, file|
      tmpfile = file.tmpfile
      filename = file.filename
      if !filename.is_a?(String)
        p "No filename included in upload"
      else
        file_path = File.join(Kemal.config.public_folder, "uploads/", filename)
        p "copied from", tmpfile.path, file_path
        File.rename(tmpfile.path, file_path)
      end
    end
    "Uploaded"
  end
end

Kemal.run
```

**Comment by sdogruyol** [comment]
@crisward how about `0.21.1`?

**Comment by crisward** [comment]
Same. Just checked.

**Comment by sdogruyol** [comment]
Not sure why this breaks the file upload. Any ideas @Sija ?

**Comment by crisward** [comment]
the upload object, even with a uploading file outputs something like this with `p upload` added.

```
(removed the byte array)
@sync_close=false>,
 @creation_time=nil,
 @filename="Upton.csv",
 @headers=
  HTTP::Headers{"Content-Disposition" =>
    "form-data; name=\"file\"; filename=\"Upton.csv\"",
   "Content-Type" => "text/csv"},
 @modification_time=nil,
 @name="file",
 @read_time=nil,
 @size=nil)
```
So size can = nil for a valid upload.

**Comment by sdogruyol** [comment]
@crisward i'll dive into that

**Comment by crisward** [comment]
If it helps, I was checking if the file has a filename in my code. Perhaps you could move that into kemal. Don't think it's possible to upload without a filename? Not sure where the spec for multipart uploads lives.

**Comment by sdogruyol** [comment]
@crisward can you create another issue for that please

**Comment by Sija** [comment]
@crisward @sdogruyol sorry for the mess! should I make another PR with `filename.is_a?(String) && !filename.empty?` fix?

**Comment by crisward** [comment]
Apparently filename doesn't have to be supplied either according to the spec.

**Comment by crisward** [comment]
from gitter
>Chris Hobbs @RX14 Mar 18 23:37
@crisward if the file is empty, the first read(slice) will return 0. That's the only reliable way to tell.

**Comment by Sija** [comment]
@crisward that would be a performance penalty from default :/

**Comment by RX14** [comment]
There's no performance penalty because the whole data in the multipart "part" has to be read anyway. If you don't read `part.io` fully it'll just be read [here](https://github.com/crystal-lang/crystal/blob/master/src/http/multipart/parser.cr#L66). Even if that wasn't the case, it'd be a tiny performance penalty of at most a single syscall.

**Comment by rdp** [comment]
But it's also possible to upload "empty files" so I guess if there is no
data *and* no filename then it's a non upload? :)
