### ISSUE TITLE
Support for streaming responses

### ISSUE THREAD

**Issue by f** [kemalcr/kemal#315]
I think Kemal needs an equivalent behavior of `Sinatra::Streaming`.

This is how Sinatra streaming works like
```rb
get "/events" do
  stream do |buffer|
    redis.psubscribe("message.*") do |on|
      on.pmessage do |subscription, event, data|
        buffer << "data: #{data}\n\n"
      end
    end
  end
end
```

It streams this endpoint without closing the request (persistent). As you can see, I'm writing into `buffer` asynchronously. The request will never end, but browser won't wait to get all the data (browser's standart behavior) but when it's streaming, it will receive and show whatever it takes in time.

Since this is mostly used by `EventSource`, it may only have `GET` request and make it simpler for Kemal:

This is a psuedo code which a streaming endpoint may behave.
```rb
stream "/events" do |buffer, env|
  redis.psubscribe("message.*") do |on|
    on.pmessage do |subscription, event, data|
      buffer << "data: #{data}\n\n"
    end
  end
end
```

It doesn't seem like a big deal but I think it needs to support.

https://www.w3.org/TR/2009/WD-eventsource-20091029/
https://www.html5rocks.com/en/tutorials/eventsource/basics/
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by sdogruyol** [comment]
@f please take a look at https://github.com/kemalcr/kemal/issues/151 and let me know WDYT

**Comment by flagello** [comment]
Isn't the proposed solution (https://github.com/kemalcr/kemal/issues/151#issuecomment-230175181) too verbose/unintuitive? I understand @asterite reasoning, but `stream` seems much more immediate and in line with `get` and `ws`.

**Comment by f** [comment]
@flagello Yes it's too unintuitive. I spend a night to make it done and I couldn't do it. Also, (for `EventSource` case which streams used by in common),

```rb
post "/" do
  stream do
  end
end
```

this doesn't make sense.
