### ISSUE TITLE
`before_all` is not setting variable for rendering

### ISSUE THREAD

**Issue by oltmannsdaniel** [kemalcr/kemal#317]
If I call `before_all` to set a variable for my Flash Message I couldn't use it in my `.ecr` view.

Maybe someone know how to solve this. Or had a better example for flash messages.

**Comment by sdogruyol** [comment]
@oltmannsdaniel you need to set your variable in your route scope instead of `before_all`. 

```crystal
before_all "/" do |env|
   env.set "is_kemal_cool", true
end

get "/" do
  is_kemal_cool = env.get "is_kemal_cool" # => true
end

**Comment by oltmannsdaniel** [comment]
Ok, thank you. Do you have an idea how to protect routes.

So check if the User is authenticated without writing `before_get "/"` for every protected route?

**Comment by sdogruyol** [comment]
[Middleware](http://kemalcr.com/docs/middlewares/) is better suited for this case.

```crystal
class UserAuthHandler < Kemal::Handler
  def call(context)
    puts "Doing some custom stuff here"
    if user
      call_next context
    else
      return "User not found"
   end
  end
end

add_handler UserAuthHandler.new
```

**Comment by oltmannsdaniel** [comment]
I mean protecting only a specific amount of routes @sdogruyol

**Comment by sdogruyol** [comment]
@oltmannsdaniel a middleware with `only` or `exclude`. This sample only runs on routes `["/", "/users", "/posts"]` with `"POST"` method.

```crystal
class UserAuthHandler < Kemal::Handler
  only ["/", "/users", "/posts"], "POST"

  def call(context)
    return call_next(env) unless only_match?(env) # No match
    puts "If the path is / i will be doing some processing here."
  end
end

add_handler UserAuthHandler.new
```

**Comment by oltmannsdaniel** [comment]
Ok. Thank you very much for your support.
