### ISSUE TITLE
how can i get client ip?

### ISSUE THREAD

**Issue by lgphp** [kemalcr/kemal#319]
$_SERVER["REMOTE_ADDR"] in php,but crystal?

**Comment by sdogruyol** [comment]
@lgphp for now this is still an open issue in Crystal https://github.com/crystal-lang/crystal/pull/1722

**Comment by crisward** [comment]
If you're behind an nginx proxy you should be able to use

```crystal
get "/" do |ctx|
  ipaddress = ctx.request.headers["X-Forwarded-For"]?
end
```

**Comment by rdp** [comment]
Here's how rails 2.3 gets its output like

`Processing Controller#action (for 207.46.13.90 at 2017-03-10 16:29:08) [GET]`

https://gist.github.com/rdp/ec8d8d7152988f496f951a2f0d65a320

I've thought before it might be nice for kemal's output to be something like

`2017-03-10 14:26:45 -0700 for 207.46.13.90 200 GET / 144.78ms`

FWIW :)

**Comment by crisward** [comment]
I think this could be closed as this probably going to be inherited on context when crystal decides to add it - https://github.com/crystal-lang/crystal/issues/453

Though I suppose we could patch crystal in the meantime with a solution?

**Comment by sdogruyol** [comment]
@crisward I'm curious to see how Crystal itself will implement this (eventually) :+1: Closing for now
