### ISSUE TITLE
Missing key error in params

### ISSUE THREAD

**Issue by jwoertink** [kemalcr/kemal#326]
When posting an array, I'm having issues accessing the key.

```crystal
require "kemal"

post "/test" do |env|
  env.params.body["sld"]   # this returns "kemal"
  env.params.body["tlds"]  # this returns a giant stacktrace
end
```

`curl -XPOST http://localhost:3000/test -d "sld=kemal&tlds[]=com&tlds[]=net&tlds[]=io"`

I get this error:

```
Exception: Missing hash key: "tlds" (KeyError)
```

**Comment by sdogruyol** [comment]
Kemal uses `HTTP::Params.parse` which is built into Crystal. It looks like it doesn't handle `Array`s 😢

**Comment by sdogruyol** [comment]
LOL, this works however it only fetches the first element

```crystal
env.params.body["tlds[]"] # Beware of []
```

However i find this strange and would expect to be able to access it via just `"tlds"`

**Comment by sdogruyol** [comment]
https://github.com/crystal-lang/crystal/issues/4128

**Comment by sdogruyol** [comment]
@jwoertink the correct way of accessing an array param is 


```crystal
env.params.body.fetch_all("tlds[]") # => ["com", "net", "io"]
```

**Comment by jwoertink** [comment]
Ah. weird. Thanks for looking in to that! I find it strange that there's no standard for how those are supposed to be parsed considering checkboxes and multi selects are a common thing.

Maybe it's just me, but this feels inconsistent:
```crystal
env.params.body["name"]
env.params.body["age"]
env.params.body.fetch_all("hobbies[]")
```

Now the question is, how is a hash handled? i.e.

`user[name]=jeremy&user[age]=35&user[hobbies][]=crystal` 

You can't do `body["user"]`, and doing `fetch_all("user[]")` is empty. You would have to do `fetch_all("user[name]").first`. I guess it's time for a new shard to sort of clean these up. 

I guess we can close out this issue since it's not really a bug, but would you be ok with me sending a PR to add a new page to the website guide? I'm thinking a page on using params, or maybe just extending the context page.

**Comment by sdogruyol** [comment]
@jwoertink that'd be great 👍 

I'm also thinking of standardizing the interface and will work on that. I like to keep Kemal as simple as possible thus 

```
env.params.body["hobbies"]
```

should work

**Comment by jwoertink** [comment]
Sweet. Ok, until that change is done, then I'll just send over a PR for docs on how it should be handled for now. Thanks!
