### ISSUE TITLE
POST request with Array on body

### ISSUE THREAD

**Issue by oltmannsdaniel** [kemalcr/kemal#337]
My HTML code:
```HTML
<form action="/" method="post">
    <input type="text" name="options[]">
    <input type="text" name="options[]">
</form>
```

What I expect: That the `env.params.body["options[]"]` is an Array **not a String**, or at least a JSON object.

@sdogruyol The Parameter Parser need some changes.

**Comment by sdogruyol** [comment]
Please use Kemal master for this

19 Mar 2017 14:16 tarihinde "Daniel Oltmanns" <notifications@github.com>
yazdı:
