### ISSUE TITLE
Kemal Handler: Dynamic route issue

### ISSUE THREAD

**Issue by oltmannsdaniel** [kemalcr/kemal#346]
My Code:
```crystal
class MiddlewareHandler < Kemal::Handler
  only ["/", "/:name"], "GET"

  def call(env)
    return call_next(env) unless only_match?(env)

    puts "No match"

    call_next env
  end
end

add_handler MiddlewareHandler.new
```

The `/:name` Route wouldn't be recognized by the Handler. @sdogruyol

**Comment by sdogruyol** [comment]
This actually works as intended when you go to `/asd` printing out "No Match"

```crystal
class MiddlewareHandler < Kemal::Handler
  only ["/", "/:name"], "GET"

  def call(env)
    return call_next(env) unless only_match?(env)

    puts "No match"

    call_next env
  end
end

add_handler MiddlewareHandler.new

get "/" do |env|
  "index"
end

get "/:name" do
  "name"
end
```

What's your Kemal version @oltmannsdaniel ?

**Comment by oltmannsdaniel** [comment]
@sdogruyol Uups. Had an old one. Definitely need to go deeper into it.

**Comment by oltmannsdaniel** [comment]
@sdogruyol But one more question: **How can I sepeterate API Routes from my main stuff?**. Because I definitely do not need a session or CSRF token on those requests!?

Do you have there any good solution?

**Comment by sdogruyol** [comment]
Sorry, i don't get your question. What do you mean by 'seperating from main stuff`?

**Comment by oltmannsdaniel** [comment]
Well, there are the normal routes like / or /welcome or /signin.But I also want to add /api/v1/authentication or /api/v1/users. On those Routes I do not need to generate a Session or a CSRF token, because I won't use it.Am 31.03.2017 15:11 schrieb Serdar Dogruyol <notifications@github.com>:Sorry, i don't get your question. What do you mean by 'seperating from main stuff`?

**Comment by sdogruyol** [comment]
@oltmannsdaniel well those won't be created unless you're creating.

**Comment by samueleaton** [comment]
@oltmannsdaniel You want middlewares to be excluded from your API routes? Like this?

```ruby
require "kemal"


class Authenticator < Kemal::Handler
  # Will not run for any api GET requests
  exclude ["/api/**"]

  def call(env)
    return call_next(env) if exclude_match?(env)

    puts "authenticating..."
    call_next(env)
  end
end

add_handler Authenticator.new

get "/" do
  "Hello World!"
end

get "/api/v1/hello" do |env|
  env.response.content_type = "application/json"
  "{\"msg\":\"Hello World!\"}"
end


Kemal.run
```

**Comment by oltmannsdaniel** [comment]
@samuelaton When the "/api/**" stuff works, is that exactly what I need
