### ISSUE TITLE
WebSocket handler can't take URL parameter.

### ISSUE THREAD

**Issue by ne-sachirou** [kemalcr/kemal#349]
WebSocket handler can't take URL parameter.

```crystal
# This works for /cable/1
ws "/cable/1" do |socket, env|
end
```

```crystal
# This dosen't work for /cable/1, only matches for /cable/:id
ws "/cable/:id" do |socket, env|
end
```

Is there any reason that `ws` can't take URL parameter?

**Comment by sdogruyol** [comment]
@ne-sachirou routing doesn't work on `ws`. You can use query params like `cable?id=5`

**Comment by Sija** [comment]
@sdogruyol why not? is there any argument **against** it?

**Comment by jmrepetti** [comment]
Regarding this topic, I also wanted to use different routes for different sockets. I read here(http://kemalcr.com/guide/#websockets) that is possible, but looks like the last 'ws' route definition is called no matter which route I use to connect. I'm using kemal@master.

**Comment by sdogruyol** [comment]
@jmrepetti can you share a code snippet?

**Comment by jmrepetti** [comment]
Sure!

Kemal script:

```crystal
require "kemal"

ws "/room_socket" do |socket|
  socket.send "room_socket"
end

ws "/player_socket" do |socket|
  socket.send "player_socket"
end

Kemal.run
```
The html with the socket connection, is a static file served from public/index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Title</title>


    <script>
      var playerSocket = new WebSocket("ws://0.0.0.0:3000/player_socket");

      playerSocket.onmessage = function (event) {
        console.log(event.data);
      }

      var roomSocket = new WebSocket("ws://0.0.0.0:3000/room_socket");

      roomSocket.onmessage = function (event) {
        console.log(event.data);
      }
    </script>

  </head>
  <body>
  </body>
</html>
```

When I access Chrome console log prints:

```javascript
player_socket
player_socket
```

I expect to see the messages from the different sockets.

If I change the order of the routes:

```crystal
require "kemal"

ws "/player_socket" do |socket|
  socket.send "player_socket"
end

ws "/room_socket" do |socket|
  socket.send "room_socket"
end

Kemal.run
```

Then Chrome console prints:

```
room_socket
room_socket
```

From the root project folder I run:

```
$ crystal run src/example.cr 
```

I'm using:

OSX 10.12.6 and Crystal 0.23.1 (2017-07-13) LLVM 4.0.1

**Comment by sdogruyol** [comment]
@jmrepetti could you please open a new issue with this snipper :pray:

**Comment by jmrepetti** [comment]
Sure, I'll do.
