### ISSUE TITLE
Enhancement: HTTP parameters as Hash-like object with keyer_cr

### ISSUE THREAD

**Issue by danielpclark** [kemalcr/kemal#350]
Until today I don't believe there was a Crystal library written to do this.  To parse multiple form data fields as a Hash-like object rather than one long String.

```crystal
Kemal::ParamParser.new(env.request).query
```

The above returns a String of parameters.  I have written [keyer_cr](https://github.com/danielpclark/keyer_cr) to handle multiple parameters and any depth.  This acts as a nested Hash that you may retrieve data from.

```crystal
v = Keyer::Parser.new("a=7&asdf[qwer]=1234&cat=meow")
v["asdf"]["qwer"]
# => "1234"
v["a"]
# => "7"
v["cat"]
# => "meow"
```

I feel this is a sorely needed feature and I was wondering if it is within the scope of this project to include it?  If so I was curious how the method for it would be added in?  Changing the above `query` method would be breaking behavior so I'm guessing a new method then?

**Comment by sdogruyol** [comment]
Hey @danielpclark, thanks for the issue.

Kemal already builds a hash from query params by `env.params.query`, i'm not sure what's the use case for your suggestion.

**Comment by danielpclark** [comment]
Is this documented anywhere?  Going through docs, api, and source code I have not seen `env.params.query` mentioned.  It's why I wrote the tool.

**Comment by danielpclark** [comment]
Oh my.  I see what I've done.  I was rendering the result of `Kemal::ParamParser.new(env.request).query` directly to the view to see it.  It shows the result like `a=7&asdf[qwer]=1234&cat=meow` and therefore I thought it was a String.  But now displaying it with:

```crystal
x = Kemal::ParamParser.new(env.request).query
{x, typeof(x)}
```
I see I am getting a hash-like object: `{HTTP::Params(@raw_params={"a" => ["7"], "asdf[qwer]" => ["1234"], "cat" => ["meow"]}), HTTP::Params}`

Which just goes to show I was mistaken.  It looks like `HTTP::Params.display` method is a string representation which led to my confusion.

**Comment by sdogruyol** [comment]
@danielpclark may i ask what's your use case for this?

**Comment by danielpclark** [comment]
There is none.  It's already implemented in `HTTP::Params` .  The guides, APIs, and code didn't indicated to me this feature existed so I invested the time to make it.

I guess my only recommendation is to update the docs and guides so people can know they have a hash-like params feature.
