### ISSUE TITLE
Gems and hosting

### ISSUE THREAD

**Issue by arjunmenon** [kemalcr/kemal#351]
Coming from Ruby, does Kemal allows the app to interface with certain Ruby gems? That would be helpful in plugging functionality straight up and work with the gems output directly.

Apart from Heroku, are there any others which provide Crystal hosting, as a feature?

**Comment by sdogruyol** [comment]
Hey @arjunmenon 

- Kemal is written in Crystal and it does not have a way of interfactng with Ruby gems.
- You can run your Kemal application in any host provider like DigitalOcean, AWS, Google Cloud e.g if the OS is support by Crystal
