### ISSUE TITLE
Typed url parameters

### ISSUE THREAD

**Issue by romanoff** [kemalcr/kemal#352]
Is there a way to ask that id url parameter was Int instead of string? Maybe something like this:
```
get "/users/:id[int]" do |env|
end
```
Could not find in documentation

**Comment by sdogruyol** [comment]
@romanoff typed routes are not implemented yet. I've been thinking about this for a while

**Comment by samueleaton** [comment]
If added, what would the end result look like for typing a param?

**Comment by alex-lairan** [comment]
So it can be ?
```
get "/users/:id[int]" do |env|
end

get "/users/:id[string]" do |env|
end

get "/users/:id[boolean]" do |env|
end
```

This could be very cool :)

**Comment by sdogruyol** [comment]
Yeah, this format seems really applicable 👍

**Comment by alex-lairan** [comment]
Okay ! I will love it ! :D 

🕺

**Comment by lollar** [comment]
Hey @sdogruyol, I have started working on this and have a basic implementation but I am curious if you had an idea of which types you wanted to support?

**Comment by straight-shoota** [comment]
As I have already mentioned, I don't this would actually be an improvement. Even with a different implementation than #431.

Values that are dynamically extracted from the path at runtime will always have a union type of all possible types, not just the intended type. Instead, if you convert to the type directly in code, you'll get a value of the very type your converting to.

```crystal
# conventional way
get "/users/:id" do |env|
  id = env.params.url["id"].to_i
  typeof(id) # => Int32
end
# dynamic type extraction
get "/users/:id[int]" do |env|
  id = env.params.url["id"]
  typeof(id) # => Int32 | String | Bool | ...
end
```

**Comment by crisward** [comment]
Are there any frameworks (in any language) who implement this functionality in routing? 

I'd imagine you'd want to be able to declare multiple routes, so matching only on an applicable type then coercing it to the correct crystal type.

Also I'm a little unsure if this is even possible. So what is "false" is it a string or  a bool? What about 1 and 0 are they true/false or ints. What about floats, without decimal places... The regex need to match these types are not exclusive so multiple routes with multiple typed params could have an overlap.

Or I could be just over thinking this... 😕

**Comment by straight-shoota** [comment]
Yeah, in a dynamic language this is easily doable. Django for example has such a feature (https://docs.djangoproject.com/en/2.0/topics/http/urls/).

**Comment by hfjallemark** [comment]
Rocket (Rust) has great support for typed routing in a statically typed language: https://rocket.rs/v0.4/guide/requests/#dynamic-paths

The basic idea is that routes will only match if exact parameter types match. They types are inferred from the route function parameters so no need to define them in the route path.

Would love to see this in Kemal!

**Comment by straight-shoota** [comment]
Yes, a similar approach would work in Crystal as well. The specific behaviour of type conversion and validation is still a bit problematic, though. But maybe it's fine to provide something like `RawStr` to use custom implementations.

**Comment by sdogruyol** [comment]
Closing this for now as it's not a top priority
