### ISSUE TITLE
File Upload example not working

### ISSUE THREAD

**Issue by dimparf** [kemalcr/kemal#353]
Crystal 0.21.1 / Kemal master. Example on this page: http://kemalcr.com/docs/file_upload/
Error in src/your_app.cr:6: undefined method 'filename' for Tempfile
file_path = ::File.join [Kemal.config.public_folder, "uploads/", file.filename]

Tempfile in Crystal 0.21.1 not have filename method.

**Comment by sdogruyol** [comment]
@dimparf the docs are outdated 😭

**Comment by sdogruyol** [comment]
I just updated the docs 👍
