### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by CodelessFuture** [kemalcr/kemal#355]
In dynamic views 
```
<html>
<head>
  <title><%= $title %></title>
</head>
<body>
  <%= content %>
</body>
</html>
```

I think is only **title**, without _$_.....as I'm trying to follow kemal doc for learning crystal and kemal and using for my new work....I love your work and the one of the guys of crystal but both project doc difficult to follow.

My codebase is [this](crystalweb)

**Comment by sdogruyol** [comment]
@CodelessFuture `$title` was a global variable and removed from Crystal as of `0.20.0`. I'll update the documentation

**Comment by sdogruyol** [comment]
Thanks for the issue! I just updated the docs 👍
