### ISSUE TITLE
Simplifying and unify params access

### ISSUE THREAD

**Issue by msa7** [kemalcr/kemal#357]
What about simplifying/unify params access?

I think about change this

```
get "/:name" do |env|
  name = env.params.url["name"]
  render "src/views/hello.ecr"
end
```

to this

```
get "/:name" do |env|
  name = env.params["name"]
  render "src/views/hello.ecr"
end
```

or maybe even

```
get "/:name" do |env|
  name = env["name"]
  render "src/views/hello.ecr"
end
```

**Comment by f** [comment]
It was already like that at the beginning.

We seperated them in order to get same keys in different parts of request.
E.g. :name can occur both in JSON, query string and URL.

>

**Comment by f** [comment]
Besides, current implementation works lazily, if we try to parse whole
params at once it would be a big performance issue, and it was.

**Comment by msa7** [comment]
Thanks for pointing it out.

> E.g. :name can occur both in JSON, query string and URL.

IMO it problem of API design. 

We could keep `params.url, params.body...`
And do `env.param("name")` - it could be lazy, too.
Later see what is really used. 

IMO in 80% it enough to have `env.param("name")`

**Comment by f** [comment]
I don't quite remember but there was a non-problematic API use case that
pushed us to seperate them. Maybe @sdogruyol would explain better.

18 Nis 2017 Sal 11:25 tarihinde Sergey Makridenkov <notifications@github.com>
şunu yazdı:

**Comment by sdogruyol** [comment]
@f is right. We separated them for different parts and also made them lazy for better performance.
