### ISSUE TITLE
Check if param exists

### ISSUE THREAD

**Issue by kiliankoe** [kemalcr/kemal#358]
I'm sorry for a probably rather simple question, but I can't find anything regarding this in the docs, other issues here or in the source (although I didn't have the most thorough look through the latter). 

I'd like to access a URL param. `env.params.query["res"]` seems to be the way to go. Unfortunately this crashes with `Missing hash key: "res" (KeyError)` when that key is missing. I apparently naively assumed the type of the param to be `String | Nil` 🙈 

Is there another option of checking the param's existence first? Or optionally receiving a param if it exists or doesn't?

Thanks for helping out a crystal noob in advance 😊

**Comment by rdp** [comment]
try env.params.query["res"]?
