### ISSUE TITLE
Error with liquid.cr

### ISSUE THREAD

**Issue by icyleaf** [kemalcr/kemal#359]
```crystal
require "kemal"
require "liquid"

text = "hello world"
ctx = Liquid::Context.new
tpl = Liquid::Template.parse(text)

puts tpl.render(ctx)
```

complie and run:

```
Error in src/test.cr:9: instantiating 'Liquid::Template#render(Liquid::Context)'

puts tpl.render(ctx)
         ^~~~~~

in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kemal/src/kemal/helpers/macros.cr:65, line 1:

>  1.   Kilt.render(data)

expanding macro
in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kilt/src/kilt.cr:22, line 1:

>  1.     String.build do |__kilt_io__|
   2.       Kilt.embed(data, "__kilt_io__", )
   3.     end
   4.

instantiating 'String:Class#build()'
in /usr/local/Cellar/crystal-lang/0.22.0/src/string.cr:269: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /usr/local/Cellar/crystal-lang/0.22.0/src/string.cr:269: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kemal/src/kemal/helpers/macros.cr:65, line 1:

>  1.   Kilt.render(data)

expanding macro
in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kilt/src/kilt.cr:22, line 1:

>  1.     String.build do |__kilt_io__|
   2.       Kilt.embed(data, "__kilt_io__", )
   3.     end
   4.

instantiating 'String:Class#build()'
in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kemal/src/kemal/helpers/macros.cr:65, line 1:

>  1.   Kilt.render(data)

expanding macro
in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kilt/src/kilt.cr:22, line 2:

   1.     String.build do |__kilt_io__|
>  2.       Kilt.embed(data, "__kilt_io__", )
   3.     end
   4.

expanding macro
in lib/kilt/src/kilt.cr:13: expanding macro

    {% ext = filename.split(".").last %}
                      ^~~~~

in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kemal/src/kemal/helpers/macros.cr:65, line 1:

>  1.   Kilt.render(data)

expanding macro
in macro 'render' /Users/wiiseer/Development/crystal/wasp/lib/kilt/src/kilt.cr:22, line 2:

   1.     String.build do |__kilt_io__|
>  2.       Kilt.embed(data, "__kilt_io__", )
   3.     end
   4.

undefined macro method 'Var#split'
```

**Comment by sdogruyol** [comment]
`kilt` doesn't support `liquid.cr` //cc @jeromegn

**Comment by jeromegn** [comment]
I'm confused as to how this code would call the Kilt render logic. There's no mention of Kilt, the only thing it did was to load Kemal. Whatever's returned by `Liquid::Template.parse` called `render`, but that triggered the Kilt code? Huh.

As far as I understand the liquid philosophy (the ruby library's, at least), there shouldn't be pre-compiled templates. Liquid is a safe templating language useful for running untrusted "code" from users (the language doesn't allow you to run arbitrary Crystal code, for instance.) Therefore, the templates themselves are not *always* known at compile time. They're usually fetched from a store.

I could be wrong, but what I meant to say is that it should be possible to render templates without Kilt within Kemal :)

**Comment by sdogruyol** [comment]
There are some places which override `__kilt_io__` but i'm totally clueless how this affects `liquid.cr``

https://github.com/kemalcr/kemal/blob/master/src/kemal/helpers/macros.cr#L36

**Comment by icyleaf** [comment]
```crystal
require "liquid"
require "kilt"

text = "hello world"
ctx = Liquid::Context.new
tpl = Liquid::Template.parse(text)

puts tpl.render(ctx)
```
This code is okay only with kilt, so i think here are some problem in kemal, is it the key the `render` method in [macros.cr#L58](https://github.com/kemalcr/kemal/blob/master/src/kemal/helpers/macros.cr#L58)?

**Comment by tommasop** [comment]
I agree same problem here with ecr:

      kemal:
        github: kemalcr/kemal
        commit: 0b4856b7417592743a27fc3e30867fd141395bf6
      kilt:
        github: jeromegn/kilt
        version: 0.3.3

`Error opening file './src/views/home.ecr' with mode 'r': No such file or directory (Errno)
0x106fdd3e5: *CallStack::new:CallStack at ??
0x106fde80e: *raise<Errno>:NoReturn at ??
0x106fe5f64: *File::new<String, String, Int32, Nil, Nil>:File at ??
0x106fefc98: main at ??
Error in macro 'embed' /Users/tommasop/code/play/tcode_site/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       ECR.embed("./src/views/home.ecr", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /usr/local/Cellar/crystal-lang/0.21.1_1/src/ecr/macros.cr:69, line 1:

>  1.     {{ run("ecr/process", "./src/views/home.ecr", "__kilt_io__") }}
   2.

expanding macro
in macro 'embed' /Users/tommasop/code/play/tcode_site/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       ECR.embed("./src/views/home.ecr", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /usr/local/Cellar/crystal-lang/0.21.1_1/src/ecr/macros.cr:69, line 1:

>  1.     {{ run("ecr/process", "./src/views/home.ecr", "__kilt_io__") }}
   2.

Error executing run: ecr/process "./src/views/home.ecr" "__kilt_io__"

Got:`

but the file is there.

**Comment by tommasop** [comment]
With crystal 0.22.0 I have:

```
🤖  Your SentryBot is vigilant. beep-boop...
🤖  watching file: ./src/tcode_site/version.cr
🤖  watching file: ./src/tcode_site.cr
🤖  compiling tcode_site...
Error in macro 'embed' /Users/tommasop/code/play/tcode_site/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       ECR.embed("./src/views/home.ecr", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /usr/local/Cellar/crystal-lang/0.22.0/src/ecr/macros.cr:69, line 1:

>  1.     {{ run("ecr/process", "./src/views/home.ecr", "__kilt_io__") }}
   2.

expanding macro
in macro 'embed' /Users/tommasop/code/play/tcode_site/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       ECR.embed("./src/views/home.ecr", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /usr/local/Cellar/crystal-lang/0.22.0/src/ecr/macros.cr:69, line 1:

>  1.     {{ run("ecr/process", "./src/views/home.ecr", "__kilt_io__") }}
   2.

Error executing run: ecr/process "./src/views/home.ecr" "__kilt_io__"

Got:



🤖  Compile time errors detected. SentryBot shutting down...
```

Could it be a kilt error?

**Comment by tommasop** [comment]
Possibly related to: https://github.com/jeromegn/kilt/issues/13

**Comment by jeromegn** [comment]
It's hard to say. @icyleaf's small test showed that his code ran fine without Kemal, with Kilt.

I'm not sure what could cause this.

**Comment by tommasop** [comment]
My bad, the issue in question was that my views folder was not in the src so the files weren't actually found :( sorry also for the thread hijacking thought it was linked

**Comment by straight-shoota** [comment]
I encountered the same problem with [crinja](https://github.com/straight-shoota/crinja), an implementation of the Jinja2 template engine I am working on. So the usage is quite similar to liquid.cr. The relevant part from the error output:

```
in /crinja/src/crinja/template.cr:50: instantiating 'Crinja::Environment#with_scope(Crinja::Context)'

      env.with_scope(bindings) do
          ^~~~~~~~~~

in macro 'render' /crinja/examples/kemal/lib/kemal/src/kemal/helpers/macros.cr:65, line 1:

>  1.   Kilt.render(io)

expanding macro
```

The referenced `template.cr:50` 
```
  # Renders this template to *io* using *bindings* as local variables scope.
  def render(io : IO, bindings = nil)
    env.with_scope(globals) do
      env.with_scope(bindings) do # This is line 50
        render(io, env)
      end
    end
  end
```

Similar to the example @icyleaf provided, the failure occurs at a call to the `#render` method on the template object wich seems to somehow invoke the `render` macro from global scope.

In my case I could work around this error by putting an explizit `self` in front of the implicit call: `self.render(io, env)`. With this, everything works fine.

With liquid.cr it seems to be bit different, because there the method call already has `tpl` as explicit receiver. The only way I could find to get this compiled was to change the method name.

Overall, this looks more like a flaw in Crystal than with Kilt or Kemal. But still, such issues make me question the approach to put domain specific methods into the global scope...

**Comment by straight-shoota** [comment]
This should be fixed with crystal-lang/crystal#236 in the next release of Crystal.

**Comment by icyleaf** [comment]
Thanks, I will checkout after my holiday.

**Comment by sdogruyol** [comment]
Thank you @straight-shoota 👍
