### ISSUE TITLE
deploy docs needed - how to specify port

### ISSUE THREAD

**Issue by tigernassau** [kemalcr/kemal#360]
nice work on kemal - we are switching from Sinatra

how to run kemal on a specific port ? 
crystal myapp.cr -p 8000  => fail
Kemal.run -p 8000 => fail 
maybe answer is to run websocket but need to figure out how to integrate with nginx reverse proxy

deploying does not seem to be addressed in any samples or docs

**Comment by sdogruyol** [comment]
From CLI

Please build your app in release mode.
```
crystal build --release your_app.cr
./your_app -p 3000
```

In your code

```
Kemal.config.port = 3000
```

**Comment by DanielSokil** [comment]
This needs to be in docs: `Kemal.config.port = 3000`

**Comment by InstanceOfMichael** [comment]
This is probably preferred:
```
ENV["PORT"] ||= "3000"

Kemal.config.port = env["PORT"].to_i
```

**Comment by straight-shoota** [comment]
Better: `ENV["PORT"]?.try(&.to_i) || 3000`
