### ISSUE TITLE
Adding a filter handler bypasses logging

### ISSUE THREAD

**Issue by RX14** [kemalcr/kemal#362]
Using a `before_each` handler ends up calling `FilterHandler#initialize` which calls `Kemal.config.add_filter_handler` which invokes `Config#setup` which will setup the log handler, possibly before `logging false`.

Workaround is to set `logging false` before using `require "kemal"`.

**Comment by sdogruyol** [comment]
I actually solve this via https://github.com/kemalcr/kemal/commit/f511d21aa1dd567da882d82fccc4800f94e94089. Can you try wish `master`?

**Comment by Sija** [comment]
@sdogruyol cutting a new release would help, since having dependency with `branch: master` could easily break the build in some unspecified future. just my 2¢.

**Comment by sdogruyol** [comment]
@Sija you are right. I'll cut a new release this week.
