### ISSUE TITLE
Parse URL query params as Array only for keys ending in `[]`

### ISSUE THREAD

**Issue by Sija** [kemalcr/kemal#363]
Merging #328 changed the way how url query params are parsed resulting in several backwards incompatible changes.

ATM QS with `?arr=1` will parse as `{"arr" => "1"}`, while `?arr=1&arr=2` returns `{"arr" => ["1", "2"]}` which is to say the least, counter-intuitive. It's also incompatible with most of the languages/frameworks out there - php, ruby or [qs node module](https://github.com/ljharb/qs) (used by express.js) to name a few.

I'd like to propose rethinking this change and possibly reverting it altogether.

**Comment by sdogruyol** [comment]
I reverted #328 to keep backwards compatability

**Comment by Sija** [comment]
👍
