### ISSUE TITLE
Can't start up "Hello World!" app. Unknown token?

### ISSUE THREAD

**Issue by bigDaddyS1oth** [kemalcr/kemal#365]
Trying out the basics on the step-by-step guides on the website, and when running `crystal build --release src/first_app.cr ./first_app` the console gives a syntax error of `Syntax error in first_app:1: unknown token: '\u{7f}'` and it shows `ELF>� @@�;@8`. 

Is there a way I can edit the executable, say just renaming it to a `.cr` file then going in a changing that token to something specific (I wouldn't know what to change it to)? Or did I miss something?

EDIT: Scratch that last bit. Tried to open it with a text editor and it says "The document was not UTF-8 valid."
Uh oh

**Comment by sdogruyol** [comment]
I guess this is related to your editor and encoding

**Comment by bigDaddyS1oth** [comment]
I'll try opening it with some others. If I get it open, what do I need to change?

**Comment by bigDaddyS1oth** [comment]
Alright it's opened up in Atom. Can I do anything to it? The error message specifically points to the E in `ELF����>�� @@�;�@8`

**Comment by bigDaddyS1oth** [comment]
Nevermind. I'm a moron.
