### ISSUE TITLE
kemal example upload script error

### ISSUE THREAD

**Issue by codenoid** [kemalcr/kemal#366]
hi, i just try to use file upload script in http://kemalcr.com/docs/file_upload/ ,,
but i got a error, in the first error info, 
`Error in src/kemalblog.cr:24: instantiating 'File:Class#join(Array(String | Nil))'
    file_path = ::File.join [Kemal.config.public_folder, "uploads/", file.filename]
                       ^~~~
`
screenshot : https://s7.postimg.org/d1mbwaz2j/kemalbug4.png
thanks

**Comment by bitrvmpd** [comment]
Hello!, did you create the "uploads" folder inside "public"?. I had the same issue, but after i created that specific path it worked flawlessly.

**Comment by tanghoangphong** [comment]
file_path = "#{Dir.current}/public/uploads/#{file.filename.to_s}"
it's work with me.

**Comment by sdogruyol** [comment]
Thanks for your responses. Closing this 👍
