### ISSUE TITLE
Missing view gives an unclear error message

### ISSUE THREAD

**Issue by Fryguy** [kemalcr/kemal#369]
I accidentally put my views directory into the src directory, but had a get statement like the following:

```crystal
require "kemal"

get "/" do
  render "views/index.ecr"
end

Kemal.run
```

This caused Kemal to not find the view, which is correct, however the error message produced in no way told me that:

```text
$ crystal build src/kemal_crystal_bug.cr
Error in macro 'embed' /Users/jfrey/projects/kemal_crystal_bug/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       ECR.embed("views/index.ecr", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /usr/local/Cellar/crystal-lang/0.22.0/src/ecr/macros.cr:69, line 1:

>  1.     {{ run("ecr/process", "views/index.ecr", "__kilt_io__") }}
   2.

expanding macro
in macro 'embed' /Users/jfrey/projects/kemal_crystal_bug/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       ECR.embed("views/index.ecr", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /usr/local/Cellar/crystal-lang/0.22.0/src/ecr/macros.cr:69, line 1:

>  1.     {{ run("ecr/process", "views/index.ecr", "__kilt_io__") }}
   2.

Error executing run: ecr/process "views/index.ecr" "__kilt_io__"

Got:


```

I did not expect the "Got:" part to be empty, and instead expected something closer to the kind of error from a missing require file: `Error in src/bar.cr:1: while requiring "foo": can't find file 'foo' relative to '/Users/jfrey/projects/bar/src'`

I'm not sure if the lack of an error message is a Kemal bug or a bug in ECR.  I figured I'd open it up here first to start the journey.

It took me a while to figure out what was going on.  I'm new to kemal, and didn't know the views directory was relative to the project root.  I thought it was relative to the main .cr file, hence why I put the views directory under my src directory.  I couldn't find any good documentation on an expected directory structure of the project, and didn't realize my error until I found the sample kemal-chat app.  I'm willing to update the documentation for this, but not sure where it is supposed to go (i.e. should it be a new page in https://github.com/kemalcr/kemalcr.com/tree/master/_docs or just as a part of one of the existing pages there?)

**Comment by sdogruyol** [comment]
Welcome @Fryguy , thanks for using Kemal.

Unfortunately the error message comes from `ecr` which is included in Crystal itself. 
About the file structure you can improve the http://kemalcr.com/docs/views/ docs which is located in https://github.com/kemalcr/kemalcr.com/blob/master/_docs/views.md

**Comment by Fryguy** [comment]
Opened as an issue an Crystal: https://github.com/crystal-lang/crystal/issues/4577

**Comment by sdogruyol** [comment]
I just saw that. Thank you @Fryguy 👍
