### ISSUE TITLE
Inefficient use of string builders

### ISSUE THREAD

**Issue by foliot** [kemalcr/kemal#370]
The render macros use nested string builders and intermediate memory buffers to render the resulting template (see example expansion below). From a very hacked-together test, I think the performance could be improved by eliminating the string builders and writing directly to the output IO.

## layout.ecr
```ecr
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
</head>
<body>
  <%= yield_content "main" %>
</body>
</html>
```

## hello.ecr
```ecr
<% content_for "main" do %>
  <table>
    <tr>
      <th>id</th>
      <th>message</th>
      </tr>
      <% data.each do |hello| %>
        <tr>
          <td><%= hello %></td>
          <td><%= hello %></td>
        </tr>
      <% end %>
  </table>
<% end %>
```

## test.cr
```crystal
data = [] of String
  
100.times do
  data += ["abc", "def", "ghi"]
end

render("views/hello.ecr", "views/layout.ecr")
```

## Macro expansion
```crystal
__content_filename__ = "views/hello.ecr"

content = String.build do |__kilt_io__|
  __temp_37 = -> do
    __kilt_io__ = IO::Memory.new
    __kilt_io__ << "\n\t<table>\n\t\t\t<tr>\n\t\t\t<th>id</th>\n\t\t\t<th>message</th>\n\t\t\t</tr>\n\t\t\t"
    data.each do |hello|
      __kilt_io__ << "\n\t\t\t\t<tr>\n\t\t\t\t<td>"
      hello.to_s(__kilt_io__)
      __kilt_io__ << "</td>\n\t\t\t\t<td>"
      hello.to_s(__kilt_io__)
      __kilt_io__ << "</td>\n\t\t\t\t</tr>\n\t\t\t"
    end
    __kilt_io__ << "\n\t</table>\n"
    __kilt_io__.to_s
  end
  CONTENT_FOR_BLOCKS["main"] = Tuple.new("views/hello.ecr", __temp_37)
  nil
end

String.build do |__kilt_io__|
  __kilt_io__ << "<!DOCTYPE html>\n<html>\n<head>\n\t<title>Hello</title>\n</head>\n<body>\n\t"
  (if CONTENT_FOR_BLOCKS.has_key?("main")
    __caller_filename__ = CONTENT_FOR_BLOCKS["main"][0]
    __temp_38 = CONTENT_FOR_BLOCKS["main"][1]
    if __content_filename__ == __caller_filename__
      __temp_38.call
    end
  end).to_s(__kilt_io__)
  __kilt_io__ << "\n</body>\n</html>"
end
```

**Comment by foliot** [comment]
They also mention the performance cost of to_s instead of to_s(io) in the Crystal book: [https://crystal-lang.org/docs/guides/performance.html](https://crystal-lang.org/docs/guides/performance.html)

**Comment by foliot** [comment]
A similar issue is holding back the performance (even though it is already awesome!) of the TechEmpower benchmark for Kemal. I mixed the db code from the Kemal benchmark with the Crystal benchmark code and got huge performance increases over the Kemal code. The problem is that the Kemal code returns things like `results.to_json`, but it should always do things like `results.to_json(response_io)`. When you do `to_json` instead of `to_json(io)`, it has to make a string object then copy that string object into the output IO buffer. `to_json(io)` writes straight into the output IO buffer.

Here's a gist with the Crystal code and the results: [https://gist.github.com/foliot/c5761ea1fbf642dd7679b513aa8c585a](https://gist.github.com/foliot/c5761ea1fbf642dd7679b513aa8c585a)

**Comment by sdogruyol** [comment]
Hey @foliot, thanks a lot for your great performance tips 👍 

I'd be happy to accept a PR about those 😄

**Comment by foliot** [comment]
You're welcome! You might also want to do the same thing that I did for the fortune benchmark temporarily while we figure out how to improve the performance of `render`. From the results I got, it looked like doing `ECR.embed "views/fortunes.ecr", response` instead of `render "views/fortunes.ecr"` was something like 4 or 5 times faster (88641 requests for Kemal vs 392819 requests for Crystal).
