### ISSUE TITLE
Update to Kilt v0.4

### ISSUE THREAD

**Issue by z64** [kemalcr/kemal#371]
Hi there!

It would seem that the `shard.yml` within `kilt` `0.3.3` has an incorrect version number.

https://github.com/jeromegn/kilt/blob/v0.3.3/shard.yml#L2

This causes a slight "issue" that every time you run `shards build`, it re-fetches your dependencies because it thinks it never has a lib that satisfies the rule of `~> 0.3.3`.
```
Installing kilt (0.3.3)
$ shards list
Shards installed:
  * kilt (0.1.0)
```
```
$ shards check
Dependencies aren't satisfied. Install them with 'shards install'
```
This can be circumvented by just editing your `lib/kilt/shard.yml` to read `0.3.3` and `shards build` won't be any the wiser.

That aside, looking at the next tag, v4.0, it would appear that `kemal` should be able to update its dependency without any breaking changes.
https://github.com/jeromegn/kilt/compare/v0.3.3...master

**Comment by z64** [comment]
I might throw in too - the current `README` kind of passively suggests people use `master` in their dependency listing for `kemal` in their app.

While people *should* know better, I think it would be best to drop "`branch: master`" from `README` so it defaults to the latest tag instead.

Just a suggestion.

**Comment by sdogruyol** [comment]
@z64 that's for the tips 👍  Removing master from readme sounds great 💯

**Comment by sdogruyol** [comment]
Fixed via https://github.com/kemalcr/kemal/commit/eb3e83d5903ce8f18d796a97ae200009fdf2c9a2

**Comment by z64** [comment]
Thanks! :)
