### ISSUE TITLE
Application layer DSL

### ISSUE THREAD

**Issue by tarvit** [kemalcr/kemal#373]
Are there any plans for providing some simple approach for creating idiomatic applications in Kemal?
I am talking about adding some base classes for `Application`, `Controller`, `Router` etc.

**Comment by straight-shoota** [comment]
I think it would at least be nice to support a modular style where you subclass `Kemal::Application` as an alternative to top-level DSL (like in Sinatra modular vs. classic style).

**Comment by tarvit** [comment]
@straight-shoota Exactly. I'd like to have possibility to use DSL in specific objects only without having them in global namespace. But having them in global namespace is good for marketing reasons. Because it takes much less code to get basic Kemal app working.

**Comment by sdogruyol** [comment]
I'm actually thinking of having modular applications but didn't have time to dedicate. PRs are welcome and I'm happy to give feedback / guidance.

**Comment by sdogruyol** [comment]
Closing this in favor of #378
