### ISSUE TITLE
Wrong Content-Length for small amounts of data via IO.copy

### ISSUE THREAD

**Issue by jreinert** [kemalcr/kemal#374]
Minimal example:

``` crystal
require "kemal"

DATA = "foo"

get "/" do |context|
  context.response.content_length = DATA.bytesize
  IO.copy(IO::Memory.new(DATA), context.response)
end

spawn { Kemal.run(3000) }
sleep 1

HTTP::Client.get("http://localhost:3000") do |response|
  puts "Expected: #{DATA.inspect}"
  puts "Received: #{response.body_io.gets_to_end.inspect}"
end
```

You will see that the received data differs from the original. This is an issue with Kemal itself since if you replace kemal in this case with a pure `HTTP::Server` it will be handled correctly.

**Comment by sdogruyol** [comment]
Thanks for reporting this @jreinert

**Comment by bew** [comment]
Using `send_file context, DATA.to_slice` instead of using `IO.copy` make it work.

It's not the perfect solution for streaming, for that you can use `send_file context, "/file/path"` (more infos in the [docs](http://kemalcr.com/api/toplevel.html#send_file(env,path:String,mime_type:String?=nil)-class-method))

**Comment by sdogruyol** [comment]
Taking a close look at this issue shows that calling `to_s` for `IO` actually returns the size of the data.
https://github.com/kemalcr/kemal/blob/master/src/kemal/route_handler.cr#L36

**Comment by crisward** [comment]
This is caused by your route returning data, which then gets appended to the output.
If you return nil it works fine.

```
require "kemal"

DATA = "foo"

get "/" do |context|
  context.response.content_length = DATA.bytesize
  IO.copy(IO::Memory.new(DATA), context.response)
  nil
end

spawn { Kemal.run(3000) }
sleep 1

HTTP::Client.get("http://localhost:3000") do |response|
  puts "Expected: #{DATA.inspect}"
  puts "Received: #{response.body_io.gets_to_end.inspect}"
end
```

**Comment by RX14** [comment]
Sure looks like unintentionally returning data from a route is a common problem. Perhaps the design should be rethought to be more explicit.

**Comment by crisward** [comment]
Think the idea is taken from http://www.sinatrarb.com/ which makes for a very simple interface. 

I quite like the way express js does it, with an object, with lots of return methods, ie res.send(). Koa.js uses `ctx.body =`, though that may be confusing as body is also on `ctx.params.body` Either way some convenience methods which set content type etc could be good.

**Comment by crisward** [comment]
Just looking over sinatra docs, it looks like they limit the kind of things that can be returned. 

* A String
* An Array with three elements: [status (Fixnum), headers (Hash), response body (responds to #each)]
* An Array with two elements: [status (Fixnum), response body (responds to #each)]
* An object that responds to #each and passes nothing but strings to the given block
* A Fixnum representing the status code

This could be a good solution for kemal too?

**Comment by RX14** [comment]
I think that just 1 and 5 are good here. The arrays would be better as tuples in crystal, but really it'd be better not to have them at all and ask people to simply use `status_code = xxx`. I think 4 is weird, what's the usecase.

**Comment by crisward** [comment]
4 I think is for streaming.

**Comment by sdogruyol** [comment]
Actually Kemal also tries to restrict the return to 1

**Comment by crisward** [comment]
If this is the bit of code that does this, it actually seems to coerce it to a string
https://github.com/kemalcr/kemal/blob/master/src/kemal/route.cr#L11

Perhaps it could do a type check first and only return strings. 
This would obviously be a breaking change for anyone returning things other than strings. It would certainly fix this difficult to spot bug. 

BTW I spotted it straightaway because it's happened to me quite a few times, especially when returning binary files from routes. (hence this fix -
 https://github.com/kemalcr/kemal/commit/48128696c6130e76fcf29529f630a0d7c3cd813b)

**Comment by sdogruyol** [comment]
Do you want to dive into that? @crisward

**Comment by RX14** [comment]
I think returning strings only is fine. Simply check the return value with `is_a?` and then discard if its not a string. No coersion should be done.

**Comment by sdogruyol** [comment]
@RX14 sounds interesting. Compile-time errors for non-String stuff then?

**Comment by RX14** [comment]
No, of course not. Silently ignore them as if you'd annotated the method `: Nil`

**Comment by sdogruyol** [comment]
I'm not sure about silent ignore, that'd also lead to hard to find behaviors like the one in this issue.

**Comment by crisward** [comment]
If we don't ignore it, every current route which doesn't return a string will throw an error, and the only way to fix will be to return an empty string, which could look a bit odd.

It should be documented that routes should return strings (which they probably already do). 

We could perhaps have a flag / debug log setting to indicate when a routes return value is not being returned to the browser. So these can be found and fixed if necessary.

Thoughts?
