### ISSUE TITLE
redirect with flash session

### ISSUE THREAD

**Issue by netwarp** [kemalcr/kemal#375]
Hi,
I would like to know if it's possible to make a redirect with a flash data in session.
It could look like something like that: 
```crystal
post "/comment" do
  comment = env.params.body["comment"]
  env.redirect("/").with("success", "Your comment has been successfully sent")
end
```
I know it"s very easy on laravel framework but I don't know do the same on kemal.
Thanks.

**Comment by crisward** [comment]
You may want to checkout this shard - https://github.com/neovintage/kemal-flash.

**Comment by sdogruyol** [comment]
Thanks for the answer @crisward, I think that shard is great for this case 👍
