### ISSUE TITLE
X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by crisward** [kemalcr/kemal#379]
Just been doing some pen testing on our site. Zap, Owasps pen testing tool suggests adding `X-Content-Type-Options: nosniff` header to static files.

https://msdn.microsoft.com/en-us/library/gg622941%28v=vs.85%29.aspx

I can't see a downside to this. 

Adding here ok?
https://github.com/kemalcr/kemal/blob/master/src/kemal/helpers/helpers.cr#L100

**Comment by sdogruyol** [comment]
@crisward go for it 👍

**Comment by sdogruyol** [comment]
Closed via #380
