### ISSUE TITLE
Add information about running Kemal App in production mode

### ISSUE THREAD

**Issue by solisoft** [kemalcr/kemal#388]
Hi,

You should add in your documentation a paragraph about how running Kemal App in production mode.

```
crystal build --release --no-debug src/<app_name>.cr
KEMAL_ENV=production ./<app_name>
```

For now I run it in inside a `screen` but a monit config sample can be useful too.

Great work though ;)

**Comment by kazzkiq** [comment]
Didn't knew this "production mode" even existed! Are there notable performance gains by enabling it?

**Comment by sdogruyol** [comment]
@kazzkiq there's no obvious performance gain :smile: However it's a best practice to use `KEMAL_ENV=production` in a prod application.

**Comment by sdogruyol** [comment]
This is now documented in Kemal Guide http://kemalcr.com/guide/#environment
