### ISSUE TITLE
Add more information to the API page

### ISSUE THREAD

**Issue by Cyan101** [kemalcr/kemal#390]
As of now the API page is pretty bland and nothing in the [config page](http://kemalcr.com/api/Kemal/Config.html) is actually explained.

Obviously some things should be obvious like what "port" changes, but somethings aren't exactly 100% such as `host_binding` or `server`, I guess to some its obvious while as to others it isn't. Either way i think this page and some others could use some more information on them to help people

**Comment by sdogruyol** [comment]
Hey @Cyan101, API doc is generated with `crystal doc` from the Kemal source code. I'm open for any PRs / improvements there :+1:

**Comment by emmiep** [comment]
Is it just me or is the API docs completely gone now? The link @Cyan101 posted does not work and there's no link to the API docs on the website or the github from what I can tell.

**Comment by lebogan** [comment]
It's at: https://kemalcr.com/docs/Kemal/Config.html
A link to the API is missing on the site main page.

**Comment by lebogan** [comment]
It's at: https://kemalcr.com/docs/Kemal/Config.html
A link to the API is
missing on the site main page.

**Comment by sdogruyol** [comment]
The API doc is intentionally removed 👍
