### ISSUE TITLE
I'm not able to define different routes for websockets

### ISSUE THREAD

**Issue by jmrepetti** [kemalcr/kemal#395]
Going through the guide I read that's is possible to define different routes for websockets (http://kemalcr.com/guide/#websockets) but I'm not able to make it work. The last 'ws' definition is the one that handle the socket connection, the first one seems to be ignored. 

Here's my code:

```crystal
require "kemal"

ws "/room_socket" do |socket|
  socket.send "room_socket"
end

ws "/player_socket" do |socket|
  socket.send "player_socket"
end

Kemal.run
```
The html with the socket connection is a static file served from public/index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Title</title>


    <script>
      var playerSocket = new WebSocket("ws://0.0.0.0:3000/player_socket");

      playerSocket.onmessage = function (event) {
        console.log(event.data);
      }

      var roomSocket = new WebSocket("ws://0.0.0.0:3000/room_socket");

      roomSocket.onmessage = function (event) {
        console.log(event.data);
      }
    </script>

  </head>
  <body>
  </body>
</html>
```

When I access Chrome console log prints:

```javascript
player_socket
player_socket
```

I expect to see the messages from the different sockets.

If I change the order of the routes:

```crystal
require "kemal"

ws "/player_socket" do |socket|
  socket.send "player_socket"
end

ws "/room_socket" do |socket|
  socket.send "room_socket"
end

Kemal.run
```

Then Chrome console prints:

```
room_socket
room_socket
```

From the root project folder I run:

```
$ crystal run src/example.cr 
```
I couldn't find in the source code the logic where the routes are matched for Websockets, I saw how is done for HTTP routes, and If I understand correctly, when the handlers are passed to the Http::Server (https://github.com/kemalcr/kemal/blob/master/src/kemal.cr#L31) 
only the first websocket handler will be processed, is it correct? The first to be processed is the last definition due the way is inserted in the HANDLERS array  (https://github.com/kemalcr/kemal/blob/master/src/kemal/config.cr#L165)

I think I can find a workaround for this, is just that the documentation says is possible and I wanted to do it that way. 

I'll keep debugging.
Thanks!

**Comment by sdogruyol** [comment]
I've just created and tested your snippet. I'm seeing the correct output in the Chrome console

```
player_socket
room_socket
```

What's your Kemal version?

**Comment by jmrepetti** [comment]
I'm using the master revision


dependencies:
  kemal:
    github: kemalcr/kemal
    branch: master

**Comment by sdogruyol** [comment]
I reproduced this on Kemal master

**Comment by jmrepetti** [comment]
I did a small test based on how handlers are loaded and I think the websockets routes needs to be wrapped by a multiplexer handler like Kemal::RouteHandler does, right? Is this test correct?

```ruby
# Based on this
# config.server = HTTP::Server.new(config.host_binding, config.port, config.handlers)
# config.handlers => [#<Kemal::InitHandler:0x10543cb70 @next=nil>,
#  #<Kemal::CommonLogHandler:0x10543c990>,
#  #<Kemal::CommonExceptionHandler:0x10543c960 @next=nil>,
#  #<Kemal::StaticFileHandler:0x10543a900>,
#  #<Kemal::WebSocketHandler:0x10543aa40>,
#  #<Kemal::WebSocketHandler:0x10543aac0>,
#  #<Kemal::RouteHandler:0x10543ab40>]

require "kemal"
require "http/server"

ws1 = Kemal::WebSocketHandler.new "/a" { |socket|
  socket.send "ws1"
}

ws2 = Kemal::WebSocketHandler.new "/b" { |socket|
  socket.send "ws2"
}

server = HTTP::Server.new("127.0.0.1", 8080, [
  HTTP::ErrorHandler.new,
  HTTP::LogHandler.new,
  HTTP::CompressHandler.new,
  HTTP::StaticFileHandler.new("."),
  ws1,
  ws2,
]).listen

```

And I get 'ws1' two times in the JS console.
