### ISSUE TITLE
Websocket routes breaking get routes

### ISSUE THREAD

**Issue by crisward** [kemalcr/kemal#401]
If you have 
```
ws "/" do |socket, ctx|
end
```
below no longer gets hit... in master
```
get "/" do |ctx|
end
```

**Comment by crisward** [comment]
Found this out the hard way... pushed it live 😢

**Comment by sdogruyol** [comment]
Sad to hear that :cry: It's fixed in master now :+1:

**Comment by crisward** [comment]
Thanks - it was only our site, did the mistake of pushing quick because I wanted to leave. Fixed after a minute or two. 👍
