### ISSUE TITLE
Class/instance methods as route handlers

### ISSUE THREAD

**Issue by n7olkachev** [kemalcr/kemal#402]
Example:
```
get "/", HomeController, :index
```
I would like to work on PR, if you are interested in it.

**Comment by sdogruyol** [comment]
Kemal doesn't enforce any patterns like `MVC` You can already achieve this behaviour with Procs

**Comment by danielpclark** [comment]
@n7olkachev You can see an example of doing this with a Proc here: https://blog.codeship.com/crystal-from-a-rubyists-perspective/

**Comment by n7olkachev** [comment]
Thanks, got it
