### ISSUE TITLE
Can't starting "hello, world" app.

### ISSUE THREAD

**Issue by spudro228** [kemalcr/kemal#404]
Hi!
Run the command: `crystal build ./src/your_app.cr`
And I get an error:
> /usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/spudro/cristal/your_app/your_app'  -rdynamic  -lz `command -v p
kg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --l
ibs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/us
r/local/lib`

`ldconfig -p | grep libssl` returned

>  libssl3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl3.so
        libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
        libssl.so.1.0.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.1.0.0
        libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so

OS: Ubuntu 16.04 xenial

**Comment by sdogruyol** [comment]
This is not a Kemal error but mostly likely an openssl version error. I'm not using Ubuntu 16.04 so it's hard for me to test this.

**Comment by spudro228** [comment]
@sdogruyol 
Thanks for the answer!
Just needed to install libssh-dev.

**Comment by sdogruyol** [comment]
@spudro228 could you please close this issue?

**Comment by RX14** [comment]
The actual meaningful error was
```
/usr/bin/ld: cannot find -lz
```

This means you should have installed zlib's devel package.

**Comment by spudro228** [comment]
@RX14 Lol, i installed libssh-dev and It works!
Maybe zlib1g-dev have in dependencies libssh-dev?

**Comment by RX14** [comment]
>libssh-dev happens to depend on zlib1g-dev
