### ISSUE TITLE
Route namespace / prefix ?

### ISSUE THREAD

**Issue by blocknotes** [kemalcr/kemal#411]
Is it possible to set a prefix for a group of routes?
Something like Rails namespacing:
```
  namespace :api do
    namespace :v1 do
      # ...
    end
  end
```
Currently I'm doing:
```
  PREFIX = "/api/v1"
  get "#{PREFIX}/posts" do
    # ...
  end
  get "#{PREFIX}/authors" do
    # ...
  end
```

**Comment by sdogruyol** [comment]
No, Kemal is unopinionated about routes. There's an external shard which may be useful for you https://github.com/jwoertink/kave

**Comment by blocknotes** [comment]
Ok, thank you

**Comment by Ashvith10** [comment]
> No, Kemal is unopinionated about routes. There's an external shard which may be useful for you https://github.com/jwoertink/kave

Looks like kave is no longer maintained.
