### ISSUE TITLE
A problem with OpenSSL

### ISSUE THREAD

**Issue by kendim** [kemalcr/kemal#414]
There is a problem with OpenSSL while running Kemal. I did not install OpenSSL, the problem is obviously caused by this. But i want to use LibreSSL. In this case what should it be?

`O-penS-S-L-5858S-S-L-5858C-ontext5858S-erver.o: In function 'add_options':
/usr/lib64/crystal/openssl/ssl/context.cr:274: undefined reference to 'SSL_CTX_set_options'
collect2: hata: ld çıkış durumu 1 ile döndü`
`Error: execution of command failed with code: 1: 'cc "${@}" -o '/home/kendim/.cache/crystal/crystal-run-art.tmp'  -rdynamic  -lz 'command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'' 'command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'' -lpcre -lm -lgc -lpthread /usr/lib64/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib'`
Here is the output.

**Comment by sdogruyol** [comment]
There's an open issue for LibreSSL support in Crystal https://github.com/crystal-lang/crystal/issues/4676
