### ISSUE TITLE
Gracefully close websocket connections on server INT

### ISSUE THREAD

**Issue by danielwestendorf** [kemalcr/kemal#415]
Given the websocket recipe from the cookbook

```cyrstal-lang
require "kemal"

messages = [] of String
sockets = [] of HTTP::WebSocket

ws "/" do |socket|
  sockets.push socket

  # Handle incoming message and dispatch it to all connected clients
  socket.on_message do |message|
    messages.push message
    sockets.each do |a_socket|
      a_socket.send messages.to_json
    end
  end

  # Handle disconnection and clean sockets
  socket.on_close do |_|
    sockets.delete(socket)
    puts "Closing Socket: #{socket}"
  end
end

Kemal.run
```

When a client disconnects, the `HTTP::Websocket#on_close` block is executed. 👍 

However, when the server receives an `INT` signal, the same code block is not executed. This prevents any cleanup from happening that might be handled in the `#on_close` block.

I've tried trapping on `INT` with no success:
```crystal-lang
Signal::INT.trap do
  puts "Shutting down!"
  sockets.each do |socket|
    socket.close
  end
end
```

Are there facilities to invoke the websocket's `#on_close` block before shutting down the server completely?

**Comment by straight-shoota** [comment]
Did you happen to add that trap after `Kemal.run`? Then it won't be reached.
Or the regular handler in [src/kemal.cr](https://github.com/kemalcr/kemal/blob/210e2c0801294e1d013d4120e3b71292e39d4f72/src/kemal.cr#L44) runs first and then exits the programm.

**Comment by RX14** [comment]
I'm interested to know the usecase for this given that the mechanism wouldn't be reliable, for example `kill -9` or a segfault wouldn't be able to trap shutdown.

Probably a `sleep 0` after using `socket.close` might reschedule fibers to deliver `on_close` messages.

**Comment by danielwestendorf** [comment]
@straight-shoota No, before the `Kemal.run`. I'm guessing the `Kemal.stop`, which calls `exit` is exiting the program prior to my code? Or the server is being shutdown and the websockets are closed without executing the `#on_close` block?

@RX14 Yes, in those cases, this wouldn't be reliable. I'm more looking for more consistency when graceful shutdowns due to app deploys. I wouldn't expect crashes to account for this necessarily. The ultimate goal for this is a best-effort notify other services of a websocket's connectivity state.

Adding a `sleep 0` doesn't seem to help with invoking the `#on_close` block.

**Comment by danielwestendorf** [comment]
I'm wondering if a PR would be entertained to obtain these needs. I have a few ideas so far:

1. Add config option to disable trapping `INT`. This would leave trapping `INT` to the end user, and allow them to do whatever cleanup is needed.

2. Add `Kemal.at_exit(&handler : Int32 -> ) : Nil` which behaves similar to the top level [at_exit](https://crystal-lang.org/api/0.23.1/toplevel.html#at_exit%28%26handler%3AInt32-%3E%29%3ANil-class-method) method. This would invoke any passed blocks before shutting down the server and exiting.

3. A single config `at_exit` option which takes a block and is invoked before shutting down the server and exiting.

4. Maybe shard which monkey patches `Kemal.stop`? 👎

**Comment by RX14** [comment]
So we've determined your exit handler simply isn't being run?

**Comment by straight-shoota** [comment]
When (if?) #378 gets merged you'll have `Kemal::Base` for the basic behaviour and `Kemal::Application` for additional features for a ready-to-use app - like trapping signals.

Then you can easily use only the base and implement those special things in a way you need for your specific task.

**Comment by RX14** [comment]
This shouldn't require changing everything out. Why is kemal using exit in the int hander anyway?

**Comment by danielwestendorf** [comment]
Correct, my exit handler isn't being run at all, regardless of where I put it. Here is an example:

```crystal
# src/ex.cr
require "kemal"

Signal::INT.trap do
  puts "Trapping INT"
  10.times do |i|
    puts "Executing #{i}"
    sleep 1
  end
end

Kemal.run
```

```sh
$ crystal run src/ex.cr
[development] Kemal is ready to lead at http://0.0.0.0:3000
^CKemal is going to take a rest!
$
```

**Comment by danielwestendorf** [comment]
It seems that my trap is [getting lost](https://github.com/crystal-lang/crystal/blob/e2a1389e8165fb097c785524337d7bb7b550a086/src/signal.cr#L75-L76) because it isn't running before exit.

I've had some luck doing the following:

1. Remove the `exit` call in `Kemal.stop`
2. Using an `at_exit` block to do my cleanup. The server is dead at this point and all connections closed, so I'll just have to extract my cleanup logic to be outside of the `HTTP::WebSocket#on_close` block.

At the end of the day, however, I'd expect that `HTTP::WebSocket#on_close` block to be invoked regardless of the client or the server closing the socket.

**Comment by danielwestendorf** [comment]
I ended up getting something semi-functional by adding an `at_exit` block after my `Kemal.run` which will work for now.
