### ISSUE TITLE
Kemal fails to run

### ISSUE THREAD

**Issue by AleffSouza** [kemalcr/kemal#418]
I have started to explore kemal and when I run the most basic example I got a compiler error.

I think the last commit has broken the building cause It's failing exactly what the commit 902d87c proposes to change. 

```
lib/kemal/src/helpers/helpers.cr:137 undefined method open for Flate::Writer::Class
```

**Comment by crisward** [comment]
Looks like you're using master. (Please use the latest release instead https://github.com/kemalcr/kemal/releases . Master has been updated in preparation for the next release of Crystal.
