### ISSUE TITLE
Failing to install Kemal

### ISSUE THREAD

**Issue by StormFire-Technologies** [kemalcr/kemal#419]
I am running crystal version 0.23.1 and trying to install the latest version of Kemal but when I add kemal to my dependencies and then run Shards Install it gives me the error `Failed to clone https://github.com/kemalcr/kemal.git`

**Comment by sdogruyol** [comment]
Do you have `git` installed?

**Comment by StormFire-Technologies** [comment]
Yeah, I use `git` all the time. for my project repo I am using bitbucket for my source control, and I had to adjust some setting with `git`. More specifically, I had to change the git push settings so that they would push using `ssh` rather than `https`. But I don't see how that would affect a `git clone`

**Comment by sdogruyol** [comment]
Could you please share you `shard.yml`?

**Comment by StormFire-Technologies** [comment]
Sure thing:
`name: challInit
version: 0.1.0

dependencies:
  kemal:
    github: kemalcr/kemal

authors:
  - Joshuah Charney <jcharney95@gmail.com>

targets:
  challInit:
    main: src/challInit.cr

crystal: 0.23.1

license: MIT`

**Comment by StormFire-Technologies** [comment]
My version of `git` is `git version 2.7.4` as well

**Comment by sdogruyol** [comment]
Can you try installing via `crystal deps` command

**Comment by StormFire-Technologies** [comment]
I am getting the same result :(
`$ crystal deps`
`Updating https://github.com/kemalcr/kemal.git`
`Failed to clone https://github.com/kemalcr/kemal.git`

**Comment by omarroth** [comment]
What happens if you try to clone Kemal manually?

**Comment by StormFire-Technologies** [comment]
`Cloning into 'kemal'...`
`Permission denied (publickey).`
`fatal: Could not read from remote repository.`

`Please make sure you have the correct access rights
and the repository exists.`

**Comment by omarroth** [comment]
Could you share your .gitconfig?

**Comment by StormFire-Technologies** [comment]
Sure:
`[core]`
	`repositoryformatversion = 0`
	`filemode = true`
	`bare = false`
	`logallrefupdates = true`

**Comment by StormFire-Technologies** [comment]
I don't have a `[github]` section for my `gitconfig`. Could that be the issue?

**Comment by omarroth** [comment]
I don't think so, the setting for forcing ssh seems like it may be affecting clone. Could you share what you're using to force ssh?

**Comment by StormFire-Technologies** [comment]
This is the command I used: `git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"`
But I can't remember specifically if I accidentally used `git config --global url."git@github.com:".insteadOf "https://github.com/"` as well initially

**Comment by StormFire-Technologies** [comment]
I guess I could just try typing in the second command but switching the `git@github.com:` with `https://github.com/`

**Comment by RX14** [comment]
This seems to be a general shards issue, maybe open an issue in crystal-lang/shards. or justcc @ysbaddaden.

**Comment by StormFire-Technologies** [comment]
So maybe its an issue with the version of crystal i have?

**Comment by RX14** [comment]
Actually, if you can't clone kemal manually, then it's a local git configuration error. Fix your gitconfig?

**Comment by StormFire-Technologies** [comment]
Ok, so what would be there to fix? Sorry I'm a little bit of a newbie when it comes to git configuration files, I haven't dove into them too much

**Comment by straight-shoota** [comment]
@StormFire-Technologies Shards should always use `https://github.com/kemalcr/kemal.git` (and it does say so), so this should not require you to authenticate with a public key.

Could you please run `shards install --verbose`, as well as `git clone https://github.com/kemalcr/kemal.git --verbose`?

**Comment by StormFire-Technologies** [comment]
`shards install -v` returns:
    

> `Updating https://github.com/kemalcr/kemal.git`
>     `git clone --mirror --quiet -- 'https://github.com/kemalcr/kemal.git' kemal`
>     `Failed to clone https://github.com/kemalcr/kemal.git`

------------------------------------------------------------------------------------------------------------------------------

`git clone https://github.com/kemalcr/kemal.git -v` returns:

> `Cloning into 'kemal'...`
> `Permission denied (publickey).`
> `fatal: Could not read from remote repository.`
> 
> `Please make sure you have the correct access rights`
> `and the repository exists.`

**Comment by ysbaddaden** [comment]
This is going circles. You have a Git issue that translates `https://github.com/` into `git@github.com:`. That is translates the HTTPS URI to an SSH one, which requires a SSH key which fails because you don't have any perssion on the `kemalcr/kemal` repository.

I'm sorry, I can't help.

**Comment by StormFire-Technologies** [comment]
Fixed it! I had to manually go into my gitconfig file and remove the part telling it to grab the SSH version. Noob mistake on my part. Sorry for all of this guys. Closing this issue now.

**Comment by cserb** [comment]
I'm experiencing the same issue now:
```
shards install                    
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/veelenga/ameba.git
Fetching https://github.com/kemalrc/kemal.git
Username for 'https://github.com':
```

Cloning manually works fine though
