### ISSUE TITLE
Request environment in websocket route

### ISSUE THREAD

**Issue by Superman132** [kemalcr/kemal#423]
Can you access the request environment in a websocket route. I need to access the cookies of the request.

**Comment by sdogruyol** [comment]
@Superman132 you can access the environment as the second parameter the block

```
ws "/" do |socket, env|
  env.request
end
```

**Comment by YukiSakuraVN** [comment]
The context is inconsisten between context of ws and context of ws' session. Please try yourself the following code:
```crystal
ws "/" do |socket, ctx|
    pp! ctx #line_1
    pp! ctx.session #line_2
end
```
You will see some differences:
- Look in to #line_1 screen dump, the ctx.@request.@cookies is nil while there is Cookie in the request headers
- In the screen dump of #line_1, the ctx.@session is nil. But in the screen dump of #line_2 the ctx.session.@context.@session is not
