### ISSUE TITLE
How can I do wss instead of ws with kemal for websockets?

### ISSUE THREAD

**Issue by codingphasedotcom** [kemalcr/kemal#424]
I'm getting some errors on heroku while using web sockets of kemal.
here the error i'm seeing 

Mixed Content: The page at 'https://codingphasecrystal.herokuapp.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://codingphasecrystal.herokuapp.com/chat'. This request has been blocked; this endpoint must be available over WSS.

(index):24 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by drhuffman12** [comment]
Assuming this part of [the guide](http://kemalcr.com/guide/) is current, you should be able to do as follows:

# SSL

Kemal has built-in and easy to use SSL support.

To start your Kemal with SSL support.

```sh
crystal build --release src/your_app.cr
./your_app --ssl --ssl-key-file your_key_file --ssl-cert-file your_cert_file
```

**Comment by sdogruyol** [comment]
Just lie @drhuffman12 said :+1:
