### ISSUE TITLE
Accessing data in context storage safely

### ISSUE THREAD

**Issue by HiImJulien** [kemalcr/kemal#428]
### Description

For my first web application I thought of creating a simple blog engine, which uses JWT as authorization. Therefore I created a filter, which checks whether a token is present and is decodable.

The data of the given token is then stored in the context storage, in order to pass to the actual route handler.

The route then tries to access the token and handles differently depending on wether it is present or not. However, apparently, there's no way to check for a key's existence in context storage but using 
exception handlers?

### Steps to Reproduce
```crystal
put "/api/author" do
    author_id = env.get "author_id" # Raises an exception, when key is not present
end

```

**Actual behavior:** [What actually happens]
Not able to check for keys existence.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime.

### Versions

> Crystal 0.24.1 (2017-12-26)
> 
> LLVM: 5.0.1
> Default target: x86_64-apple-macosx
> 
> macOS 10.13.2 High Sierra
> MacBook (Retina, 12-inch, Early 2016)
> 

### Additional information
I am pretty new to Crystal (and Ruby); I just have little experience tinkering with Sinatra.
P.S.: I love your work! Well done!

**Comment by straight-shoota** [comment]
You should be able to use "env.store.get? "author_id"` as a non-raising method. But true, this should probably be accessible directly on the context/environment.

**Comment by sdogruyol** [comment]
This is just Crystal, if you try to access a non-existent key with `[]` in a `Hash` it'll also raise. Instead you should use `[]?` like @straight-shoota mentioned :+1:

**Comment by sdogruyol** [comment]
On second thought, I believe that we shouldn't expose `env.store` at all. Adding `env.get?` would be a better solution.

**Comment by sdogruyol** [comment]
This is now implemented in `master`. Thanks for the report @HiImJulien :+1: 

Now you can use

```crystal
put "/api/author" do
    author_id = env.get? "author_id" # Won't raise and will return nil
end
```
