### ISSUE TITLE
How to let kemal run on multi cpu core ?

### ISSUE THREAD

**Issue by bigbenz8** [kemalcr/kemal#430]
When I run benchmark test, only one cpu core is on load, how should I make it use muti cpu cores ? Is there any plugin or middleWare to do this(something like nodejs-cluster)?

**Comment by drhuffman12** [comment]
One "multiple cpu's" option would be the `reuse_port` param noted in "https://crystal-lang.org/api/0.24.1/HTTP/Server.html":

```
You may set reuse_port to true to enable the SO_REUSEPORT socket option, which allows multiple processes to bind to the same port.
```
I suppose you could wrap forked [processes](https://crystal-lang.org/api/0.24.1/Process.html) in a [benchmark](https://crystal-lang.org/api/0.24.1/Benchmark.html), but I don't know how well Benchmark would handle Processes.

**Comment by bigbenz8** [comment]
It works. Thanks for your suggestion.

**Comment by drhuffman12** [comment]
Glad to be of service :)

**Comment by sdogruyol** [comment]
Thanks @drhuffman12 :pray: 

@bigbenz8 please check https://github.com/kemalcr/kemal/issues/429#issuecomment-357211197

**Comment by drhuffman12** [comment]
@sdogruyol , yw
