### ISSUE TITLE
undefined method 'content_type' for HTTP::Server::Response error

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal#432]
### Description
Trying to build/run the example code in the *Filters* section.

### Steps to Reproduce
Direct copy/paste from the guide:
```
require "kemal"

before_get "/foo" do |env|
  puts "Setting response content type"
  env.response.content_type = "application/json"
end

get "/foo" do |env|
  puts env.response.content_type # => "application/json"
  {"name": "Kemal"}.to_json
end
```
**Expected behavior:** compile success

**Actual behavior:** compile and spec error: undefined method 'content_type' for HTTP::Server::Response error

**Reproduces how often:** every time I run a build or spec (KEMAL_ENV=test crystal spec --verbose)

### Versions
Crystal: 0.24.1
Kemal: 0.22.0
Fedora 26 Workstation 

### Additional Information
The error refers to HTTP::Server::Response not HTTP::Client::Response. Is this the correct response for the above code?

**Comment by straight-shoota** [comment]
This issue is not with Kemal but Crystal's HTTP API: `HTTP::Server::Response` doesn't have a `#content_type` getter, but only a setter `#content_type=`.

Obviously, the guides are wrong.

But it shouldn't be needed to query the content type because the application is setting that, so it should already know what it is.

**Comment by lebogan** [comment]
Still learning. Thank you for the insight.

**Comment by straight-shoota** [comment]
Please leave this issue open. The guide still needs to be fixed.

**Comment by sdogruyol** [comment]
Thanks @lebogan @straight-shoota :+1: I've fixed the guide :100:
