### ISSUE TITLE
Route specific status code handling

### ISSUE THREAD

**Issue by mitjafelicijan** [kemalcr/kemal#433]
I am developing web app that serves actuals website and I also have REST API under a different endpoint but in the same app.

domain.com/ - serves website
domain.com/api/ - serves rest api

When I try to implement REST API and use custom status code like `ctx.response.status_code = 404` this forces the response for global 404 handler.

In a case of website part I created custom handler and this looks like to have the same global effect.

```
error 404 do
  "This is a customized 404 page."
end
```

In order to implement REST API the correct way I would need to use custom handlers and not allow Kemal to prosume and display 404 page from "global scope" - html response.

So in order to ensure proper basic functions for REST with delete, get, put, post and in case of get I would need to be able to return empty response with 404 status code if element was not found. And in case of website there can be 404 handler that handles displaying 404 html page.

Is this even possible and am I missing something obvious?

**Comment by crisward** [comment]
Your api is probably requesting with a content type header of application/json check for that in the custom 404 and return the correct response.

**Comment by RX14** [comment]
You can access `ctx.request.path` in the error handler and make a decision on that.

```cr
error 404 do |ctx|
  if ctx.request.path.starts_with? "/api"
    # ...
  else
    # ... 
  end
end
```
end

**Comment by straight-shoota** [comment]
@RX14 Why did you vote down @crisward's suggestion? I think both approaches can be valid, depending on the specific API design. I guess your solution is more straightforward with regards to the question. But it may also be a goal to have all `application/json` requests to return a JSON error.
