### ISSUE TITLE
Index out of bounds with missing param

### ISSUE THREAD

**Issue by jwoertink** [kemalcr/kemal#436]
### Description

If you try to use a param key that doesn't exist, it looks like [this line](https://github.com/kemalcr/kemal/blob/master/src/kemal/exception_handler.cr#L15) is actually swallowing the real error. Instead of `KeyError:Missing hash key` you get `Index out of bounds`. 

### Steps to Reproduce
If you check out this example, you'll see I'm using `url["od"]` instead of `url["id"]`. 

```crystal
require "spec"
require "kemal"
require "spec-kemal"

ENV["KEMAL_ENV"] = "test"

get "/users/:id" do |env|
  "This is users #{env.params.url["od"]}"
end

Kemal.run
at_exit { Kemal.stop }

describe "Test" do
  it "does something weird" do
    get "/users/1"
    response.status_code.should eq 200
    response.body.should eq "This is users 1" 
  end
end
```
**Expected behavior:**
See the error message
`#<KeyError:Missing hash key: "od">` 

**Actual behavior:**
See the error message
`Index out of bounds`

**Reproduces how often:**
100%

### Versions

```
Crystal 0.24.1 (2018-01-27)
LLVM: 5.0.1
Default target: x86_64-apple-macosx (10.13.3)
Kemal: 0.22.0
spec-kemal: 0.4.0
```

### Additional Info
Commenting out that `log` line then leads to [this line](https://github.com/kemalcr/kemal/blob/master/src/kemal/exception_handler.cr#L18). It seems that it's specifically `ex.inspect_with_backtrace` that is printing out this error. If I take out all calls to that, then I see the error message I would expect. A KeyError is a lot easier to solve than Index out of bounds.

**EDIT**
Here's the error I get when I run the spec:

```
[13:59PM] tester$ crystal spec/test_spec.cr 
E

Failures:

  1) Test does something weird

       Index out of bounds
Error running at_exit handler: Index out of bounds
```

**Comment by straight-shoota** [comment]
I can't reproduce with these versions. Using `spec-kemal 0.3.0` won't compile with `crystal 0.24.1`. And with `spec-kemal 0.4.0` the spec runs as expected (failing test `response.status_code.should eq 200`).

**Comment by jwoertink** [comment]
that's strange. spec-kemal compiles fine for me on that version. I'll try and clear out my cache and try this again to see, and update what I find out.

**Comment by straight-shoota** [comment]
`spec-kemal 0.3.0` uses [`MemoryIO`](https://github.com/kemalcr/spec-kemal/blob/v0.3.0/src/spec-kemal.cr#L25). This was removed in `Crystal 0.20.4`.

**Comment by jwoertink** [comment]
oh, you're right. I am using spec-kemal `0.4.0`. 

```
version: 1.0
shards:
  kemal:
    github: kemalcr/kemal
    version: 0.22.0

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  radix:
    github: luislavena/radix
    version: 0.3.8

  spec-kemal:
    github: kemalcr/spec-kemal
    version: 0.4.0
```

**Comment by jwoertink** [comment]
Just an update on this, it doesn't strictly happen with params. I get this pretty much with any error I get when running specs. My current work around is to change `ex.inspect_with_backtrace` to `ex.message.to_s` exception_handler.

**Comment by straight-shoota** [comment]
This looks like crystal-lang/crystal#5224 not a Kemal issue.

Please try with the latest Crystal (from `master` branch) it should be fixed but is not released yet.

**Comment by jwoertink** [comment]
Ok, it looks like the master branch of crystal does fix this issue, but Kemal doesn't run on that version. I'll go ahead and close this out since it's crystal related. I'll open up a new issue for the other thing.

Thanks for finding that @straight-shoota
