### ISSUE TITLE
Kemal site configuration

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal#437]
While I realize that Kemal is nowhere as opinionated as Rails or even Amber, as a newbie, I would like to have some kind of guideline on site directory structure. Like, are all files placed in src? Where do public files like css and js go? Should I put my views in src?

I finally managed to get a simple site up and running, and I like the Sinatra-like simplicity; however, even Sinatra has some suggested directory structure. 

Is this practical? Can I help with this? I would love to see Kemal really take off like or better than Sinatra.

Thank you for this incredible framework!

**Comment by sdogruyol** [comment]
Thanks a lot. I think we can have a recipe in the Kemal Cookbook http://kemalcr.com/cookbook/hello_world/ :+1:

**Comment by jwoertink** [comment]
@lebogan Not sure if it would help or not, but my shard [fez](https://github.com/jwoertink/fez) gives you a sort of opinionated kemal structure. It may also be a little overkill depending on what your needs are.

**Comment by lebogan** [comment]
Thanks for all the responses. I am going to work more on this.
