### ISSUE TITLE
Compatibility with next Crystal

### ISSUE THREAD

**Issue by jwoertink** [kemalcr/kemal#438]
### Description

It looks like [this PR](https://github.com/crystal-lang/crystal/pull/5183/files) changed the `JSON::Type` to `JSON::Any::Type`. This causes a breaking change 

```
in lib/kemal/src/kemal/param_parser.cr:11: undefined constant JSON::Type

    alias AllParamTypes = Nil | String | Int64 | Float64 | Bool | Hash(String, JSON::Type) | Array(JSON::Type)
```

### Steps to Reproduce

1. Use the latest commit from crystal
2. run a kemal app

**Expected behavior:** Kemal to boot

**Actual behavior:** Compile error

### Versions

Latest Kemal and latest crystal from master branch

**Comment by straight-shoota** [comment]
There's already an PR for that: #435

**Comment by jwoertink** [comment]
@sdogruyol works fast! ;)

**Comment by sdogruyol** [comment]
There's already #435 waiting for Crystal 0.24.2 release :+1:
