### ISSUE TITLE
Remove powered-by header

### ISSUE THREAD

**Issue by dkimot** [kemalcr/kemal#439]
I want to remove the X-Powered-By header, is there an easy or quick way to do that?

**Comment by sdogruyol** [comment]
@dkimot one of the easiest way might be

```crystal
before_all do |env|
  env.response.headers.delete "X-Powered-By"
end
```

**Comment by dkimot** [comment]
That's perfect, thank you

**Comment by RX14** [comment]
There should be a configuration option never to add it.

**Comment by philipp-classen** [comment]
It has been implemented now (see https://github.com/kemalcr/kemal/pull/449):
```
Kemal.config.powered_by_header = false
```
