### ISSUE TITLE
Comment documentation on route definitions 

### ISSUE THREAD

**Issue by Blacksmoke16** [kemalcr/kemal#442]
### Description

Using comment documentation on route definitions does not get parsed/displayed after doing `crystal docs`

### Steps to Reproduce

1. Create a new kemal project
2. Add a route with comment documentation on it
3. Add another method also with comment documentation on it
4. Run `crystal docs`
5. Notice that only the method had documentation created.

**Expected behavior:** Docs generated for the route definitions

**Actual behavior:** It doesn't

**Reproduces how often:** 100%

### Versions

Crystal 0.24.2
Kemal 0.22.0

#### Example:
routes.cr
```Crystal
module Api2
  # Defines the routes used in the app
  class Routes
      # Test route for getting json
      get "/" do |env|
        {name: "Serdar", age: 4141414}.to_json
      end
      # Test Method
      def test
      end
  end
end
```
generated class doc
![image](https://user-images.githubusercontent.com/12136995/38150919-33959aa4-342f-11e8-8f4f-f0ec0b599be2.png)

### Use Case
I would like to use the auto generated doc comments on my route definitions to define what the endpoint is used for as well as route specific information, such as request body, auth required etc.

**Comment by straight-shoota** [comment]
`get` is a global macro and doesn't add anything to the local class scope. This might change in the future to allow scoping route definitions to a class (see #378). But still, it wouldn't add any method or constant to the enclosing class that could show up in the API docs. I don't think there would be a genuine way to do that.

It probably wouldn't be the right place for this, anyway. The API docs covers types, methods and constants and describe how to interact with a library on code level.
Routes defined in a kemal application are not part of the Crystal API, they are a HTTP API which needs to be documented separately.

**Comment by Blacksmoke16** [comment]
Fair enough, thanks for the explanation.
