### ISSUE TITLE
Logo Copyright Terms

### ISSUE THREAD

**Issue by LVMBDV** [kemalcr/kemal#457]
I was thinking of making an educational video series on Kemal and using its logo in the thumbnail but I could not find any information on its copyright status, which implies it cannot be used by any third parties under any circumstances. It this intentional or just overlooked? Also, thank you for your work on this wonderful framework.

P.S. [Here](https://crystal-lang.org/media/) is how Crystal deals with this.

**Comment by sdogruyol** [comment]
Moved to https://github.com/kemalcr/kemalcr.com/issues/32
