### ISSUE TITLE
Impossible to run Kemal with reuse_port: true

### ISSUE THREAD

**Issue by vlazar** [kemalcr/kemal#459]
### Description

Due to changes in HTTP::Server API in Crystal 0.25.0 and the way Kemal 0.23.0 starts server it's now impossible to run Kemal with `reuse_port: true`.

Ref: https://github.com/kemalcr/kemal/pull/452/files#diff-e5663d7073109a4b406e96582b8cb5c2R71

The problem is `listen` now also does `bind_tcp`:

Ref: https://github.com/crystal-lang/crystal/blob/7fb783f7afec0a199d6f22ef78aae0f45517068a/src/http/server.cr#L216-L220

### Steps to Reproduce

```crystal
# reuse_port_issue.cr
require "kemal"

get "/plaintext" do |env|
  env.response.content_type = "text/plain"
  "Hello, World!"
end

Kemal.config do |cfg|
  cfg.serve_static = false
  cfg.logging = false
end

Kemal.run do |cfg|
  cfg.server.not_nil!.bind_tcp(cfg.port, reuse_port: true)
end
```

```
$ crystal reuse_port_issue.cr
```

**Expected behavior:** It is possible to run Kemal with `reuse_port: true`

**Actual behavior:** Unhandled exception: bind: Address already in use (Errno)

**Reproduces how often:** Always

### Versions

Kemal 0.23.0

$ crystal --version
Crystal 0.25.0 (2018-06-20)

LLVM: 5.0.1
Default target: x86_64-apple-macosx

### Additional Information

Trying to update TFB to latest Crystal and frameworks here https://github.com/TechEmpower/FrameworkBenchmarks/pull/3884/commits/e6c2f9533dc8c5dbbcdc5b093d551d5b480bf622#diff-7a0f270376d33ada73bacaf95cf345fbL116

https://github.com/TechEmpower/FrameworkBenchmarks/pull/3884

**Comment by waghanza** [comment]
@vlazar Same issue if port is `3000`

**Comment by waghanza** [comment]
using `listen` it works

**Comment by vlazar** [comment]
@waghanza I'm not sure what do you mean by `listen` works. Can you share the code?

**Comment by waghanza** [comment]
@vlazar sorry, I think I have to give more details

`Kemal.run { |cfg| cfg.server.not_nil!.bind_tcp("0.0.0.0",3000, reuse_port: true) }`

seems not to work for me, but

`Kemal.run { |cfg| cfg.server.not_nil!.listen("0.0.0.0",3000, reuse_port: true) }`

works

**Comment by straight-shoota** [comment]
Yes, this works because `listen` blocks the current fiber and the code won't reach the second `listen` call until the server is stopped. It's not nice but fine as a quick workaround.

**Comment by waghanza** [comment]
@straight-shoota thanks for explanation

**Comment by vlazar** [comment]
@straight-shoota Thanks for explanation! TIL. I thought with @waghanza example two `server.listen` calls were actually made and created 2 sockets internally. It turns out that's not the case.
