### ISSUE TITLE
form-data parsing

### ISSUE THREAD

**Issue by straight-shoota** [kemalcr/kemal#461]
Currently, `ParamParser` consumes all multipart parts and stores the transmitted data in tempfiles (if a filename is present) or memory (if no filename).
This happens when `#body` is accessed, which is actually in *every single* `POST` request because `Context#route_lookup` checks for method override in a `_method` field which can be transmitted as multipart form-data. This is evaluated even before the specific handler is called and there is no way to determine if a request with attached formdata is actually valid. An application has no means to control if and how form-data uploads are handled.

If the user isn't authorized, for example, the request body shouldn't even be consumed at all. But it is automatically stored on disk. This can be inefficient and potentially even poses as a DoS threat.

It would make more sense to make the formdata handling controllable, more flexible and sophisticated by default. Sometimes, the uploaded data isn't supposed to be saved to disk at all, but rather directly processed or directed to a remote service. Automatically storing all (named) files to disk can be a unnecessary overhead.

In theory, one could just use the excellent API's `HTTP::FormData` or `HTTP:Multipart` of Crystal's stdlib directly for such customizations. But it won't work if the request is already consumed by the above mentioned method override check. This needs to be fixed to provide a way to apply a workaround using lower-level methods.

Kemal should provide an easy, automatic file upload handling but also flexible access methods for fine-grained control of upload handling.

The main issue appears to be the method override check, because it requires the multipart body to be parsed on every `POST` request in order to determine the targeted controller action. This method override might be useful in some cases. but it doesn't necessarily need to be a multipart field. Query parameter or HTTP header are equal alternatives. It would certainly make things much easier if we could remove this override check for multipart/form-data request bodies.

If we can agree on that, the next step would be to discuss changes to the API for accessing multipart/form-data fields.

See #455 for initial discussion

**Comment by sdogruyol** [comment]
I also don't think we have the best way to handle uploads now. I especially don't like consuming body beforehand and I'd be happy to discuss any changes regarding to make it better :+1:

**Comment by sdogruyol** [comment]
This is mostly implemented by #465.Thank you @straight-shoota for raising up the issue :+1:
