### ISSUE TITLE
Remove dependency on Kilt

### ISSUE THREAD

**Issue by straight-shoota** [kemalcr/kemal#467]
In my opinion, Kemal should care about providing a basic framework for handling HTTP requests.
This often implicates using a template engine, but I think Kemal should better be engine-agnostic.

Kilt is great as it simplifies integration of multiple template engines, but not all use cases actually need that. Some apps require to interact with a specific template engine directly for using advanced features, or because the engine is not supported by Kilt. An app that only serves a JSON-API might not need any template engine at all.

So, I'd suggest to remove `kilt` as a dependency for `kemal`.

Kilt should still be promoted as suggested template interface for kemal applications. But the dependency should not be required if you don't use Kilt.

The only place where Kilt is actually used is the `render` macro, which is just a short cut for `Kilt.render` and a wrapper to render a layout. Similarly, the macros `content_for` and `yield_content` rely on Kilt but they are not even universally usable with all template engines. They only work if the template engine allows to directly embed Crystal code. So it's essentially an extensions of ECR.

I'd suggest do move these features to Kilt and ECR directly. They manage specifics of template engine behaviour and Kemal shouldn't have to care about that.

Optionally, we could leave these macro helpers as is, but move them to a separate file that needs to be required explicitly when using Kilt. This would also remove the strict dependency on Kilt.

**Comment by rdp** [comment]
what should the default for templates be?  Kemal also wants to be "easy to use for beginners" as it were...

**Comment by straight-shoota** [comment]
@rdp Let the authors choose whatever they need. Crystal stdlib comes with ECR, so it's probably a good idea to use that in typical examples. But there should also be guides for using other template engines (with or without Kilt).

There are only a few things coming from Kemal: that's adding `jeromegn/kilt` as dependency and defining `macro render` as an alias to `Kilt.render`. Apart from that, the only template-related features are `content_for` and `yield_content` which should be implemented by ECR and/or Kilt directly.

So compared to using Kemal with dependency on Kilt, the adjustment is quite simple: Add the dependency yourself (only if you need more than ECR) and call `ECR.render`/`Kilt.render` instead of `render`.

**Comment by straight-shoota** [comment]
Actually, `ECR.render` didn't exist. But now there's crystal-lang/crystal#6371 :+1:

**Comment by drum445** [comment]
I think this makes sense, but as @rdp says it should be documented how to get the old functionality back.
My opinion may be biased as I use it for JSON APIs so wouldn't notice the template engine being removed by default

Cheers

**Comment by drum445** [comment]
Sinatra offers templating via erb by default, not sure why we'd want to take it out of Kemal? That is unless it causes overheads I am not aware of.

**Comment by straight-shoota** [comment]
@drum445 erb is included in Ruby's stdlib. But kilt is not in Crystal's stdlib. It's an additional dependency and in some use cases completely useless because you either need to interface with a specific template engine directly for using enhanced features, or a template engine not supported by kilt (like templates evaluated at runtime).

**Comment by drum445** [comment]
@straight-shoota That makes sense, however I think Kemal should be able to server ECR files "out of the box"; as @rdp said, Kemal should be easy to use.

**Comment by straight-shoota** [comment]
ECR is part of Crystal's stdlib and works fine without Kilt. Kilt just provides an interface for ECR, which could also be used by different engines.

We only need to figure out what to do with the `render` macro.

There are actually two versions: One receives a single file name argument and is simply an alias for `Kilt.render`. If you replace it with `ECR.render`, you're using ECR template without any involvement of Kilt.
The other adds simple layout support and uses the single-argument version to evaluate layout and content.

One option is to simply remove both from Kemal. You would have to call your template engine of choice explicitly and use the capture features it provides.

Alternatively, we could simply change the implementation to `ECR.render`. If you want to use a different engine, either call it explicitly or overwrite the `render` macro.

`content_for`/`yield_content` can probably just stay as they are in Kemal. They don't depend on Kilt anyway and in fact are very much limited to be useful with ECR.

**Comment by drum445** [comment]
@straight-shoota I like this method better, ideally this will also mean that there will be no breaking changes as the render macro can still exist but just call `ECR.render` - providing the layout and child page loading would still work as it does now.
