### ISSUE TITLE
Instance Variables and Modular Application Style

### ISSUE THREAD

**Issue by J-Mo63** [kemalcr/kemal#473]
I'm currently using Kemal to build a modular API and I'm getting an issue from all the routes being defined as part of the top level. I was hoping to use instance variables as I was looking to declare route logic as so:

``` crystal
# update route
put '/:id' do
  load_user
  build_user
  save_user
end

private def load_user
  @user = User.get(param("id"))
end

private def build_user
  @user.attributes = user_params
end

private def save_user
  @user.to_json if @user.save
end
```

On a related note I'm wondering if it's possible to have my BaseApi run as an instance of Kemal as right now I'm defining my modules with something like this, which is forcing me to define all my methods as class methods.

``` crystal
class BaseApi
  extend Formattable
  include ApiHelper

  def self.route(route : String)
    "/api" + route
  end

  before_all do |env|
    format_json env
  end
end

class ExampleApi < BaseApi
  extend Routable

  @@namespace = "/example"

  # routes to  GET /api/example/test
  get route("/test") do |env|
    {example_response: "hello!"}.to_json
  end
end

module Routable
  private def route(route : String)
    super @@namespace + route
  end
end
```

Please let me know if there's something I can do this with like a `Kemal::Base` (or if I'm missing something here) because it would be very useful.

Thanks for taking the time to read and I would appreciate any feedback on my predicament that you're willing to provide!

**Comment by sdogruyol** [comment]
This is actually WIP https://github.com/kemalcr/kemal/pull/378

**Comment by J-Mo63** [comment]
Amazing! I'll be very interested to see what you and @straight-shoota come up with on this!

**Comment by sdogruyol** [comment]
@hugopl looks useful. Would like to see a `kemal-controller` shard 👍

**Comment by hugopl** [comment]
I'll use that name, thanks! And maybe later I could create a `kemal-megazord` a shard that just glue `kemal-*` shards plus few HTMX/Slang helpers and convenience methods I wrote here to e.g. use JS import maps, CORS with nonce support, etc.

**Comment by sdogruyol** [comment]
That'll actually lead to `kemal-contrib` 🤣
