### ISSUE TITLE
How do I access the raw request body?

### ISSUE THREAD

**Issue by horrendo** [kemalcr/kemal#478]
### Description
I'm interacting with Slack. To verify the authenticity of the request I need to generate the request signature and compare it with the signature in the request header (as described [here](https://api.slack.com/docs/verifying-requests-from-slack#secret_regeneration)).

Part of that process requires me to have access to the raw request body.  Maybe I'm doing something wrong, but it seems to me by the time my route comes in to play, the Kemal ParamParser has consumed the body and I no longer have access to it.

Do I have any option other than to monkey patch Kemal::ParamParser?

### Steps to Reproduce

define a simple route:

```
  post "/some/route" do |env|
    b = env.request.body
    t = typeof(b)
    puts "b is of type #{t}"
    if b
      bb = b.gets_to_end
      puts "bb = #{bb}"
    else
      puts "b is nil"
    end if
    pp! b
  end
```

Hit that route with cURL - e.g.

```
curl --data "hello=world" http://127.0.0.1:3000/some/route
```

**Expected behavior:**

I would expect to be able to access the raw request body via env.request.body (or some other property).

**Actual behavior:**

```
b is of type (IO | Nil)
b # => #<HTTP::FixedLengthContent:0x110050060
 @closed=false,
 @decoder=nil,
 @encoder=nil,
 @encoding=nil,
 @io=#<TCPSocket:fd 11>,
 @read_remaining=0_u64,
 @sync_close=false>
bb = 
```

**Reproduces how often:** 100%

### Versions

```
[~/git/pg_csvlog]$ crystal --version
Crystal 0.25.1 (2018-06-30)

LLVM: 5.0.2
Default target: x86_64-apple-macosx
```

**Comment by straight-shoota** [comment]
>it seems to me by the time my route comes in to play, the Kemal ParamParser has consumed the body and I no longer have access to it.

Exactly. This has just recently been changed by #465 and will be included in the next Kemal release.
You could try using master to test if it solves your use case.

**Comment by horrendo** [comment]
That worked a treat. Thanks for such a quick reply. Any idea when there will be a new release?

**Comment by straight-shoota** [comment]
There is a new Crystal release 0.26.0 on the horizon, and I expect kemal to follow quickly because it contains a breaking change (see #477).

But you can just work with kemal master until then.

**Comment by horrendo** [comment]
Terrific. Thanks again !!
