### ISSUE TITLE
Add UnixServer type (Unix Domain Socket)

### ISSUE THREAD

**Issue by danykey** [kemalcr/kemal#485]
Hi, thanks a lot for Kemal.

Could you add supporting of UnixServer(Unix Domain Socket) type?
Will be nice also add to config.scheme = "unix".

For example, Nginx supports Unix sockets, so here are good reason to up a performance.
Some test demonstrates UDF is 1.5 - 2 times faster than TCP sockets.

Thanks.

**Comment by straight-shoota** [comment]
You can already use custom HTTP connections provided by `HTTP::Server` (including unix sockets) with Kemal using:

```cr
Kemal.run do |config|
  config.server.bind_unix "path/to/socket.sock"
end
```

**Comment by danykey** [comment]
Ouch .. thanks!
Missed in docs.

**Comment by straight-shoota** [comment]
I'm not sure this is even documented anywhere.

**Comment by sdogruyol** [comment]
Closing this in favor of https://github.com/kemalcr/kemalcr.com/issues/30
