### ISSUE TITLE
Using put/patch/delete methods without _method magic param

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal#486]
### Description

I have used **put/delete** prior to version 0.24.0 in a couple of my Kemal apps. After this version release I have no idea how to achieve the same result without _method. I have resorted to using **post** to achieve this. The Guide still says that these methods are valid but, I have no idea how to access them either in my routes or html. Researching online has not helped me towards any solution. Please, point me in the right direction. Thanks loads!

### Steps to Reproduce
Example route and the form accessing that route:
```
delete "/log/:id" do |env|
  entry = find_record(env.params.url["id"])
  delete_record(entry) if entry
  env.redirect "/logs"
end

form action="/log/#{entry.id}" method="POST"
  input type="hidden" name="_method" value="DELETE"
  input.btn.btn-outline-danger type="submit" value="Delete Entry"
```

**Expected behavior:** 
I expected the action to complete, ie, actually delete the record.

**Actual behavior:** 
The action generates a 404 not found error. A debug output using the Granite logger shows that the **delete** is actually a **get**?

### Versions
Crystal 0.26.0 and Kemal 0.24.0

### Additional Information

Changing the **delete** to **post** works.

**Comment by sdogruyol** [comment]
https://github.com/kemalcr/kemal/pull/500 is gonna fix this in the next release
