### ISSUE TITLE
Improve routing speed

### ISSUE THREAD

**Issue by vladfaust** [kemalcr/kemal#488]
[Prism](https://github.com/vladfaust/prism) uses @luislavena's Radix tree implementation as well. I've improved route resolve times by using `Hash` for static routes lookup as seen @ https://github.com/vladfaust/prism/issues/45.

You can easily improve Kemal's speed as well, see https://github.com/vladfaust/prism/blob/46e9ec7a214e1976ddc88f465f3c0189e5557c33/src/prism/router.cr#L182-L212. I'm open for questions, if any.

Cheers.

**Comment by samueleaton** [comment]
I did something similar in Raze back in January. Its a pretty simple addition: https://github.com/samueleaton/raze/blob/master/src/raze/radix.cr#L25
