### ISSUE TITLE
Crystal 0.27.0 Upgrade

### ISSUE THREAD

**Issue by DanielSokil** [kemalcr/kemal#502]
### Description
This issue was created as an upgrade status for Crystal 0.27.0

**Comment by DanielSokil** [comment]
### Use `File.tempfile` instead of `Tempfile`

importing Kemal into a project, results in an error:
```bash
require "kemal"
^

in lib/kemal/src/kemal.cr:4: while requiring "tempfile": can't find file 'tempfile'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

require "tempfile"

**Comment by sam0x17** [comment]
eta on a merge for this?

**Comment by sdogruyol** [comment]
There you go :tada: https://github.com/kemalcr/kemal/releases/tag/v0.25.0
