### ISSUE TITLE
content_for sometimes not yielding

### ISSUE THREAD

**Issue by taylorfinnell** [kemalcr/kemal#510]
### Description

`content_for` not always working as expected

I have code like this in `head.ecr`

`<title><%= yield_content "page_title" %> - My Site</title>`

My layout looks like this:

layouts/default.ecr
```
<!doctype html>
<html>
  <%= render "./client/views/global/head.ecr" %>
  <body>
    <div id="app">
      <div class="masthead"></div>
      <%= content %>
    </div>
    <%= render "./client/views/global/foot.ecr" %>
  </body>
</html>
```

And I call of this like so:

`render "client/views/myview.ecr", "client/views/layout/default.ecr"`

Where `myview.ecr` has:

```<% content_for "page_title" do %><%= "Foo" %><% end %>```

Sometimes, seemingly randomly the page title will be ` - My Site` instead of the expected `Foo - My Site`.

### Steps to Reproduce

I have not been able to reliably reproduce it. However, I think the issue is in macros. In this code

```
macro yield_content(key)
  if CONTENT_FOR_BLOCKS.has_key?({{key}})
    __caller_filename__ = CONTENT_FOR_BLOCKS[{{key}}][0]
    %proc = CONTENT_FOR_BLOCKS[{{key}}][1]
    %proc.call if __content_filename__ == __caller_filename__
  end
end
```

Sometimes this condition fails `__content_filename__ == __caller_filename__` and I **think** that is what is causing the issue

**Expected behavior:** `content_for` to always provide content

**Actual behavior:** `content_for` does not always provide content

**Reproduces how often:** Very low

### Versions

```
$ crystal -v
Crystal 0.27.0 (2018-11-04)

LLVM: 6.0.1
Default target: x86_64-apple-macosx

macOS: 10.13

Kemal: 0.25.1```

**Comment by sdogruyol** [comment]
This is really weird and might be related to how macros are evaluated. Could you please create a minimal repo so that I can play with it @taylorfinnell

**Comment by sdogruyol** [comment]
Hey @taylorfinnell, and update on this?

**Comment by mang** [comment]
I know this is a bit old, but in case it helps someone:

I just had the exact same issue when working with nested templates (I was generating .ecr templates with .ecr templates). I see OP is doing just this with `<%= render ... %>`. In my case the solution was as simple as escaping the ECR tag (like `<%%= yield_content ... %>`).
(Not sure if this is a bug, but the error message sure was hard to understand:)
