### ISSUE TITLE
Feature request for scoping routes to a resource

### ISSUE THREAD

**Issue by aarongodin** [kemalcr/kemal#523]
### Description

I had an idea for a feature in Kemal and am curious what you think of the idea. Thank you as well for your awesome work on this library.

### Feature

The idea is borrowed from express.js. With express, you can create a new `Router` that allows scoping of routes to a base URL. I also remember this being a useful feature in the Rails router.

Here is some example code. The `resource` method would handle the scoping of the routes to a base URL.

```crystal
require "kemal"

resource "/groups" do
  get "/" do
    # get all groups
  end

  get "/:id" do
    # get a single group
  end

  post "/" do
    # create a group
  end

  # etc...
end

resource "/groups/:id/memberships" do
  get "/" do |env|
    # note that the env object still has access to the url params of the resource
    group_id = env.params.url["id"]
    # get all group memberships
  end

  post "/" do
    # create a group membership
  end

  # etc...
end

```

Any thoughts on this feature? I could see it being useful in my current codebase.

**Comment by vladfaust** [comment]
Onyx has [recently shipped](https://blog.onyxframework.org/posts/v0_4_0_released/) that feature with `on` syntax. 

*Disclaimer — it's always good to have alternatives. Onyx is also MIT*

**Comment by sdogruyol** [comment]
@aarongodin thanks for the suggestions. I'd like Kemal core to be as simple as possible with *just* the core features. However, you can always created shard which adds this behavior on top of Kemal core.

I also stated my view before like in this comment https://github.com/kemalcr/kemal/pull/534#issuecomment-497237487
