### ISSUE TITLE
Broken pipe error when navigating between pages

### ISSUE THREAD

**Issue by drum445** [kemalcr/kemal#524]
### Description

Frequent `Error writing to socket: Broken pipe (Errno)` errors are returned on sites that use SSR (templates/views)

##### This is one way to get the error to throw, I've seen it from just general navigation however  
1. Load a page
2. Load another page
3. Use the back button in the browser and you will see the error

**Expected behavior:** When returning to a page previously loaded using the browser's back button, or navigating between pages, Kemal should not error.

**Actual behavior:** The Kemal app throws a `Error writing to socket: Broken pipe (Errno)` error everytime.

**Reproduces how often:** 60%

### Versions
Crystal 0.27.2  
Kemal 0.25.2
Ubuntu 18.10

### Additional Information
Seems to only occur when hosting sites that serve files - SSR using templates (ECR)
Doesn't cause an issue from the user's PoV, as the site behaves as expected. It does cause issues for the server/dev.

Full stack:  
```crystal
Exception: Error writing to socket: Broken pipe (Errno)
  from /usr/share/crystal/src/socket.cr:77:13 in 'unbuffered_write'
  from /usr/share/crystal/src/io/buffered.cr:139:14 in 'write'
  from /usr/share/crystal/src/http/server/response.cr:188:11 in 'unbuffered_write'
  from /usr/share/crystal/src/io/buffered.cr:205:5 in 'flush'
  from /usr/share/crystal/src/io/buffered.cr:143:7 in 'write'
  from /usr/share/crystal/src/http/server/response.cr:69:7 in 'write'
  from /usr/share/crystal/src/io.cr:1134:7 in 'copy'
  from lib/kemal/src/kemal/helpers/helpers.cr:153:7 in 'send_file'
  from lib/kemal/src/kemal/static_file_handler.cr:65:9 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/kemal/src/kemal/exception_handler.cr:8:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/kemal/src/kemal/log_handler.cr:10:35 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:24:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/http/server/request_processor.cr:16:3 in 'process'
  from /usr/share/crystal/src/http/server.cr:414:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:380:13 in '->'
  from /usr/share/crystal/src/fiber.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:72:34 in '->'
  from ???
```

**Comment by straight-shoota** [comment]
This might actually be a bug in the stdlib HTTP or socket implementation. But it would be great to have a small and specific reproducible example.

**Comment by sdogruyol** [comment]
Closing this as no way to reproduce
