### ISSUE TITLE
Unable to disable command line parsing

### ISSUE THREAD

**Issue by Hentioe** [kemalcr/kemal#526]
### Description

I set `args` to `nil` according to the comments in the source code. But Kemal is still parsing the command line arguments.

### Steps to Reproduce

`app.cr`:
```` crystal
require "kemal"

# Matches GET "http://host:port/"
get "/" do
  "Hello World!"
end

# Creates a WebSocket handler.
# Matches "ws://host:port/socket"
ws "/socket" do |socket|
  socket.send "Hello from Kemal!"
end

Kemal.run(args = nil)
````
running:

```` bash
crystal run src/app.cr -- -h
````

output:

````
    -b HOST, --bind HOST             Host to bind (defaults to 0.0.0.0)
    -p PORT, --port PORT             Port to listen for connections (defaults to 3000)
    -s, --ssl                        Enables SSL
    --ssl-key-file FILE              SSL key file
    --ssl-cert-file FILE             SSL certificate file
    -h, --help                       Shows this help
````

**Expected behavior:**

Disable parsing behavior for command line arguments.

**Actual behavior:**

Kemal is still parsing the command line arguments.

### Versions

````
➜  ~ crystal --version                  
Crystal 0.27.2 (2019-02-05)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
````

Kemal version: 0.25.2

### Additional Information

Because this caused my application's most initial development steps to stagnate, I am a newcomer to Crystal and hope to get a solution. thank you all.

**Comment by straight-shoota** [comment]
The call probably matches the wrong `Kemal.run` overload, where `nil` is interpreted as `port` argument: `.run(port : Int32?, args = ARGV)`. This should be fixed by calling `Kemal.run(args: nil)` instead, using `args:` instead of `args=`).

**Comment by Hentioe** [comment]
@straight-shoota Nice! It may be that the official tutorial does not mention the difference between `:` or `=`, or I ignored it. I have to go back and see the relevant part, thank you.
