### ISSUE TITLE
cannot find file 'mime'

### ISSUE THREAD

**Issue by simon1tan** [kemalcr/kemal#528]
Crystal 0.25.0 (2018-06-16)
LLVM: 5.0.1

Just install kemal using shards. Running simple demo results in this error:
in lib/kemal/src/kemal.cr:6: while requiring "./kemal/helpers/*"

require "./kemal/helpers/*"
^
in lib/kemal/src/kemal/helpers/helpers.cr:1: while requiring "mime": can't find file 'mime'

**Comment by Blacksmoke16** [comment]
Mime was released with crystal version `0.27.1`.  Would have to upgrade your version to get it.
