### ISSUE TITLE
Can I turn off the views/layouts to be compiled into the binaries?

### ISSUE THREAD

**Issue by petr-fischer** [kemalcr/kemal#529]
In other words, can I keep the ECR views/layouts in the files alongside the compiled crystal+kemal binary application - this leaves me free to edit views/layouts later. Is it possible?

**Comment by straight-shoota** [comment]
No, this can't work. ECR stands for embedded Crystal and your template expressions are just Crystal code. The template engine uses macros to translate the templates to Crystal and embed them into your code. For example, `Hello <%= name %>!` becomes something similar to the following:
```cr
String.build do |io|
  io << "Hello "
  io << name
  io << "!"
end
```
Crystal code needs to be compiled before it can be executed. So, ECR can't be evaluated at runtime without recompiling the program.

There are alternatives of runtime template engines though (see https://github.com/veelenga/awesome-crystal/blob/master/README.md#template-engine).
I'm the author of [crinja](https://github.com/straight-shoota/crinja) which is an implementation of the Jinja2 template language for Crystal. Being able to edit templates independently from the program binary was the main motivation for writing this shard. So maybe it fits your purpose as well.

**Comment by petr-fischer** [comment]
@straight-shoota Exactly what I need - **thanks** for this hint (and a nice shard)!
