### ISSUE TITLE
Broken pipe error after a certain amount of time

### ISSUE THREAD

**Issue by SenkJu** [kemalcr/kemal#531]
### Description

I have made several websites using Kemal in the past and never had any problems with it. However, with my latest project I have run into a prolem and am unable to figure out how to solve it. Everytime I launch my server everything is working fine for roughly 12 hours but then it randomly stops working and instead shows the following error: <img src="https://axolotl.club/318GYLLJ.png?key=ufGYPgXSWqAkWa">. 

#### Error in log:
```
Exception: Error writing to socket: Broken pipe (Errno)
  from /usr/share/crystal/src/thread.cr:69:3 in 'unbuffered_write'
  from lib/mysql/src/mysql/statement.cr:95:5 in 'build'
  from lib/db/src/db/statement.cr:96:13 in '->'
  from lib/kemal/src/kemal/route.cr:255:3 in '->'
  from lib/kemal/src/kemal/route_handler.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???
```

#### What I have tried so far:
- I disabled gzip for static content.
- I have updated Crystal to 0.28.0 from 0.27.2-

### Steps to Reproduce

Unfortunately, I'm not able to reproduce this bug in another project because I don't know what causes it.

#### Crystal Version: 
Crystal 0.28.0 [639e4765f] (2019-04-17)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

#### OS: 
Ubuntu 18.04.2 LTS (WSL)

### Additional Information

- I am using crystal-mysql.

**Comment by vladfaust** [comment]
From the error log it's clear that the error has nothing to do with Kemal. From what I can say, the MySQL socket dies. It appeared first in 0.27, right? If so, it has nothing to do with recent fiber changes either (I could think of accidental GC).

I advise you to create an issue at https://github.com/crystal-lang/crystal-mysql/issues, providing as much details as possible.

**Comment by SenkJu** [comment]
Thanks for your reply. I will do that.
