### ISSUE TITLE
Server automatic shutdown

### ISSUE THREAD

**Issue by crud-boy** [kemalcr/kemal#541]
### problem
1.  The Linux server starts the following commands through screen and nohup. The next day the website will not open and the process is still in progress.  
`
crystal run app.cr -- --ssl --ssl-key-file ./cert/2_plugins.yooeefast.cn.key --ssl-cert-file ./cert/1_plugins.yooeefast.cn_bundle.crt
`

2.  The software SSL compiled from the following command line is not accessible
`
crystal build --release app.cr -- --ssl --ssl-key-file ./cert/2_plugins.yooeefast.cn.key --ssl-cert-file ./cert/1_plugins.yooeefast.cn_bundle.crt
`

### Env
Shards installed:
  * kemal (0.25.2)
  * radix (0.3.9)
  * kilt (0.4.0)
  * exception_page (0.1.2)

Crystal 0.29.0 [fbfe8b62f] (2019-06-05)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by sdogruyol** [comment]
@crud-boy is there any way to reproduce? This issue sounds more OS/Configuration related than Kemal related

**Comment by crud-boy** [comment]
run cmd
```
screen
nohup crystal run app.cr -- --ssl --ssl-key-file ./cert/2_plugins.xx.cn.key --ssl-cert-file ./cert/1_plugins.xx.cn_bundle.crt &
exit
```
main.cr
```crystal
# -*- coding: UTF-8 -*-
require "kemal"
require "file"


get "/monkey" do | env |
  # env.redirect "/public/html/index.html" 
  render  "src/views/index.ecr"
end



ws "/ws" do |socket|
  socket.on_message do |message|
    filename = message.to_s
    content = File.read "./packages/enc/#{filename}", "UTF-8"
    socket.send content
    socket.close
  end
end


ws "/log" do |socket|
  socket.on_message do |message|
    File.open("./url.txt", "a") do |file|
      file.write(message.to_s().encode("UTF-8"))
    end
  end
end


```
app.cr
```crystal
require "kemal"
require "./src/main"

serve_static true
serve_static({"gzip" => true, "dir_listing" => true})
public_folder "./public"

Kemal.run 443
```

**Comment by rdp** [comment]
is it using 100% cpu?  If you attach with gdb what backtrace does it give?  I'm running into a similar issue...

**Comment by rdp** [comment]
If it works when you first start it, but then "fails later" possibly see this: https://github.com/crystal-lang/crystal/issues/8108

**Comment by sdogruyol** [comment]
Thanks for the update @rdp :+1:
