### ISSUE TITLE
Halt on before_all still invoke the next route

### ISSUE THREAD

**Issue by RemiKalbe** [kemalcr/kemal#542]
Same issue as #474 #475

I have this before_all
```crystal
before_all do |env|
    begin
      origin = env.request.headers["origin"]
    rescue
      halt env, status_code: 400, response: "Missing origin."
    end
end
```

But even if it `halt` the next route is called.

**Comment by mamantoha** [comment]
@RemiKalbe can't reproduce with kemal `0.26.0` 

```crystal
require "kemal"

before_all do |env|
  begin
    origin = env.request.headers["origin"]
  rescue
    halt env, status_code: 400, response: "Missing origin."
  end
end

get "/" do
  "Hello Kemal!"
end

Kemal.run
```

<img width="585" alt="Screenshot_20190805_112138" src="https://user-images.githubusercontent.com/61285/62449634-4ea3f200-b773-11e9-9a01-789f222538c6.png">

**Comment by RemiKalbe** [comment]
You don't get it, yes the browser blocks the request but the server carries on.

Tried that out, it will print hey on the console.

```crystal
require "kemal"

before_all do |env|
  halt env, status_code: 400, response: "Missing origin."
end

get "/" do |env|
  puts "Hey"
end

Kemal.run
```
