### ISSUE TITLE
Concurrent requests seem to interfere with each other

### ISSUE THREAD

**Issue by rvprasad** [kemalcr/kemal#543]
**Since I am not sure if this is a Crystal issue or Kemal issue, I have reported this to the Crystal team as well (crystal-lang/crystal#7978).**

### Description

A [simple server](https://github.com/rvprasad/thundering-web-requests/tree/master/servers/kemal-crystal) responds to get requests with random numbers in JSON format.  When the server is running on a Raspberry Pi and `ab` tool is used to issue sequential requests to the server in quick succession, the output of the server on standard output is garbled.

I am reporting the issue here as I am not sure if this is a crystal issue or a kemal issue.

### Steps to Reproduce

1. Execute the server following the instructions in [README.md](https://github.com/rvprasad/thundering-web-requests/blob/master/servers/kemal-crystal/README.md)
2. Execute `ab -n 10 -c 1 http://127.0.0.1:1234/random?num=30`

**Expected behavior:** The following or something similar should be seen in the terminal executing the server. 
```
8.108ms
8.051ms
8.403ms
8.242ms
8.209ms
8.437ms
8.095ms
7.988ms
8.126ms
8.087ms
```

**Actual behavior:** The following is seen in the terminal executing the server.
```
-159659774543452127413503ApacheBench/2.3127.0.0.1:1234/random?num=30��<�pyR�p��%�h2.3
                                                                                     /get/random34
                                                                                                  /get/rams
-1358916334152017894057263��7R뱵��Al`|��34
                                          /get/random096127.0.0.1:41128	127.0.0.1
                                                                                 /get/random2.3ms
321435393.761ms
-0.000ms
-0.000ms
4076574188583769414937274��&��5���Qg����2.3
                                           /get/random34
                                                        /get/random30
                                                                     /get/random127.0.0.1:41152	127.0ms
-902563470739474328704365�^��b�Z'�v�;�ق2ms
-108291519172398526629057��1m�EU]�K�����9�2.3
                                             /get/random34
                                                          /get/randomms
0.000ms
-0.000ms
```

**Reproduces how often:** Always

### Versions

Crystal 0.29.0 (2019-07-20)

Kemal 0.25.2

LLVM: 6.0.1
Default target: arm-unknown-linux-gnueabihf

Linux master10 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux

### Additional Information

The object file of the crystal compiler was compiled on Ubuntu/Laptop and then linked to create the executable on Hypriot/RaspberryPi.

**Comment by rvprasad** [comment]
I observed similar garbled output even after isolating `puts` into a dedicated fiber.

**Comment by rvprasad** [comment]
After some digging around (see crystal-lang/crystal/issues/7978), this issue seems to be Kemal specific as the same code snippet works fine outside Kemal handler (at call1) but not within a handle (at call2).
```
require "kemal"

def foo() 
  tp1 = "%fms" % 3.333
  puts tp1
  tp2 = "%dms" % 3.333
  puts tp2
end 

foo()   # call1

get "/random" do |env|
  foo() # call2
  ""
end

Kemal.config.logging = false
Kemal.config.port = 1234
puts "Serving at 0.0.0.0:1234"
Kemal.run
```

**Comment by asterite** [comment]
This issue can be closed, kemal has nothing to do with it.

**Comment by rvprasad** [comment]
Closing the issue as it is related to fibers in Crystal.  See crystal-lang/crystal/issues/7978.
