### ISSUE TITLE
run --ssl error

### ISSUE THREAD

**Issue by marcstein** [kemalcr/kemal#547]
### Description

I am attempting to run under SSL on Crystal 29.0 and Kemal and upon running receive an Invalid option: --ssl error

### Steps to Reproduce

1. crystal run src/newClarity.cr works correctly
2. crystal run src/newClarity.cr --ssl --ssl-key-file xxx.pem --ssl-cert-file xxx.crt

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
Invalid option: --ssl error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Crystal 0.29.0 [fbfe8b62f] (2019-06-05)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

Ubuntu 18.04

### Additional Information

cert and key are at correct paths

**Comment by rdp** [comment]
Looks like it's trying to pass "--ssl" to the crystal compiler itself.  You can "probably" avoid it by just building  src/newClarity.cr first, or by running it like "-- --ssl ..."

**Comment by sdogruyol** [comment]
@rdp is right :+1:  You should pass the flag to the Kemal app and not to Crystal compiler.

**Comment by marcstein** [comment]
Thanks!
