### ISSUE TITLE
add examples of http response code?

### ISSUE THREAD

**Issue by rdp** [kemalcr/kemal#555]
It wasn't clear to me from this guide:

https://kemalcr.com/guide/

How to set an arbitrary http response status code like "500" maybe it could be improved upon?  Thanks!

**Comment by grkek** [comment]
```ruby
get "/" do |env|
	env.response.status_code = 500
end
```

This will do the trick, if you don't want more dividable framework you can check out [grip](https://github.com/grkek/grip).

**Comment by sdogruyol** [comment]
Guess this is not so obvious, maybe we need better docs

**Comment by sdogruyol** [comment]
Moved to kemalcr repo
