### ISSUE TITLE
How to configure the public folder?

### ISSUE THREAD

**Issue by nono** [kemalcr/kemal#559]
### Description

I'd like to use a custom public folder and I don't see a good way to do that. As a work-around, I have recoded `Kemal.run`, but it looks very hackish.

### Steps to Reproduce

```crystal
Kemal.run do |config|
  config.public_folder = "./web"
end
```

**Expected behavior:** Kemal serves static files from the `web` directory

**Actual behavior:** Kemal serves static files from the `public` directory

**Reproduces how often:** always

### Versions

```
$ crystal --version
Crystal 0.32.1 [41bd18fbe] (2019-12-18)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

$ grep kemal -A1 shard.lock 
  kemal:
    github: kemalcr/kemal
    version: 0.26.1
```

### Additional Information

`config.setup` is called before `yield config` in `Kemal.run`, which means that changing the config in the block has no effect on how the config setup its handlers.

**Comment by mamantoha** [comment]
You can

```
Kemal.config.public_folder = "./web"
Kemal.run
```

**Comment by sdogruyol** [comment]
As @mamantoha mentioned 👍
