### ISSUE TITLE
run compiles previous src code

### ISSUE THREAD

**Issue by jtaber-tigernassau** [kemalcr/kemal#565]
### Description

love kemal but: 

Major problem - it appears run is caching previous run so new changes do not show
so everytime we make a change and re run or even re build the change is not reflected
[Description of the issue]

### Steps to Reproduce

modify myapp.cr  save  ie change route
crystal run src/myapp.cr

=> previous code is run with former route
??  is there a way to clear compile cache ?? 

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `crystal --version`.Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sdogruyol** [comment]
This is confusing, any way to reproduce?

**Comment by sdogruyol** [comment]
Closing as there's no way to reproduce
