### ISSUE TITLE
can't have two routes starting with the same characters on the same level

### ISSUE THREAD

**Issue by xmonader** [kemalcr/kemal#569]
### Description

can't have two routes starting with the same characters on the same level e.g `/:name/template` and `/:name/try_update` 

- related to the usage of radix tree as a router, https://github.com/luislavena/radix#caveats
- there's should be a note on the documentation or allowing swapping the router with something without that limitation

**Comment by sdogruyol** [comment]
This is a known issue, maybe we should document this @straight-shoota

**Comment by straight-shoota** [comment]
The example is incorrect, btw.: `/:name/template` and `/:name/try_update` work fine because the parameters have the same name. Differntly named parameters at the same level are impossible: `/:name/` and `/:id`.

**Comment by sdogruyol** [comment]
Closing as @straight-shoota already mentioned the issue
