### ISSUE TITLE
add automatic OpenAPI docs

### ISSUE THREAD

**Issue by ZerataX** [kemalcr/kemal#578]
Similar to it [FastAPI](https://fastapi.tiangolo.com/features/#automatic-docs) it would be incredibly helpful if kermal could automatically create documentation compatible with Swagger/OpenAPI

**Comment by mamantoha** [comment]
I think this should not be part of Kemal framework.

But if you want this you can check [icyleaf/swagger](https://github.com/icyleaf/swagger) shard which provides this feature.

**Comment by ZerataX** [comment]
definitely understand if this is outside of scope for Kemal, but the mentioned project does not provide this feature?

the idea is if I write something like this with fastAPI
```python
from fastapi import FastAPI

app = FastAPI()


@app.get("/items/{item_id}")
async def read_item(item_id: int):
    return {"item_id": item_id}
```

I can now open my browser at http://127.0.0.1:8000/docs and get automatic, interactive, API documentation:
![OpenAPI docs](https://fastapi.tiangolo.com/img/tutorial/path-params/image01.png)
