### ISSUE TITLE
Websockets fail to connect

### ISSUE THREAD

**Issue by marzhaev** [kemalcr/kemal#579]
### Description

After upgrading to Crystal 0.35.0 on Kemal's master branch I'm having issues with connecting to a WebSocket. I believe it may be further to #575 

### Steps to Reproduce

1. Follow official install instructions.
2. Create a route such as `ws "/" { |socket| Log.info { "no stuff happens here" } }`
3. Launch Kemal app.
4. Use Chrome or via wscat: `wscat -c ws://localhost:3000/`

**Expected behavior:** I expect a successful connection.

**Actual behavior:** It to connect due to "Invalid WebSocket frame: RSV2 and RSV3 must be clear".

**Reproduces how often:** All the time

### Versions

Crystal 0.35.0 (2020-06-09) 

LLVM: 10.0.0
Default target: x86_64-apple-macosx

Persists for Crystal 0.35.0 and compiled from master branch for debug purposes.
Persists for both OSs: macOS Catalina 10.15.4 and Ubuntu 18.04

### Additional Information

WebSockets actually work flawlessly for Crystal-only implementation. Breaks once Kemal is brought in. I used Wireshark and locally complied Crystal to debug. As expected, there is something to do with headers, but I cannot zero in despite many hours invested.

**Comment by mamantoha** [comment]
@marzhaev https://github.com/kemalcr/kemal/pull/577

**Comment by mamantoha** [comment]
@marzhaev please re-open an issue because it doesn't merged into master

**Comment by marzhaev** [comment]
FYI, until #577  is merged, in order to apply that patch locally you can include the following in your project somewhere after require "kemal"

```
class Kemal::WebSocketHandler
  def call(context : HTTP::Server::Context)
    return call_next(context) unless context.ws_route_found? && websocket_upgrade_request?(context)
    context.websocket.call(context)
  end
end
```
