### ISSUE TITLE
IO not flushed and connection not closed due to response extension

### ISSUE THREAD

**Issue by benoist** [kemalcr/kemal#581]
### Description

The response extension is causing web requests not to be closed on large body content

### Steps to Reproduce

get "/" do
  "a"*9000 + "!"
end

**Expected behavior:** [What you expect to happen]

The exclamation mark should be return using curl http://localhost:8080

**Actual behavior:** [What actually happens]

The exclamation mark is not returned using curl http://localhost:8080 and the connection stays open

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Versions

crystal 0.35.1

### Additional Information

This file causes the issue as it overwrites the close method, but it doenst flush the IO as is down in the original implemenation.
https://github.com/kemalcr/kemal/blob/master/src/kemal/ext/response.cr

**Comment by mamantoha** [comment]
Duplicate https://github.com/kemalcr/kemal/issues/575
