### ISSUE TITLE
`halt` as an exception

### ISSUE THREAD

**Issue by yujiri8** [kemalcr/kemal#588]
Feature request (unless there's already something equivalent to this, but I couldn't find it)

My understanding is that `halt` is the only concise way of stopping execution to return a response, and that its use of `next` makes it impossible to use in helper functions, only in routes.

I'm looking at migrating to Kemal from [FastAPI](https://fastapi.tiangolo.com). In FastAPI, I can raise an HTTPException that stops the route handler to return a specified response. Since it works by raising an exception, I can use it anywhere.

Could `halt` or an alternative work the same way?

**Comment by grkek** [comment]
- You can raise exceptions in Kemal as well

```ruby
get "/", do |env|
  raise Kemal::Exceptions::RouteNotFound.new(env)
end
```

By the way if you plan on migrating from Python to Crystal you should try the "better" and more of an object oriented version of Kemal which is Grip, a fork I have been working on.

It provides better routing and much more features than Kemal.

https://github.com/grip-framework/grip

**Comment by yujiri8** [comment]
I've looked into this a little more. I can define a custom exception class that takes the required parameters, like:
```crystal
class Exc < Exception
  def initialize(context : HTTP::Server::Context, code : Int, msg : String)
    super(msg)
    context.response.status_code = code
    context.response.print msg
  end
end
```
But the response is not sent; it sends a 500 with no message.

**Comment by yujiri8** [comment]
Oh! Nevermind I forgot `context.response.close`. This might work after all.
