### ISSUE TITLE
Kemal not closing request properly?

### ISSUE THREAD

**Issue by u89012** [kemalcr/kemal#590]
I started building an app using Kemal and started noticing the page just keeps loading even though there's nothing in the controller logic that would cause it to behave that way. I tried isolating the issue but I've no idea what causes it. I'm doing some fairly regular stuff, pull some records from a sqlite table and render the rows using render ecr. Frustrated, I tried the same code using built-in HTTP Server Handler and it just works as expected, no more indefinite page loading. It looks to me the request isn't being properly closed -- can someone with more knowledge help? I really love Kemal and would rather not use the Handler style controllers.

Another observation -- missing pages seem to take a long time to load as well (the ones with Kemal doesn't know this way)

Kemal: 0.26.1
Crystal 0.35.1 (2020-06-19)

LLVM: 10.0.0
Default target: x86_64-apple-macosx

**Comment by u89012** [comment]
Ok, this is absolutely weird but I think I've caught the offending part causing this behavior! It's adding a class attribute to a link! Not just any attribute but specifically the ones below -- I know, I can't believe this either! These css classes are from bulma btw.

Works as expected
`<a href="/new/<%=i[:code]%>">start this</a>`

Causes indefinte page loading!
`<a class="button is-link" href="/new/<%=i[:code]%>">start this</a>`

**Comment by yujiri8** [comment]
Could you show the minimal code that reproduces the problem?

**Comment by sdogruyol** [comment]
Closing this as there's no way to reproduce

**Comment by u89012** [comment]
I tried to run some old code and sure enough this problem still persists! :(
