### ISSUE TITLE
Broken StaticFileHandler spec in 1.0.0-dev

### ISSUE THREAD

**Issue by bcardiff** [kemalcr/kemal#594]
Due to https://github.com/crystal-lang/crystal/pull/5212 the following spec no longer pass with 1.0.0-dev.

```
crystal spec spec/static_file_handler_spec.cr:51 # Kemal::StaticFileHandler should gzip a file if config is true, headers accept gzip and file is > 880 bytes
```

The underlying issue is that the `response.headers["Content-Encoding"]` is removed by the `HTTP::Client`. Everything is still working fine.

The spec could be rewritten using `parse_headers_and_body` method with `decompress: false` probably.

**Comment by sdogruyol** [comment]
Fixed by #599
