### ISSUE TITLE
more user guide for beginner

### ISSUE THREAD

**Issue by YanHuaSuiMei** [kemalcr/kemal#595]
I need more user guide, where can i find?

**Comment by straight-shoota** [comment]
https://kemalcr.com/guide/ ?

**Comment by YanHuaSuiMei** [comment]
i want a Tutorial like this: [an example for beginner](https://docs.djangoproject.com/en/3.1/intro/tutorial01/) :)

**Comment by straight-shoota** [comment]
Isn't that pretty similar content? What exactly are you missing for Kemal?

**Comment by YanHuaSuiMei** [comment]
... i need a full example. Kemal guide is too little content.

**Comment by straight-shoota** [comment]
I still don't know what else you're expecting. I think the guide is already very extensive on Kemal's feature. There just isn't much more to it. Kemal is a micro frame work and much smaller than Django for example. It's more comparable to Flask in Python.

And then there are also some recpies in the [cookbook](https://kemalcr.com/cookbook/hello_world/). Maybe those could use some more commentary.

**Comment by YanHuaSuiMei** [comment]
Um... An example step by step? Friendly enough for beginners.
