### ISSUE TITLE
Support array query params?

### ISSUE THREAD

**Issue by yujiri8** [kemalcr/kemal#600]
Many other frameworks, such as Django and FastAPI, support retrieving all values of a query param instead of assuming there's only one. Example (Kemal master):

```crystal
require "kemal"
get "/" do |env|
  puts env.params.query["test"]
end
Kemal.run
```
Hit `/?test=a?test=b`.
See only "a".

Django and FastAPI provide ways to access all values assigned to the parameter as a list/array.

**Comment by Blacksmoke16** [comment]
You need to use [#fetch_all](https://crystal-lang.org/api/master/URI/Params.html#fetch_all(name)-instance-method).  E.g. `puts env.params.query.fetch_all "test"`.  Also be sure to fix your query params.  The `&` separator should be used, not another `?`.

**Comment by yujiri8** [comment]
Oh thanks, I didn't realize it was URI::Params in use.
