### ISSUE TITLE
Kemal 1.0.0 is not ready for Crystal 1.0.0 (adopt latest Kilt dependency?)

### ISSUE THREAD

**Issue by petr-fischer** [kemalcr/kemal#604]
There is Kilt dependency (set to old  0.4.x version) in the Kemal shard.yml, but the Kilt library is not ready for Crystal 1.0.0 - there is no crystal version in their shard.yml.

If there is not "crystal: x.x.x" line in shard.yml, "shards" utility treats it as Crystal requirement < 1.0.0.

Kilt developer was notified here: https://github.com/jeromegn/kilt/issues/26

**Comment by petr-fischer** [comment]
Kilt 0.6.1 released - why not adopt latest Kilt in the Kemal?

**Comment by petr-fischer** [comment]
The last problem is  `crystal-loot/exception_page` dependency - still not ready for Crystal 1.0.0.

**Comment by sdogruyol** [comment]
Yup, maybe I should try updating it :smile:

**Comment by Ash42Z** [comment]
Looks like execption_page is fixed: https://github.com/crystal-loot/exception_page/pull/21

**Comment by sdogruyol** [comment]
exception_page cut a release 👍  All good to go, closing this.
