### ISSUE TITLE
mailing list unavailable

### ISSUE THREAD

**Issue by szabgab** [kemalcr/kemal#613]
On https://kemalcr.com/community/ I saw a link to the mailing list, but when I clicked on it I was redirected to https://groups.google.com/access-error?continue=https://groups.google.com/g/kemalcr and it says "Content unavailable".

Was it moved or shut down?

**Comment by sdogruyol** [comment]
That's weird, I can still access the mailing list. However it's not active and maybe I should just shut it down 🤔

**Comment by szabgab** [comment]
Also the Gitter channel is awfully silent...

**Comment by sdogruyol** [comment]
Yeah, I think a lot of people moved to Discord

**Comment by szabgab** [comment]
Do you mean https://forum.crystal-lang.org/  or is there a Kemal specific one?

**Comment by sdogruyol** [comment]
Closing via https://github.com/kemalcr/kemalcr.com/commit/a969c63272d5b98d8fc3c06559a19898abf2076f
