### ISSUE TITLE
Kemal should not generate a HEAD handler implicitly from a GET handler

### ISSUE THREAD

**Issue by hholst80** [kemalcr/kemal#614]
### Description

get should not implicitly define a head response.

Use case. A service that provides health-check pages. A monitor would use a HEAD to obtain the status-code (which maps to the health of the application).  The current logic bypasses any call to the actual get logic and always returns a 200 independently of what the get logic. I might be wrong but I think that is even against the HTTP RFC(s). A HTTP HEAD should return the same headers as the GET call would have returned, just without the payload.

RFC violation or not, the HEAD logic is not helpful for this use-case. It actually is hurting the user. Let a user define their own head logic if they need it. The current logic is probably just broken, the get logic must be called in any instance, to get the correct headers to pass back to the client.

### Steps to Reproduce

https://github.com/kemalcr/kemal/blob/3fee0686362d7ab57048ae555bf875e278a278a3/src/kemal/route_handler.cr#L20

**Expected behavior:** [What you expect to happen]

Kemal should not auto-generate a bogus HEAD handler. In any instance it should return the same header values as the corresponding GET would have.

**Actual behavior:** [What actually happens]

Returns a Status 200 for any response matching the pattern of the corresponding get.

### Versions

1.0.0 Crystal and Kemal

**Comment by sdogruyol** [comment]
@compumike that approach sounds OK 👍 However, I'm also thinking if Kemal should totally drop auto-generated `HEAD`s. WDYT @straight-shoota ?

**Comment by straight-shoota** [comment]
I don't have a strong opinion on this. But since other webframeworks apprently implicitly generate HEAD requests, it's probably good to do the same.

**Comment by Blacksmoke16** [comment]
I'm not sure how you'd go about it, but ideally the response would have a `content-length` of whatever the related `GET` request would have been.

**Comment by compumike** [comment]
I've created a PR for this here: https://github.com/kemalcr/kemal/pull/655 

It creates a new `HeadRequestHandler` which includes a `NullIO` which captures everything written to the response in order to set a valid `Content-Length` header as @Blacksmoke16 mentioned, but drops the response body.

Let me know what you think! :laughing:

**Comment by straight-shoota** [comment]
I'm wondering if there could be a convenient solution for avoiding to copy the data on a head request.

For, example when serving a file, you don't need to load the file and pipe it into the null IO to get the size when you could just pass the file size directly.
Of course you could just add a dedicated HEAD handler for this, but it's much more convenient if you have a single handler for GET and HEAD

I'm thinking about writing something like this in a handler:
```cr
if output = context.response.output.as?(HeadRequestHandler::NullIO)
  # HEAD request, no need to read data. Size is enough
  output.out_count += File.size(filename)
else
  File.open(filename) do |file|
    IO.copy(file, context.response)
  end
end
```

**Comment by compumike** [comment]
As a detail: that wouldn't work if there were a `HTTP::CompressHandler` in the chain. Or specifically for Kemal, there's a `send_file` method in `src/kemal/helpers/helpers.cr` which does conditional compression, used by `StaticFileHandler`.

(My understanding of the standards is that if the `GET` request with `Accept-Encoding: gzip` would return `Content-Encoding: gzip\nContent-Length: 25\n`, then the `HEAD` request must also do so.)

**Comment by sdogruyol** [comment]
This is now fixed via https://github.com/kemalcr/kemal/issues/614 👍
