### ISSUE TITLE
Remove dependency on Kilt

### ISSUE THREAD

**Issue by sdogruyol** [kemalcr/kemal#617]
### Description

Now that #615 is merged, we should actually remove dependency on Kilt. This should be done without breaking `content_for` and `yield_content`

//cc @henrikac @straight-shoota

**Comment by henrikac** [comment]
Does this mean:

1. Remove the two `render` macros?
2. Refactor `content_for` and `yield_content` such that they don't use Kilt anymore?

**Comment by sdogruyol** [comment]
1 - I think we can keep the `render` methods and just reimplement them using ` ECR.render`
2 - Yes, we want `content_for` and `yield_content` not to use `Kilt`

WDYT @straight-shoota ?

**Comment by mamantoha** [comment]
@sdogruyol what about extracting removed functionality into a separated repository for example `kemal-kilt`?

**Comment by straight-shoota** [comment]
The removed functionality can be restored trivially. A shard with `macro render(filename); Kilt.render({{ filename }}); end` seems really unnecessary.

**Comment by mamantoha** [comment]
@straight-shoota agreed
