### ISSUE TITLE
content with layout seems duplicated

### ISSUE THREAD

**Issue by rdp** [kemalcr/kemal#623]
Using 

```
  kemal:
    git: https://github.com/kemalcr/kemal.git
    version: 1.1.0+git.commit.5e2efec0503622267b57d03fe7d5151000d3bf47
```

If you have a layout view with a content block, it ends up duplicating the entire thing and showing a bit of [corruption](https://github.com/crystal-lang/crystal/issues/11642) in the middle.

The expansion from my test app seemed to show something like this:
```
~> __content_filename__ = "views/page_null.ecr"
   io = IO::Memory.new
   content = (io << "this is nothinggg "
   io << "\n"
   )
   io << "<html>\n<head>\n  <title>My Kemal Application</title>\n</head>\n<body>\n  "
   (content).to_s(io)
   io << "\n</body>\n</html>\n"
   io.to_s
```
content seems to be assigned to io, then you have content.to_s(io) so duplicates...
Thank you.

**Comment by sdogruyol** [comment]
This is now fixed in 1.1.2 👍
