### ISSUE TITLE
Rendering HTML with layout file double renders the inner content

### ISSUE THREAD

**Issue by matthewmcgarvey** [kemalcr/kemal#630]
https://github.com/kemalcr/kemal/blob/59720fbd1631c9d567d74918975b3aaccbb031b7/src/kemal/helpers/macros.cr#L61-L67

`io` should not have been passed to the rendering of content so it gets added before the layout and then within the layout

Related to #629

**Comment by sdogruyol** [comment]
Just cut v1.1.2 https://github.com/kemalcr/kemal/releases/tag/v1.1.2
