### ISSUE TITLE
When use content_for with yield_content, output duplicate page content.

### ISSUE THREAD

**Issue by zw963** [kemalcr/kemal#636]
### Description

We assume have following view code.

![image](https://user-images.githubusercontent.com/549126/174387272-4056dedb-936b-4d5b-846d-256a3bd21480.png)

i render it like this:

```cr
get "/" do
  current_user = UserQuery.new.first

  render "src/views/home.ecr", "src/views/layouts/layout.ecr"
end
```

Will result in:

![image](https://user-images.githubusercontent.com/549126/174387332-8048a582-f511-4d7f-b2b6-63ba981ee6da.png)

This issue only happen when used content_for in view with  yield_content in layout.

if remove one of them, render result correct.

**Expected behavior:** [What you expect to happen]

I should never render duplicate content twice.

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

always.

### Versions

Crystal 1.5.0-dev [0123976d8] (2022-06-09)

LLVM: 13.0.1
Default target: x86_64-pc-linux-gnu

Arch Linux.

i can reproduce on 1.4.1 too.

**Comment by sdogruyol** [comment]
@zw963 thanks for the report, what's your Kemal version? I remember fixing this behavior

**Comment by zw963** [comment]
Current, i use version: 1.1.2, but, i can reproduce this on the master, i can reproduce it on d53d253 too

```sh
 ╰─ $ shards list
Shards installed:
  * kemal (1.1.2 at d53d253)
  * radix (0.4.1)
  * exception_page (0.2.2)
  * backtracer (1.2.1)
  * avram (0.23.0)
  * lucky_task (0.1.1)
  * pg (0.26.0)
  * db (0.11.0)
  * habitat (0.4.7)
  * wordsmith (0.3.0)
  * dexter (0.3.4)
  * shell-table (0.9.3)
  * pulsar (0.2.3)
  * lucky_cache (0.1.1)
  * splay_tree_map (0.2.2)
  * habitat (0.4.7)
  * cadmium_transliterator (0.1.0 at 46c4c14)
```

**Comment by zw963** [comment]
I can confirm, the install kemal version include those changes in #630

**Comment by zw963** [comment]
Hi, if need more context for this issue? if you want, please tell me, i will add it here.

**Comment by sdogruyol** [comment]
@zw963 I tried to reproduce the issue and could not reproduce. Here's the repo that I used to reproduce https://github.com/sdogruyol/kemal-layout-bug, could you please clone and run this on your local and see if it works on your side too?

**Comment by zw963** [comment]
> @zw963 I tried to reproduce the issue and could not reproduce. Here's the repo that I used to reproduce https://github.com/sdogruyol/kemal-layout-bug, could you please clone and run this on your local and see if it works on your side too?

Yes, i can, please check following screenshot.

![image](https://user-images.githubusercontent.com/549126/175805789-76eebe62-756f-4bed-9216-7f74da65be8f.png)

BTW: i consider there exists some syntax error on view, i fixed, please check following diff.

```diff
 ╰─ $ git diff
diff --git a/src/views/home.ecr b/src/views/home.ecr
index fb85025..df95b8a 100644
--- a/src/views/home.ecr
+++ b/src/views/home.ecr
@@ -1,6 +1,6 @@
 <h1> Title 1</h1>
 <h2> Title 2</h2>
 
-<% content_for "title" %>
+<% content_for "title" do %>
  <title>Inner Title</title>
-<% %>
\ No newline at end of file
+<% end %>
```

**Comment by sdogruyol** [comment]
Thank you @zw963, I can reproduce it now 👍 I'll look into what's going on

**Comment by sdogruyol** [comment]
@zw963 just merged https://github.com/kemalcr/kemal/pull/639 into master, could you please try with that. It should work now 👍

**Comment by zw963** [comment]
@sdogruyol , it works! thank you.
