### ISSUE TITLE
[Question] What is the correct way to share a object(e.g. current_user) across kemal session

### ISSUE THREAD

**Issue by zw963** [kemalcr/kemal#637]
### Description

I am newbie to kemal,  i create a site which need share current_user cross session, i get current_user info from JWT token.

code is work, but i consider there is a better way to do this, please help if any.

Following code is used to retreive user open_id (public, and can be used to retrieve user uniquely).

```cr
before_all do |env|

# skip to login page
  next if env.request.path == path.sign_in

  auth_token = env.session.string?("auth_token")

  # get current_user object
  current_user = User.get_user_by_auth_token(auth_token)

  if current_user.nil?
    env.redirect path.sign_in
  else

    # save current_user open_id to session.
    env.session.string("current_user_open_id", current_user.open_id)
  end
end
```

I retrieve current_user object from pg, and save `current_user_open_id` to session again.

Then i, have to duplicate the code for retreive  current_user from session in each need logined request block, like this:

```crystal
get "/path1" do |env|
  current_user = UserQuery.new.open_id(env.session.string("current_user_open_id")).first
   
   render "..."
end

get "/path2" do |env|
  current_user = UserQuery.new.open_id(env.session.string("current_user_open_id")).first
   
   render "..."
end

get "/path3" do |env|
  current_user = UserQuery.new.open_id(env.session.string("current_user_open_id")).first
   
   render "..."
end

# ...
```

many duplicate code  here ...

so, is there exists a more robust way to resolve this issue?  e.g. pass the `current_user` directly from `before_all` to all request blocks,
then, we only need change code in one place to update all of current_user retrieve logic.

Thank you.

**Comment by sdogruyol** [comment]
Hey @zw963 

How about turning that line into a method like

```crystal
def current_user(env)
  UserQuery.new.open_id(env.session.string("current_user_open_id")).first
end
```

Then you can access it from anywhere like

```
current_user(env)
```

How does that sound?

**Comment by zw963** [comment]
> Hey @zw963
> 
> How about turning that line into a method like
> 
> ```crystal
> def current_user(env)
>   UserQuery.new.open_id(env.session.string("current_user_open_id")).first
> end
> ```
> 
> Then you can access it from anywhere like
> 
> ```
> current_user(env)
> ```
> 
> How does that sound?

We have to pass current_user variable to template, so, i guess what you mean is:

```cr
def _current_user(env)
  UserQuery.new.open_id(env.session.string("current_user_open_id")).first
end

get path.home_index do |env|
  current_user = _current_user(env)

  render_use_layout "home.ecr"
end
```

it should work,  if this is the expect usage for kemal (do the best), that is okay, though, consider not well.
