### ISSUE TITLE
A simple hello world kemal app run on windows failed. (but compilation on github action successful)

### ISSUE THREAD

**Issue by zw963** [kemalcr/kemal#658]
### Description

Following is a show case project for compile kemal app for windows use github action.

it compile successful, and uploaded into [release](https://github.com/crystal-china/crystal_hello_world/releases/tag/test)

but, when run it from a windows 10 virtual box, it failed, following is screenshot.

![image](https://user-images.githubusercontent.com/549126/236694638-98a63b02-7cc0-4391-96af-96daca4e24a1.png)

Thanks

**Comment by straight-shoota** [comment]
`Signal.trap` is not supported on Windows. This needs to be migrated to a portable API: https://crystal-lang.org/api/1.8.1/Signal.html#portability

**Comment by Sija** [comment]
Resolved by #666
