### ISSUE TITLE
Adding Handlers

### ISSUE THREAD

**Issue by RainbowZephyr** [kemalcr/kemal#664]
Hello, 
This is not an issue per se, I just wanted to know if it is possible to add handlers programmatically during the server initialization. I tried doing the following but it was not working:

```crystal
Kemal.run do |config|        
       config.add_handler(MyHandler.new)
       server = config.server.not_nil!
end
```

Am I initializing the handler wrong?

Thanks in advance

**Comment by straight-shoota** [comment]
At the point where the block executes, kemal has already setup all handlers ([calling `config.setup`](https://github.com/kemalcr/kemal/blob/cb9adcd188162f1e3c83ff98263d3587b9a2f9ab/src/kemal.cr#L33)).
Thus, adding handlers afterwards in the `run` block won't have any effect.

It should be possible before calling `Kemal.run`, though.
```cr
Kemal.config.add_handler(MyHandler.new)
Kemal.run do |config|
  server = config.server.not_nil!
end
```
