### ISSUE TITLE
Date Header Missing from Kemal

### ISSUE THREAD

**Issue by tusharmath** [kemalcr/kemal#668]
### Description

Currently by default the date header is missing from the server. This is non standard behaviour as per the RFC

> Origin servers MUST include a Date header field in all responses,
   except in these cases:

RFC — https://datatracker.ietf.org/doc/html/rfc2616#section-14.18

### Steps to Reproduce

1. Write a crystal file `main.cr`
  ```crystal
  require "kemal"
  
  get "/" do
    "Hello World!"
  end
  
  Kemal.run
  ```
2. Start the server using `crystal main.cr`
3. Dispatch curl command
  
    ```bash
    curl -i http://localhost:3000
    ```

**Expected behavior:**
Expect the server to send a Date header

**Actual behavior:**
The server does not send a Date header

**Reproduces how often:** 
100%

### Versions
all versions

Linking another issue here https://github.com/graphql-crystal/benchmarks/pull/233

**Comment by wowi42** [comment]
More like a note, but I will do it as my first contribution: need to implement Date: rfc 2822

**Comment by tusharmath** [comment]
Thanks @wowi42!
I updated the steps to reproduce this issue.
