### ISSUE TITLE
kemal-hmac 🔒

### ISSUE THREAD

**Issue by GrantBirki** [kemalcr/kemal#692]
👋 Hey @sdogruyol! I have been dabbling with crystal a bit and decided to write an plugin for kemal based off of [kemal-basic-auth](https://github.com/kemalcr/kemal-basic-auth). 

The shard is named [kemal-hmac](https://github.com/GrantBirki/kemal-hmac) and it is designed to be a super simple HMAC auth implementation for kemal.

kemal-hmac has:

- 100% test coverage
- acceptance tests
- documentation
- performance tests

I was wondering if it would be best to transfer the project into the `kemalcr` org rather than have it live under my own personal account. I'm fine with either option but I want it to live in a place that would best serve the community.

Thank you for all the great work you have done with Kemal! ❤

**Comment by sdogruyol** [comment]
Hey @GrantBirki 👋 Thanks a lot for the great library 🙏 

We officially maintain any library under kemalcr organization. If this library is transferred there, it needs to be maintained too and I have no previous experience about hmac. If you are willing to maintain we can think about it. WDYT @straight-shoota?

**Comment by GrantBirki** [comment]
@sdogruyol would you like me to initiate a repo transfer into the `kemalcr` org? If so, once it completes is there a way I could retain `write` access to the repo to maintain it? Thanks!

**Comment by sdogruyol** [comment]
Hey @GrantBirki, sorry for the late response. Let's transfer the repo to `kemalcr`organization. I can take a look at giving you the needed access level.

**Comment by GrantBirki** [comment]
Hey no worries!

It looks like I'm not able to complete the transfer as I need the ability to create repos there first 👀 

![Image](https://github.com/user-attachments/assets/7c7bbf66-077b-41a1-bf11-6a6694fb176d)

**Comment by sdogruyol** [comment]
@GrantBirki invited you to the organization

**Comment by GrantBirki** [comment]
Transfer complete! ✅ 

![Image](https://github.com/user-attachments/assets/68844e60-2c74-491b-8a78-69094ba663e4)

I think we are all set now. Thank you 🙇

**Comment by sdogruyol** [comment]
Thanks a lot @GrantBirki 👍 and welcome to Kemal :)
