### ISSUE TITLE
error: undefined method 'headers'

### ISSUE THREAD

**Issue by kebasyaty** [kemalcr/kemal#697]
Hello!

Kemal v1.6.0
error: undefined method 'headers' for http::server::context
code:
  static_headers do |response, _filepath, filestat|
    response.headers.add("Access-Control-Allow-Origin", Vizbor::Settings.app_url)

Kemal v1.5.0 - there is no such error and it works fine.

Please, fix this.
Thanks in advance.

**Comment by Sija** [comment]
That's not a bug, see #681

**Comment by sdogruyol** [comment]
Thanks a lot for pointing out @Sija 👍 

@kebasyaty changing your code to 

```crystal
static_headers do |context, _filepath, filestat|
context.response.headers.add("Access-Control-Allow-Origin", Vizbor::Settings.app_url)
```

should do the trick

**Comment by kebasyaty** [comment]
Thank you!
