### ISSUE TITLE
Sessions plugin

### ISSUE THREAD

**Issue by Thyra** [kemalcr/kemal#91]
Hi, I started writing a session plugin because I want to use Kemal for my applications and I need to be able to work with sessions: https://github.com/Thyra/kemal-session
It's quite crude yet and needs a lot of improvements but I thought you might be interested...

**Comment by sdogruyol** [comment]
Nice job :+1: I'll check this out as soon as i can.

**Comment by sdogruyol** [comment]
@Thyra i want to have sessions built-in to Kemal. What's your status on this?

**Comment by Thyra** [comment]
Yes, certainly not a bad idea! Do you already know how to do it exactly?

**Comment by mperham** [comment]
I'd like to see this too.  Sessions are necessary to guard against CSRF and replay attacks.

**Comment by Vanhecke** [comment]
By having sessions handled by middleware, I'm unable to access the `env.session` variable in other middleware and filters.

**Comment by Thyra** [comment]
Well, so what's the plan now? I don't like to have multiple parallel implementations of the same feature, especially when they are not compatible.
So I would suggest we merge the two (probably best in this repo here). WDYT @sdogruyol ?

**Comment by sdogruyol** [comment]
Hey @Thyra, i agree that it's better to have one version. I think basic in-memory store is the simplest one to have and maybe we can extend the session store to file system with your version?

WDYT?

**Comment by Thyra** [comment]
I just looked at mperhams code and it is a very different approach from mine. So it won't be possible to simply "merge" the two, I'm afraid. Firstly, some decisions need to be made:

**Data types**
My version supports Int32, String, Float64 and Bool values which are accessible through `session.int, session.string, session.float` and `session.bool` (eg `session.int("number")`). Mperhams version only supports strings, but they are accessible more easily (`session["foo"]`). So: Do you want strings only or more data types? It would also be possible to default `session("foo")` to `session.string("foo")` in my version, but I think that could be confusing.

**Engines**
My version is meant to be easily extensible: There is a modular engine system that can use all different kind of engines (=storage methods), eg in-memory, filesystem, database, network... That adds a lot of complexity to the code but I like it because it seems much more clean to me than mperhams solution.

**Configuration**
My version is configurable (cookie name, timeout for sessions etc.) whereas mperhams version has hard coded values.

So depending on what you would like better, I would suggest to either recreate the nice features of mperhams version in my version (in-memory storage, better accessibility, manually delete sessions) and incorporate it into kemal, or stick with mperhams version. But then there is nothing really that could be merged into it from my version.

What do you all think?

PS: I don't want to spawn any mperham-vs-Thyra competition, this is only about what makes the most sense.

**Comment by mperham** [comment]
I did the bare minimum necessary to solve the problem: apps using Kemal are vulnerable to CSRF.  Adding different stores, datatype support, cookie configuration, encryption and tamper-detection, etc are totally up to @sdogruyol.

**Comment by sdogruyol** [comment]
@Thyra i think having an in memory store as simple as @mperham's is good and does the bare minimum to have it in `Kemal` itself.

However we still need something like yours which does file storage, database, extensibility and more data types. 

So i am thinking of making the session engine integration configurable and integration with other session engines like yours simple.

**Comment by Thyra** [comment]
But this is exactly what I did five months ago: My session plugin is not a session engine, it is a platform for session engines that makes it easy to create many different engines like memory, file system, database etc. ( https://github.com/Thyra/kemal-session/wiki/Creating-your-own-engine ). My file system engine is just an example and I created it first because I knew this was the way how PHP handled sessions by default.
It would be trivial to implement a memory engine for my session plugin, but I don't see how you would make the current solution extensible without bascially re-inventing my whole modular setup.

But whatever, I don't have time for any coding right now and this discussion is starting to annoy me.

So, please, look at my code, see if there is anything you can use or you want to use, and if not, start from scratch.

**Comment by sdogruyol** [comment]
@Thyra taking a look back at this. I think it'll be better to remove all session related stuff from `kemal` and move it to `kemal-session`.

I think Express' https://github.com/expressjs/session is a good practice for this.

**Comment by sdogruyol** [comment]
I've started working on https://github.com/sdogruyol/kemal-session

**Comment by Thyra** [comment]
Yes, that looks very good to me! :-)

**Comment by sdogruyol** [comment]
@thyra I have moved it under Kemal organization github.com/kemalcr thank you

**Comment by Thyra** [comment]
I think you created some chaos with the garbage collector, though: You spawn a gc fiber every time a Session object is created. That happens at least once every HTTP request. So after a short time, you will have hundreds of gc fibers running.
Additionally, the memory engine sleeps in its run_gc method on line 50. So now the gc interval is twice as long as the user intends.

Also I think you should enable GitHub issues on kemal-session itself so people don't have to clutter the main repo here ;-)

**Comment by sdogruyol** [comment]
@Thyra can you please open an issue on that repo. Closing this 👍

**Comment by Thyra** [comment]
As I said, you have to enable issues for kemal-session. Right now nobody can open an issue there.

**Comment by sdogruyol** [comment]
@Thyra done
